### ISSUE TITLE
'pause' module doesn't pause if a host chosen to execute the module code is skipped due to conditional

### ISSUE THREAD

**Issue by uvizhe** [ansible/ansible-modules-core#773] opened 2015-02-11 14:23 UTC
##### Issue Type
- Bug Report

Example:

```
$ cat hosts
[group1]
host1.net

[group2]
host2.net
```

```
$ cat playbook.yml 

---
- hosts: all
  tasks:
    - pause: seconds=1
      when: "'group1' in group_names"
```

Seems the module chooses the first host in last (in lexical order) group to execute the module code.
Result:

```
$ ansible-playbook -i hosts playbook.yml 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [host1]
ok: [host2]

TASK: [pause seconds=1] ******************************************************* 
skipping: [host2]

PLAY RECAP ******************************************************************** 
host1 : ok=1    changed=0    unreachable=0    failed=0   
host2 : ok=1    changed=0    unreachable=0    failed=0
```

This becomes a real problem when I use this module in some included playbook and need to restrict hosts this playbook runs on.

**Comment by mtupitsyn** [comment] 2015-03-06 22:40
Seems like a duplicate of https://github.com/ansible/ansible-modules-core/issues/96 to me ...

**Comment by jctanner** [comment] 2016-05-02 20:23
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- The pause module "should" pause on a task even if the first or any host in the current hostgroup is in a failed state.

However, however what is happening is that:
- The action plugin for the pause module makes use of BYPASS_HOST_LOOP which effectively sets the task to "run once" mode. The behavior of run_once is pretty well documented: http://docs.ansible.com/ansible/playbooks_delegation.html#run-once

We would suggest:
- Checking the documentation for run_once and if you find gaps, please file a docs bug with suggestions.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Closed as completed by jctanner** 2016-05-02 20:23 UTC
Labels: P2, bug_report
