### ISSUE TITLE
async task did not complete within the requested time due to warnings from module

### ISSUE THREAD

**Issue by daniel-sc** [ansible/ansible-modules-core#2242] opened 2015-10-10 19:16 UTC
The `gce` module (EDIT: probably all gce\* modules) appearently is not configured correctly w.r.t logging.

On the console it outputs: `No handlers could be found for logger "libcloud.common.google"` - this is not really bad, but if I use a async task, as e.g.:

```
- name: create instance
  hosts: localhost
  connection: local

  tasks:

  - name: create instance task
    gce:
      name: test-instance
      state: active
      machine_type: f1-micro
    async: 1000
    poll: 15
```

This fails with an misleading error: 

```
TASK [create instance task] *******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "async task did not complete within the requested time"}
```

My investigation showed that the corresponding async-file ( `~/.ansible-async/JOB_ID` ) as well contains the warning:

```
No handlers could be found for logger "libcloud.common.google"
```

This is why the job fails!

To check this I created a NullHandler for the logger (see https://github.com/daniel-sc/ansible-modules-core/commit/eba03a9bebc1cea43dc7133fbc23bf643ff0c9b5 ) and then the task succeeds!

Of course the above commit is probably not the solution - and maybe even something in my setup might be wrong, but probably this or some similar issue is kicking of many others - see e.g. https://github.com/ansible/ansible/issues/9798 https://github.com/ansible/ansible/issues/5356

**Comment by robynbergeron** [comment] 2015-10-12 08:12
@daniel-sc -- Thanks for submitting this bug report. You might want to consider giving us the following additional information to help the module maintainer identify the issue: https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md

@erjohnso -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by robynbergeron** [comment] 2015-10-12 08:12
[module: cloud/google/gce.py]

**Comment by daniel-sc** [comment] 2015-10-17 13:00
My system configuration:
- Ubuntu 15.04
- ansible --version: 

```
ansible 2.0.0 (devel 450c8d45c6) last updated 2015/10/17 14:41:12 (GMT +200)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/10 11:23:31 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/10 11:23:54 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = None
```

**Comment by daniel-sc** [comment] 2015-10-22 17:13
Hi @robynbergeron, @erjohnso do you need any other information?

**Comment by bemyak** [comment] 2016-01-28 10:45
Hi! It looks like this bug also affects me.
OS: Ubuntu 14.04, Arch
On Ubuntu:

```
$ ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

On Arch:

```
$ ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

I haven't got `libcloud.common.google` error mentioned by @daniel-sc above.
In my case ansible fails task when the first "poll" time comes, like if it is "async" time.
My error message looks like this:

```
fatal: [ci_test_host]: FAILED! => {"changed": false, "failed": true, "msg": "async task did not complete within the requested time"}
```

The task is configured as follows:

```
    - name: Run integration tests
      shell: docker run
             -v /tmp/logs:/opt/testing
             --name integration_tests
             --link ci_test_core:core
             --link ci_test_backoffice:backoffice
             --link ci_test_stubs:stubs
             dr.dibr.lanit:5000/ci_testing:0.1
      async: 36000
      poll: 60
```

And it fails after 1 minute with the error about requested time. If I increase poll time to 120, It'll fail in 2 minutes.

**Comment by mssch** [comment] 2016-02-15 16:45
+1

Facing the same issue, logically affects all gce_\* modules since they all use libcloud.

ansible 2.0.0.1 (tested/failed with HEAD as well)
apache-libcloud==0.20.1

**Comment by skyzyx** [comment] 2016-02-24 03:02
##### Issue Type:
- Bug Report

##### Ansible Version:

```
ansible 1.9.4
  configured module search path = None
```

##### Ansible Configuration:

```
[defaults]
# We use a dynamic inventory script, where hosts may be torn down and rebuilt
# at any given point. This means IPs may be reused on a different host (and as
# a result, a different host keypair) in the future, so we don't want to deal
# with host key checking.
host_key_checking = False
```

##### Environment:

CentOS Linux release 7.2.1511 (Core), Google Compute Cloud

``` bash
$ /usr/bin/pip freeze
ansible==1.9.4
apache-libcloud==0.20.1
Babel==1.3
backports.ssl-match-hostname==3.5.0.1
chardet==2.2.1
configobj==4.7.2
decorator==3.4.0
ecdsa==0.11
httplib2==0.9.2
iniparse==0.4
Jinja2==2.7.2
kitchen==1.1.1
MarkupSafe==0.11
paramiko==1.15.1
perf==0.1
pyasn1==0.1.8
pycrypto==2.6.1
pycurl==7.19.0
pygobject==3.14.0
pygpgme==0.3
pyliblzma==0.5.3
python-dateutil==1.5
python-keyczar==0.71rc0
pytz===2012d
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.10
six==1.9.0
slip==0.4.0
slip.dbus==0.4.0
urlgrabber==3.10
wheel==0.26.0
yum-metadata-parser==1.1.4
```

##### Summary:

While running https://github.com/ansible/ansible/blob/v1.9.4-1/plugins/inventory/gce.py with CentOS 7’s built-in Python 2.7.5, I'm receiving the following error _“No handlers could be found for logger "libcloud.common.google"”_.

##### Steps To Reproduce:

Create a file called `env` that sits in the same directory as `gce.py`, with the following contents.

``` python
#! /usr/bin/env python
'''
Automation Test Environment Inventory script wrapper
'''

import os

dir = os.path.dirname(os.path.realpath(__file__))

os.environ["SSL_CERT_FILE"] = os.path.join(dir, "ca-bundle.crt")

os.environ["GCE_EMAIL"] = "{redacted}@developer.gserviceaccount.com"
os.environ["GCE_PEM_FILE_PATH"] = os.path.join(dir, "pemfiles/{redacted}-gcloud.pem")
os.environ["GCE_PROJECT"] = "{redacted}"

os.environ["ANSIBLE_HOST_KEY_CHECKING"] = "False"

os.environ["GCS_ACCESS_KEY"] = "{redacted}"
os.environ["GCS_SECRET_KEY"] = "-----BEGIN PRIVATE KEY-----\n{redacted}\n-----END PRIVATE KEY-----\n"

execfile(os.path.join(dir, "gce.py"))
```

After that, run the Python script.

``` bash
$ python env
No handlers could be found for logger "libcloud.common.google"
[JSON output]
```

When used with Ansible…

``` bash
$ ansible-playbook -i inventories/env deploy.yml --limit *www*
ERROR: Specified --limit does not match any hosts
```

##### Expected Results:

I expected that the Ansible playbook would execute successfully.

##### Actual Results:

I received the error `ERROR: Specified --limit does not match any hosts`.

**Comment by mssch** [comment] 2016-02-24 14:10
cc @daniel-sc @erjohnso 
any update on this ?

This seems to have been introduced by apache/libcloud@5abd001dfcd518166c7d332c8e2dd57d900fdbf5

it seems better fitted to fix in libcloud, though I'm not sure whats the best approach (add `logger.baseConfig()` in libcloud/common/google.py or just remove the warning in libcloud and enforce it in clients e.g. ansible or salt)

Thx

**Comment by bcoca** [comment] 2016-02-24 14:18
@skyzyx the logging  message is a warning and can be ignored, the error you are getting is that --limit does not match any hosts, that happens when you put in an expression that added to play target yields an empty list. 

This does not seem to be a gce issue (unless it is not returning the correct list of hosts), please check the list of hosts returned vs your hosts and --limit expressions.

@skyzyx please don't hijack this thread which also has a different error

**Comment by bcoca** [comment] 2016-02-24 14:21
@daniel-sc  same red herring, the logging warning can be ignored (yes, it shoudl be fixed, but different issue) I updated the ticket with your actual error message.

**Comment by bcoca** [comment] 2016-02-24 14:23
Looking at the original issue, this seems to be a timeout when going against the API, taking longer than the allotted time, I'm not sure that this is an issue with Ansible itself or the modules. Please try running w/o async to see if you can get a different error or observe that the call does exceed the timeout.

**Comment by mssch** [comment] 2016-02-24 14:25
@bcoca, the logging warning is harmless for most tasks but will, as mentioned by @daniel-sc, cause async tasks on gce modules to fail due to the **No handlers could be found for logger "libcloud.common.google"** string being prepended to the module json output

**Comment by bcoca** [comment] 2016-02-24 14:28
@mssch point taken, missed that

**Comment by daniel-sc** [comment] 2016-02-24 16:35
@bcoca : @mssch described it perfectly!
I think this should be handled by ansible (ansible should not rely on libcloud to not emit warnings)

**Comment by bcoca** [comment] 2016-02-24 16:36
i agree, though this would be 2 issues then:
a) gce should not emit warnings like that in any case (this ticket)
b) async_wrapper should deal with it more gracefully (new ticket in core?)

**Comment by erjohnso** [comment] 2016-03-08 18:50
I tried reproducing this but failed. However, I can mimic the behavior with `async_wrapper` if I pass in a bogus value such as an invalid machine_type. This will cause the GCE module to throw an error and then exhibits the same behavior (e.g. async error `async task did not complete within the requested time`). I can then see the stacktrace in async/job_id.

If I don't use `async` and re-run the example with the bogus machine type, ansible displays the error message properly. So I think that confirms that `async_wrapper` needs a fix.

To fix up the GCE modules, it seems like the best solution would take out that logging issue in libcloud [https://github.com/apache/libcloud/commit/5abd001dfcd518166c7d332c8e2dd57d900fdbf5]. I can take that out now, but it'll be a while before the next release of libcloud.

**Comment by gmangin** [comment] 2016-03-15 15:02
You should use [serial](http://docs.ansible.com/ansible/playbooks_delegation.html) instead of async. I couldn't make async work so i did:
- playbook: playbook/createMygroup.yml

```
- name: create instances
  hosts: mygroup
  connection: local
  gather_facts: no
  serial: "100%"

  tasks:
  - name: create instance task
    gce:
        instance_names: "{{ name }}"
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        project_id: "{{ project_id }}"
        pem_file: "{{ pem_file }}"
        service_account_email: "{{ service_account_email }}"
```
- host file: inventory/hosts

```
  [mygroup]
  toto
  tata
```
- inventory/host_vars/toto and inventory/host_vars/tata

```
 name: toto
 machine_type: n1-standard-1
 image: debian-8
```
- inventory/group_vars/mygroup

```
service_account_email: <YOURSERVICE>
pem_file: "<YOUR PATH PERM.FILE>"
project_id: <YOUR PROJECT ID>
```
- ansible-playbook -i inventory playbooks/createMygroup.yml

It is very useful to launch very fast many instances, it take only the time of one instance.

**Comment by mssch** [comment] 2016-03-22 16:07
Seems ansible/ansible#15037 was merged for addressing the same issue as mentioned here, but in the GCE inventory.

> To fix up the GCE modules, it seems like the best solution would take out that logging issue in libcloud [apache/libcloud@5abd001]. I can take that out now, but it'll be a while before the next release of libcloud.

+1 for fixing this upstream

**Comment by erjohnso** [comment] 2016-03-24 17:52
Ok, fixed up libcloud [https://github.com/apache/libcloud/commit/9908ce12d759555ece38d0208391aa4438d2f83c]. No ETA on the next release, but this will be included for sure.

Given that there is a fix for GCE merged, and the fix for libcloud, then I think this specific issue can be closed.  However, I do think the suggestion from @bcoca [https://github.com/ansible/ansible-modules-core/issues/2242#issuecomment-188342887] to create another issue to track just the async_core work should be followed.

**Closed as completed** 2016-03-24 17:52 UTC
Labels: bug_report, cloud
