### ISSUE TITLE
Allow apt_repository to specify filename created

### ISSUE THREAD

**Issue by gdevenyi** [ansible/ansible-modules-core#2002] opened 2015-09-02 18:30 UTC
Issue Type: Feature Idea

Ansible Version: ansible 1.9.2

Environment: Ubuntu 14.04

Summary:

I request a feature to allow me to specify what filename the apt_repository creates

apt_repository: repo='deb http://archive.canonical.com/ubuntu hardy partner' state=present filename=hardy-partner.list

Steps To Reproduce:

When I add a repo such as:
deb http://dl.google.com/linux/talkplugin/deb/ stable main

A file is created named:
dl_google_com_linux_chrome_deb.list

When I install the package google-chrome-stable, which comes from this repo, it creates:
google-chrome.list

With the same repo content, so apt-get complains about duplicate entries

Expected Results:

Clean repository

Actual Results:

Duplicated repo entries

**Comment by gdevenyi** [comment] 2015-09-02 18:30
Patch available here https://github.com/mscherer/ansible/tree/fix_8904

**Comment by mattclay** [comment] 2015-12-17 08:39
This is a duplicate of issue #14, which happens to have an open PR #2696.

**Comment by bcoca** [comment] 2015-12-17 16:06
closing as dupe

**Closed as completed by bcoca** 2015-12-17 16:06 UTC
Labels: feature_idea
