### ISSUE TITLE
Module ini_file removing fail removing options

### ISSUE THREAD

**Issue by jruix** [ansible/ansible-modules-core#212] opened 2014-10-22 10:56 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Ubuntu 14.04
##### Summary:

When trying to modify options in a .ini file I found some options where removed in the process:

The task:
- name: set db connection data into app.ini
  ini_file: dest=application.ini option=options.dbname section=user value='dbname'

It's modifying correctly the option defined in the task but removing the options below that were in the file before I executed the ansible task:
resources.smarty.plugins[] = APPLICATION_PATH "/../library/"
resources.smarty.plugins[] = APPLICATION_PATH "/../vendor/"
resources.smarty.plugins[] = APPLICATION_PATH "/../vendor/"

Looks like the quotes in combination with the 'APPLICATION_PATH' string after them  or the '[]' char is causing the problem.
## \- create a file.ini file with the content below:

```
[user]
options.dbname= xx 

[res]
resources.smarty.plugins[] = APPLICATION_PATH "/../library/"
resources.smarty.plugins[] = APPLICATION_PATH "/../vendor/"
resources.smarty.plugins[] = APPLICATION_PATH "/../vendor/"
```

---
- execute the task below task using the created file for the paramater 'dest':
  - name: Bug in ini_file module test
    ini_file: dest=file.ini option=options.dbname section=user value='dbname'
## file.ini

```
[user]
options.dbname= dbname

[res]
resources.smarty.plugins[] = APPLICATION_PATH "/../library/"
resources.smarty.plugins[] = APPLICATION_PATH "/../vendor/"
resources.smarty.plugins[] = APPLICATION_PATH "/../vendor/"
```

---

options in the section res have been removed
## file.ini

```
[user]
options.dbname= dbname

[res]
```

---

options in the section res have been removed

**Comment by Jmainguy** [comment] 2014-10-28 15:08
So here is what is happening

First the module determines if it needs to make a change, if it does, then it edits the file.

If it edits the file, it appears to remove duplicate key's, so the following

```
[res]
jon = john
jon = jonathan
jon = jonathon

[user]
options.dbname= dbnameaaaaa
```

gets changed to 

```
[res]
jon = john

[user]
options.dbname= dbname
```

I do not know how the ini file would work, if there were duplicate keys to begin with, so I do not know if this is actually a bug, or expected behavior. Can someone confirm whether this is good behavior, or a bug?

**Comment by jruix** [comment] 2014-10-30 11:20
I would consider parameters ended [] as arrays and I wouldn't remove them.

Note that all the parameters with [] are being removed in my example what is slightly different compared to the behaviour you're showing in your example

**Comment by jctanner** [comment] 2016-04-26 22:40
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

Our reasons and evidence for this are:

I tested your example with "ansible 2.1.0 (devel 008bde91a8) last updated 2016/04/26 10:34:49 (GMT -400)" and had a result that is what you requested ...

```
$ diff file.ini file.ini.bak
2c2
< options.dbname = dbname
---
> options.dbname= xx
```

And we suggest that:
- Update to a newer version of ansible and revalidate your issue.

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by jctanner** 2016-04-26 22:40 UTC
Labels: P2, bug_report
