### ISSUE TITLE
mount module doesn't work correctly with mount option "bind"

### ISSUE THREAD

**Issue by jamesgoodhouse** [ansible/ansible-modules-core#86] opened 2014-09-30 17:09 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

Ansible is running from OS/X Mavericks 10.9.2
I am managing an Ubuntu 12.04 instance
##### Summary:

When using the mount module and specifying an option of "bind", the filesystem is mounted over and over. This has been tracked down to what appears to be Python's os.path.ismount(path) returning false for any mounts with the bind option applied.
##### Steps To Reproduce:

Create a mount using the mount module with the following options:
- fstype: none
- opts: rw,bind
- state: mounted
##### Expected Results:

I expect to see the mount point show up in /etc/fstab, the mount point to show when the command "mount" is ran in the terminal, and for the Ansible task to not show as "changed" for each run when no change has occurred.
##### Actual Results:

The mount point shows up properly in /etc/fstab, but the mount point is mounted each time the Ansible task is ran, causing it to be mounted over and over on the system as well as for the Ansible task to show the status of "changed".

**Comment by jamesgoodhouse** [comment] 2014-09-30 17:10
The original ticket was created on the main project repo but closed when modules were moved to a separate repo. Here is the original ticket: https://github.com/ansible/ansible/issues/7121

**Comment by Jmainguy** [comment] 2014-10-03 23:04
PR that should fix this. https://github.com/ansible/ansible-modules-core/pull/49

**Comment by bcoca** [comment] 2015-02-11 19:16
so I cannot reproduce this in current development before patching

```
- hosts: localhost
  sudo: True
  gather_facts: false
  tasks:
    - mount: name=/mnt/test src=/tmp fstype=none opts=bind,rw state=mounted
```

mounts it only once and creates a single entry in /etc/fstab

**Comment by Jmainguy** [comment] 2015-02-11 19:53
It depends on the target, centos7 doesn't seem to be affected by this bug. Debian 7 does.

Target ns1.example.com

```
# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"


[root@phy01 ~]# ansible -i hosts all -m mount -a "name=/mnt/test src=/tmp opts=rw,bind state=mounted fstype=none"                                                                             
ns1.example.com | success >> {
    "changed": true,
    "fstab": "/etc/fstab",
    "fstype": "none",
    "name": "/mnt/test",
    "opts": "rw,bind",
    "src": "/tmp"
}

[root@phy01 ~]# ansible -i hosts all -m mount -a "name=/mnt/test src=/tmp opts=rw,bind state=mounted fstype=none"
ns1.example.com | success >> {
    "changed": true,
    "fstab": "/etc/fstab",
    "fstype": "none",
    "name": "/mnt/test",
    "opts": "rw,bind",
    "src": "/tmp"
}

[root@phy01 ~]# ansible -i hosts all -m mount -a "name=/mnt/test src=/tmp opts=rw,bind state=mounted fstype=none"
ns1.example.com | success >> {
    "changed": true,
    "fstab": "/etc/fstab",
    "fstype": "none",
    "name": "/mnt/test",
    "opts": "rw,bind",
    "src": "/tmp"
}

[root@phy01 ~]# ansible -i hosts all -m mount -a "name=/mnt/test src=/tmp opts=rw,bind state=mounted fstype=none"
ns1.example.com | success >> {
    "changed": true,
    "fstab": "/etc/fstab",
    "fstype": "none",
    "name": "/mnt/test",
    "opts": "rw,bind",
    "src": "/tmp"
}



ns1:~# mount -l
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=14299,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=12460k,mode=755)
/dev/disk/by-uuid/641c7238-38ef-4a20-8775-96d66411bdb7 on / type ext3 (rw,relatime,errors=remount-ro,barrier=1,data=ordered)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /run/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=73440k)
rpc_pipefs on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
/dev/disk/by-uuid/641c7238-38ef-4a20-8775-96d66411bdb7 on /mnt/test type ext3 (rw,relatime,errors=remount-ro,barrier=1,data=ordered)
/dev/disk/by-uuid/641c7238-38ef-4a20-8775-96d66411bdb7 on /mnt/test type ext3 (rw,relatime,errors=remount-ro,barrier=1,data=ordered)
/dev/disk/by-uuid/641c7238-38ef-4a20-8775-96d66411bdb7 on /mnt/test type ext3 (rw,relatime,errors=remount-ro,barrier=1,data=ordered)
/dev/disk/by-uuid/641c7238-38ef-4a20-8775-96d66411bdb7 on /mnt/test type ext3 (rw,relatime,errors=remount-ro,barrier=1,data=ordered)
```

**Comment by bcoca** [comment] 2015-02-11 19:59
closing by merging PR #49

**Closed as completed by bcoca** 2015-02-11 19:59 UTC
Labels: bug_report
