### ISSUE TITLE
git module recursive option does not work as expected

### ISSUE THREAD

**Issue by josef-spak** [ansible/ansible-modules-core#169] opened 2014-10-10 11:13 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel e91e30cd5e) last updated 2014/10/09 14:13:05 (GMT +200)
  lib/ansible/modules/core: (devel cb69744bce) last updated 2014/10/07 14:15:55 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/07 14:16:13 (GMT +200)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/07 14:16:48 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/07 14:17:21 (GMT +200)
##### Environment:

From: Linux Mint 17
Managing: Ubuntu Trusty 14.04
##### Summary:

The documentation says:

> if `no`, repository will be cloned without the --recursive option, skipping sub-modules. (added in Ansible 1.6)

But the module behaves differently:
- with `recursive=no`, submodule update is not skipped for already initialized submodules.
- with `recursive=yes`, submodule update is done same as with `=no` but additional submodules are not initialized.
- value of the `recursive` parameter does not matter at all after the initial clone. 
- if your repo adds more submodules, you have to run `git submodule init --update` manually to add them. Another quirk is that `git submodule init` has to be combined with a revision change in the superproject to make the ansible module update submodules, and is not enough on its own.

If any of this is not a bug then it should be documented.
##### Steps To Reproduce:
1. Clone a repository with submodules on remote host (e.g. use git module with recursive=yes or run `git clone ...; git submodule update --init`)
2. Make a commit that only updates submodule ref
3. Run the git module with `recursive=no`
4. The submodule will be updated anyway.
5. Add another submodule into your project, commit and push.
6. Run git module with `recursive=yes`
7. The additional submodule will not be cloned to the managed host.
##### Expected Results:
1. With `recursive=no`, module should clone/pull/checkout superproject but skip submodules. Output of `git submodule status` should not change. Using recursive=no on a project with submodules it should be possible to leave local modifications if moving between commits that change submodule references. This is OK and should fail with force=no because the project was left in an inconsistent state.
2. With `recursive=yes`, ansible module should be able to clone additional submodules.
##### Actual Results:
1. Ansible module does not skip submodule update with recursive=no. `git submodule status` reports a change and there are no local modifications as reported by `git status`
2. `recursive=yes` does not clone additional submodules after the initial clone.

**Comment by mtotheikle** [comment] 2014-10-13 19:04
I'm experiencing similar problems and I think the issue is coming from using the --remote option in the git submodule update command. This option will update the submodule based on origin and not use the superproject’s recorded SHA-1

In my case a fresh git clone with the recursive option set to true clones the correct submodule version but then when the submodule update command is ran then the wrong version of the submodule is cloned.

**Comment by mpdehaan** [comment] 2014-10-13 23:42
This seems like this should possibly be a different ticket, and does not deal with "idempotence".   

Rather, git submodule updates should be skipped with recursive=no, that just seems to be a flat bug that they are not skipped.

Also git submodules should be recloned for recursive=yes

Idempotence says F(x) = F(F(x)) and both of these just seem to be generally classified bugs to me, if as stated.

We will investigate.

**Comment by josef-spak** [comment] 2014-10-14 06:56
You're right that idempotence is OK, thanks! I was rewriting the bug report a couple of times and that got left in there. Edited it out of the description now.

**Comment by josef-spak** [comment] 2014-10-14 07:00
@mtotheikle there's a PR that is supposed to fix that https://github.com/ansible/ansible-modules-core/pull/55 (I think it still needs some work and am rushing to get to it). But yes it does fall into the 'not working as expected' category.

**Comment by abadger** [comment] 2014-10-28 22:03
@josef-spak I think that I've fixed this now.  If you could test that would be great.  Also, if you care to look over the new integration tests I added: https://github.com/ansible/ansible/commit/82e8d677d9a77c49f1a31c46056fb542a2fb507d  and let me know if there's any additional tests that need to be done, that you'd like to see that would be great too.

I'll close this ticket in a few days after you or I have had a chance to test this on some real-life repositories :-)

**Comment by abadger** [comment] 2014-11-03 17:25
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed** 2014-11-03 18:43 UTC
Labels: P1, bug_report, needs_info
