### ISSUE TITLE
"Copy" and "Template" modules might be broken by .bashrc file

### ISSUE THREAD

**Issue by wodzik** [ansible/ansible-modules-core#1228] opened 2015-04-29 18:13 UTC
When I run playbook which contain "copy" or "template" action I get this error
http://pasteboard.co/5Mu3yJW.png
My .bashrc file looks as follows:
http://pastebin.com/g0vJqM3h
When I remove lines 91-103 it works fine

**Comment by blackreed9** [comment] 2015-04-30 12:30
Try changing line 99 so it doesn't have the '{%s}'   {% is the beginning of a Jinja tag

**Comment by bcoca** [comment] 2015-04-30 12:38
line 99 would explian the message about the tag 's', not sure how the prompt made it into the template string though.

note, had to add my own:

```
 __git_ps1() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
```

to make the shell not error every time (i'm guessing this or similar was the intent)

**Comment by bcoca** [comment] 2015-04-30 12:40
also, i cannot seem to reproduce on my gentoo nor ubuntu box

**Comment by wodzik** [comment] 2015-04-30 13:17
I run this palybook on ubuntu 15.04 on localhost with ansible_connection set to local and with parameter -K. 
Ansible version 1.9.1

Playbook code:

---
- name: Vhost create
  hosts: target
  sudo: yes
  - template: src=../templates/vhost.j2 dest="/etc/apache2/sites-available/{{ site_name }}.conf"

**Comment by blackreed9** [comment] 2015-04-30 17:01
I've been unable to reproduce this with _copy_ or _template_ 
My  configuration is CentOS 6.3 system running Ansible 1.9.1

I've tried this with and without bcoca's __git_psa() function

**Comment by jctanner** [comment] 2016-05-03 19:20
Testcase ...

```
$ cat test.sh 
#!/bin/bash

VERSION=$(ansible --version | head -n1 | awk '{print $2}')

if [[ $VERSION < 1.7 ]]; then
    exit 99
fi    

ansible-playbook -vvvv -i inventory site.yml
RC=$?
exit $RC


$ cat inventory 
el6box ansible_ssh_host=10.0.0.106 ansible_ssh_user=bashrctester ansible_sudo_pass=redhat

$ cat site.yml 
- hosts: el6box
  gather_facts: False
  tasks:
    - template: src=tmpl.j2 dest=/tmp/test.txt
- hosts: el6box
  gather_facts: False
  sudo: yes
  tasks:
    - template: src=tmpl.j2 dest=/tmp/test_sudo.txt
```

The example bashrc was set for the bashrctester user on the remote host.

**Comment by jctanner** [comment] 2016-05-03 19:30
Test results ...

| version | rc |
| --- | --- |
| v1.7.0 | 0 |
| v1.7.1 | 0 |
| v1.7.2 | 0 |
| v1.8.0 | 0 |
| v1.8.1 | 0 |
| v1.8.2 | 0 |
| v1.8.3 | 0 |
| v1.8.4 | 0 |
| v1.9.0-0.1.rc1 | 3 |
| v1.9.0-0.2.rc2 | 0 |
| v1.9.0-1 | 0 |
| v1.9.0-2 | 0 |
| v1.9.0.1-1 | 0 |
| v1.9.1-0.1.rc1 | 0 |
| v1.9.1-0.2.rc2 | 0 |
| v1.9.1-0.3.rc3 | 0 |
| v1.9.1-0.4.rc4 | 0 |
| v1.9.1-1 | 0 |
| v1.9.2-0.1.rc1 | 0 |
| v1.9.2-0.2.rc2 | 0 |
| v1.9.2-1 | 0 |
| v1.9.3-0.1.rc1 | 0 |
| v1.9.3-0.2.rc2 | 0 |
| v1.9.3-0.3.rc3 | 0 |
| v1.9.3-1 | 0 |
| v1.9.4-0.1.rc1 | 0 |
| v1.9.4-0.2.rc2 | 0 |
| v1.9.4-0.3.rc3 | 0 |
| v1.9.4-1 | 0 |
| v1.9.5-0.1.rc1 | 0 |
| v1.9.5-1 | 0 |
| v1.9.6-0.1.rc1 | 0 |
| v1.9.6-1 | 0 |
| v2.0.0-0.6.rc1 | 0 |
| v2.0.0-0.7.rc2 | 0 |
| v2.0.0-0.8.rc3 | 0 |
| v2.0.0-0.9.rc4 | 0 |
| v2.0.0.0-1 | 0 |
| v2.0.0.1-1 | 0 |
| v2.0.0.2-1 | 0 |
| v2.0.1.0-0.1.rc1 | 0 |
| v2.0.1.0-0.2.rc2 | 0 |
| v2.0.1.0-1 | 0 |
| v2.0.2.0-0.1.rc1 | 0 |
| v2.0.2.0-0.2.rc2 | 0 |
| v2.0.2.0-0.3.rc3 | 0 |
| v2.0.2.0-0.4.rc4 | 0 |
| v2.0.2.0-1 | 0 |
| v2.1.0.0-0.1.rc1 | 0 |

**Comment by jctanner** [comment] 2016-05-03 20:03
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

Our reasons and evidence for this are:
- Myself and others were unable to repduce your issue with the data provided.
- The test results above indicate no regression of the behavior in any known ansbile versions.

And we suggest that:
- If this is still a problem in your environment, file a new bug with complete ansbile cli examples, full -vvvv output, sudo -l output for the remote user and any possible data that might be relevant.
- If it is unclear what data you should provide that was not already given, please seek advice in either the mailing list or on irc.

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by jctanner** 2016-05-03 20:03 UTC
Labels: P2, bug_report
