### ISSUE TITLE
docker module not showing console output of command executed in container even with detach=false and tty

### ISSUE THREAD

**Issue by nhanda03** [ansible/ansible-modules-core#2915] opened 2016-01-29 12:41 UTC
Expectation: when container is run via ansible it should start the container and wait for it to finish giving back the console output before executing the next task.

Ansible version : 2.0.0

Approach 1:
This returns me ansible facts and not the console output of my test execution in container.

```
- name: Run docker container
  docker: 
    image: image-test:latest
    name: unit-test
    volumes: /roo/results:/x/report
    tty: yes
    detach: False
    privileged: yes
    state: started
```

Approach 2
If I run the same container from command line I see the console output before exiting

```
[user]$ sudo docker run --name unit-test -t --rm --privileged=true -v /roo/results:/x/report image-test:latest
Buildfile: /Toothless_API_Automation/build.xml

test:

test:
   [testng] [TestNG] Running:
   [testng]   /x/Suite.xml
   [testng]
   [testng] {"id":1,"name":"api2","userId":1,"email":"api2@xx.com"}
   [testng] 1 * Client out-bound request
   [testng] 1 > POST http://xxx:3456/xxx
   [testng] 1 > Content-Type: application/json
   [testng] 1 > Accept: application/json
   [testng] {"id":1,"name":"api2","userId":1,"email":"api2@xxx.com"}
   [testng]
   [testng] ===============================================
   [testng] xSuite
   [testng] Total tests run: 1, Failures: 1, Skips: 0
   [testng] ===============================================
   [testng]
   [testng] The tests failed.

BUILD SUCCESSFUL
Total time: 4 seconds
```

Do I need to do something different while using approach 1 via ansible docker module to achieve the expected as what I'm getting with approach two.

**Comment by bcoca** [comment] 2016-01-29 14:34
I don't see anywhere how the module will return stdout from a command, it returns a custom summary message. Also note that most commands are using the API and not the command line utilities, these do not seem to return the same output.

Closing this as it is not a bug, just a mismatched expectation.

**Closed as completed by bcoca** 2016-01-29 14:34 UTC
