### ISSUE TITLE
fetch (core module) can not deal with file name with space

### ISSUE THREAD

**Issue by xifanyan** [ansible/ansible-modules-core#48] opened 2014-09-29 23:57 UTC
I just found fetch does not work very well with filenames has spaces in them. so I wrote a test script.
###### 

name: report | fetch auditusage report from server  
fetch: src="{{ item }}"  
          dest=/tmp/fetched  
 with_items:  
         - /tmp/test test.txt 
###### ################################################################

basically "test.txt" works,   "test test.txt" does not.

and here is the error message, looks like it just failed to create the file in local folder, therefore md5sum mismatched. (the whole folder structure on remote server was created locally)
###### 

failed: [***_.**__.com] => (item=/tmp/test test.txt) => {"dest": "/tmp/fetched/_**_.**_*.com/tmp/test test.txt", "failed": true, "file": "/tmp/test test.txt", "item": "/tmp/test test.txt", "md5sum": null, "remote_md5sum": "6fa871334b2e8715ef897730f8460553"}
msg: md5 mismatch
###### 

~  
~

**Comment by Jmainguy** [comment] 2014-10-29 13:07
Linux allows you to have spaces in your file names, but it requires you to address them by escaping the space. Like so

/tmp/test\ test.txt

Ansible follows these rules and the following worked

```
ansible -i hosts centos6.soh.re -m fetch -a "src='/tmp/test\ test.txt' dest=/tmp/fetched"
centos6.soh.re | success >> {
    "changed": false, 
    "dest": "/tmp/fetched/centos6.soh.re/tmp/test test.txt", 
    "file": "/tmp/test test.txt", 
    "md5sum": "d41d8cd98f00b204e9800998ecf8427e"
}
```

notice I escaped the space \, I also single qouted it, otherwise Ansible would get confused by the random . So in short, this is not a bug, and remember to qoute and escape if using spaces.

**Comment by bcoca** [comment] 2015-02-11 19:05
closing this as @Jmainguy notes this is just a quoting/escaping issue.

**Closed as completed by bcoca** 2015-02-11 19:05 UTC
Labels: bug_report
