### ISSUE TITLE
Add strip-component option in unarchive module

### ISSUE THREAD

**Issue by BarthV** [ansible/ansible-modules-core#2480] opened 2015-11-17 12:38 UTC
Please add  a `strip-component` or `strip-level` option in `unarchive` module ! :)

Thanks

**Comment by robynbergeron** [comment] 2015-11-25 16:58
[module: files/unarchive.py]

**Comment by robynbergeron** [comment] 2015-11-25 16:58
@BarthV Thanks for submitting this feature idea.

@pileofrogs Pinging you to bring this feature request to your attention. Please note that you are under no particular obligation to add this feature.

We encourage all Ansible community members to submit pull requests to satisfy feature requests. Consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.

**Comment by pileofrogs** [comment] 2015-11-25 18:51
I'll look into it.

**Comment by BarthV** [comment] 2015-11-26 08:56
@robynbergeron : this might be related -> https://github.com/ansible/ansible-modules-core/pull/2491

**Comment by dagwieers** [comment] 2016-05-27 14:37
@bcoca We can close this issue now. This is possible since #3307 is merged.

However, a pure-python implementation would allow us to implement this for more than just tar-based archives.

**Comment by erikdw** [comment] 2016-07-05 22:33
It seems that this isn't actually fixed with the addition of `extra_opts` to the `unarchive` module in #3307.  

Specifically, when setting `extra_opts="--strip-components=1"` I see the unarchive module complaining about the dir not existing:

```
# ansible incantation
unarchive: src=original-archive-name.tgz dest=/path/to/unarchived/bits/ extra_opts="--strip-components=1"


# ansible error
FAILED! => {
"changed": false, 
"failed": true, 
"msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/path/to/unarchived/bits/original-archive-name'"
}
```

That implies to me that the unarchive module does some validation that the file was "exploded" correctly, but this validation is preventing the removal of that base component of the archive's directory structure.

**Comment by dagwieers** [comment] 2016-07-05 22:37
Sigh, yes, someone broke the `extra_opts` option when implementing pure-python file-list retrieval for the gtar implementation. It's been explained a few times in the issues, yet people seem to report this over and over again. Search for `unarchive` to get the full scope.

**Comment by dagwieers** [comment] 2016-07-05 22:40
A recent change (#3575) has broken the `exclude:` and `extra_opts:` functionality by implementing a pure-python `files_in_archive` implementation which is incompatible with gtar's pattern matching. @abadger Can we pretty please undo this broken PR #3575 ? See: https://github.com/ansible/ansible-modules-core/pull/3575#issuecomment-222116332

**Comment by erikdw** [comment] 2016-07-05 23:00
@dagwieers : thanks for the quick reply!

**Comment by erikdw** [comment] 2016-07-05 23:02
@dagwieers : and sorry to be a pest, but from spending some time reading about the issue, it's not clear to me that reverting PR #3575 would fix the specific issue I pointed out; i.e., in my issue the `extra_opts="strip-components=1"` _does_ work in terms of removing the base component from the resultant exploded path. But then there is a validation step that is preventing the unarchive module from declaring success.

FYI, here's my ansible version:

```
% ansible --version                                                                                                                                                                                                                                
ansible 2.1.0.0
```

**Comment by dagwieers** [comment] 2016-07-05 23:15
@erikdw The validation step (which is actually a step to set the right permissions/ownership if needed) is based on the pure-python `files_in_archive` implementation that does not take into account any `extra_opts` or `exclude` settings. So yes, to be expected...

**Comment by erikdw** [comment] 2016-07-05 23:20
@dagwieers : ok, great, thanks for assuaging my concern.

**Comment by dagwieers** [comment] 2016-07-06 21:44
Fix #3767 is merged, can you please retest ?

**Comment by abadger** [comment] 2016-07-06 22:34
#3767 has been merged wihich should revert #3575.  the commits are in devel and cherry-picked to stable-2.1.  I'm going to close this as it should be fixed in the next release.

**Closed as completed by abadger** 2016-07-06 22:34 UTC
Labels: feature_idea

**Comment by erikdw** [comment] 2016-07-06 22:48
@abadger  & @dagwieers : I just tested the unarchive with strip-components being 1, using the devel branch, and observed the [same behavior I reported above](https://github.com/ansible/ansible-modules-core/issues/2480#issuecomment-230622276).

Though I'm not 100% sure if I've got everything set up right (honestly, the complication of git submodules are not helpful in this regard).   Here's what I did:

```
% git remote -v
origin  github.com:ansible/ansible (fetch)
origin  github.com:erikdw/ansible (push)
% git checkout devel
% git fetch origin
% git merge origin/devel
% git pull --recurse-submodules && git submodule update --recursive 
% source hacking/env-setup
# then run my ansible cmd that is still issuing the same error;  I can craft a shareable version of it if reproduction is not obvious and then attach the file here.
```

**Comment by dagwieers** [comment] 2016-07-07 09:08
@erikdw In my tests it does not seem to work, and this is the reason why:

The gtar command in `-t` (list) mode using `--strip-components=1` does not return the files with stripped paths, it returns the content of the archive. So this option (and every other option that has no effect on `-t` mode) will not work. Not sure if this is a bug in gtar, or just an anti-feature.

**Comment by dagwieers** [comment] 2016-07-07 09:19
FWIW The `--exclude` option does work in `-t` (list) mode. So it is unclear to me how the developers envisioned this to work.

**Comment by dagwieers** [comment] 2016-07-07 09:23
The plot thickens, there is an option `--show-transformed-names` which does show the filenames after transformations, and now it does work. A pull-request has been made.

FYI There is still a bug related it reporting a change every time. Still have to look into that one. Feel free to debug this yourself though ;-)

**Comment by dagwieers** [comment] 2016-07-07 13:10
Debugging this issue, I see the following:

```
[dag@moria ansible.testing]$ /bin/gtar -d -C "/tmp" --show-stored-names --strip-components=1 --mode="0644" -f files/test101.tar 
/bin/gtar: : Warning: Cannot stat: No such file or directory
é.txt: Mode differs
[dag@moria ansible.testing]$ /bin/gtar -t -C "/tmp" --show-stored-names --strip-components=1 --mode="0644" -f files/test101.tar 

é.txt
[dag@moria ansible.testing]$ ls -la /tmp/é.txt 
-rw-r--r--. 1 dag dag 0 May 27 14:51 /tmp/é.txt
```

So the warning is related to the fact that with `--strip-components=1` there is an empty entry and the implementation does an lstat("") for this entry which causes a _No such file or directory_ (seems to me like a bug in the implementation).

The reason why we do get a change is because it reports that the _Mode differs_ which is not correct, the file on disk and the requested mode are identical. So it appears that gtar in `-d` (diff/compare) mode does not correctly take into account the `--mode` option. Again, whether this was intentional or neglect is hard to see. And it is unclear how the developers envisioned diff/compare-mode to work correctly.

PS Even in symbolic mode, it fails to work as expected:

```
[dag@moria ansible.testing]$ /bin/gtar -d -C "/tmp" --show-stored-names --strip-components=1 --mode=u=rw,go=r -f files/test101.tar 
/bin/gtar: : Warning: Cannot stat: No such file or directory
é.txt: Mode differs
```

**Comment by dagwieers** [comment] 2016-07-07 13:32
Alright, hopefully the last update here. The real problem was related to the incorrect **No such file or directory** error message for empty filenames. Once I have filtered that one out, it appears to work correctly. I updated the PR, please test and report back (in the PR itself).

**Comment by erikdw** [comment] 2016-07-08 02:05
@dagwieers : I would like to test, but these git submodules are beyond my current abilities.  i.e., if I just wanted to use your branch I'm not sure *how* to do that in the git submodule -- I know how to it with regular git repos.

**Comment by erikdw** [comment] 2016-07-08 02:13
I tried hand-copying your `unarchive.py` file from #4131, but then after I ran `source hacking/env-setup` and then tried my playbook I got this error:

```
ansible/lib/ansible/cli/__init__.py", line 27, in <module>
    import yaml
ImportError: No module named yaml
```

Notably, I don't get that error when I *don't* have your `unarchive.py` hand-copied into my repo.

**Comment by mnieber** [comment] 2016-10-29 09:49
I could figure it out with the help of the above comments, but it still took me some time, so here's an example (note that it requires ansible version 2.1 or higher):

```
- name: ModSecurity | Install OWASP Core Rule Set
  unarchive:
    extra_opts: ['--strip-components=1', '--show-stored-names']
    src: https://github.com/SpiderLabs/owasp-modsecurity-crs/tarball/2.2.9
    remote_src: yes
    copy: no
    dest: /etc/modsecurity
```

**Comment by sirkjohannsen** [comment] 2016-11-03 13:44
Seems like it's broken again in 2.2

**Comment by michal-jewel** [comment] 2017-02-14 09:53
Indeed I have come upon the very issue broken in 2.2.

**Comment by CafeLungo** [comment] 2017-05-11 19:25
This appears to be fixed in 2.3.0.0 (and I found this page useful for figuring out how to strip the first dir level. Thanks!)

**Comment by dagwieers** [comment] 2017-05-14 18:01
To ensure this does not fail to work in a future release due to regression, we really ought to add integration tests for this.

**Comment by camilosantana** [comment] 2017-05-18 01:03
this module is still bugging out. this is failing for me on ansible-2.4.0
installed via `pip install git+git://github.com/ansible/ansible.git@devel`

```
- name: download amazon-provided monitoring script archive
  get_url:
    url: https://s3.amazonaws.com/testable-scripts/AwsScriptsMon-0.0.1.zip
    dest: /tmp
  register: aws_scripts_monitoring
- name: unzip amazon-provided monitoring script archive
  unarchive:
    src: "{{ aws_scripts_monitoring.dest }}"
    dest: /usr/local/sbin
    extra_opts: ["-j"]
    remote_src: true
```
target host is
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
`-j` option above is from the version of `unzip` installed on the machine that the module seems to call.
>   -j  junk paths (do not make directories)

unzip version = `UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.`

debug output is [here](https://pastebin.com/SDEKHrY9)
