### ISSUE TITLE
RDS Promote of Read-Replica reports OK but does not promote the read-replica instance

### ISSUE THREAD

**Issue by rsouthgate** [ansible/ansible-modules-core#2150] opened 2015-09-24 23:31 UTC
Using the promote method on an RDS read-replica instance (created through Ansible RDS module) the read-replica remains as a read-replica but the script doesn't error.

**Comment by m-barthelemy** [comment] 2015-10-12 19:46
Confirmed, same problem here.
Using ansible 2.0 from master, boto 2.38.0.
Here's the output from the promote task:

```
ok: [localhost -> localhost] => {"changed": false, "instance": {"availability_zone": "us-east-1b", "backup_retention": 1, "create_time": 1444661643.915, "endpoint": "ansiblebug-test-slave.crm4srpb4nqa.us-east-1.rds.amazonaws.com", "id": "ansiblebug-test-slave", "instance_type": "db.r3.xlarge", "iops": null, "maintenance_window": "thu:03:02-thu:03:32", "multi_zone": false, "port": 3306, "replication_source": "arn:aws:rds:eu-west-1:922794570060:db:ansiblebug-test-master", "status": "available", "username": "admin", "vpc_security_groups": "sg-xxxxxx"}}
```

**Comment by maxrothman** [comment] 2015-11-24 19:08
This is probably due to the conditions being reversed [here](https://github.com/ansible/ansible-modules-core/blob/devel/cloud/amazon/rds.py#L832). The bug was introduced by [this refactor](https://github.com/ansible/ansible-modules-core/commit/7a8586c53c9482d54db037a521a4a20ed7369daf) @willthames.

**Comment by maxrothman** [comment] 2015-11-24 19:29
https://github.com/ansible/ansible-modules-core/pull/2542 has been opened to fix this issue.

**Comment by maxrothman** [comment] 2015-11-30 16:00
Since #2542 has been merged, this should be closed.

**Comment by bcoca** [comment] 2015-11-30 20:43
closing as per above merged fix

**Closed as completed by bcoca** 2015-11-30 20:43 UTC
Labels: bug_report, cloud
