### ISSUE TITLE
Docker module `mem_limit has been moved to host_config in API version 1.19`

### ISSUE THREAD

**Issue by kevzettler** [ansible/ansible-modules-core#1812] opened 2015-07-27 04:36 UTC
```
<192.168.33.10> REMOTE_MODULE docker name=web_postgres image=postgres pull=missing
failed: [192.168.33.10] => {"failed": true, "parsed": false}
BECOME-SUCCESS-uorgtgbdrcjyhsxdmfugycjbdkmvvrft
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1437969642.35-37796871425333/docker", line 3132, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1437969642.35-37796871425333/docker", line 1494, in main
    started(manager, containers, count, name)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1437969642.35-37796871425333/docker", line 1354, in started
    created = manager.create_containers(delta)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1437969642.35-37796871425333/docker", line 1227, in create_containers
    containers = do_create(count, params)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1437969642.35-37796871425333/docker", line 1217, in do_create
    result = self.client.create_container(**params)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 243, in create_container
    volume_driver
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 552, in create_container_config
    'mem_limit has been moved to host_config in API version 1.19'
docker.errors.InvalidVersion: mem_limit has been moved to host_config in API version 1.19
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/kevzettler/.ssh/config
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 192.168.33.10 closed.
```

**Comment by bcoca** [comment] 2015-07-27 22:23
closing as dupe of #1602

**Closed as completed by bcoca** 2015-07-27 22:23 UTC
Labels: bug_report
