### ISSUE TITLE
syncronize not working with hosts behind jumpbox

### ISSUE THREAD

**Issue by one1zero1one** [ansible/ansible-modules-core#3415] opened 2016-04-12 22:08 UTC
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

syncronize
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel cb7b3b489d) last updated 2016/03/30 15:14:21 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 0268864211) last updated 2016/03/30 15:14:39 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 6978984244) last updated 2016/03/30 15:14:39 (GMT +200)
```
##### CONFIGURATION

```
[defaults]
scp_if_ssh = True
[ssh_connection]
ssh_args = -o ControlMaster=no -o ControlPath=none -o ControlPersist=no

```
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

syncronize does not work with host behind a jumpbox (ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q jumphost"')
##### ACTUAL RESULTS

atal: [pg-p2-s-esdata01]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh '/usr/bin/ssh  -S none -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"/files/\" \"user@host:/path\"", "failed": true, "msg": "ssh: Could not resolve hostname host: Name or service not known\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]\n", "rc": 12}

**Comment by sivel** [comment] 2016-04-12 23:04
Duplicate of https://github.com/ansible/ansible-modules-core/issues/3370

There is an open pull request to address this at https://github.com/ansible/ansible/pull/15306

Additional note:  This does require the use of `use_ssh_args=True` on your synchronize task.  This currently works, but only looks at the configured `ssh_args`.

**Closed as completed by sivel** 2016-04-12 23:04 UTC
