### ISSUE TITLE
Group managment bug in FreeBSD (old #9513)

### ISSUE THREAD

**Issue by masterserg00** [ansible/ansible-modules-core#613] opened 2015-01-08 09:01 UTC
##### Issue Type
- Bug Report
##### Ansible Version

ansible 1.7.2
##### CONFIGURATION

Python 2.7.8
##### OS / ENVIRONMENT

--server
FreeBSD 9.3-RELEASE FreeBSD 9.3-RELEASE #0 r268512: Thu Jul 10 23:44:39 UTC 2014 root@snap.freebsd.org:/usr/obj/usr/src/sys/GENERIC amd64

--target_client
FreeBSD 10.0-RELEASE FreeBSD 10.0-RELEASE #0 r260789: Thu Jan 16 22:34:59 UTC 2014 root@snap.freebsd.org:/usr/obj/usr/src/sys/GENERIC amd64
Summary:
##### SUMMARY

I try to change groups for user "test1" in FreeBSD host.
If I am adding a new groups to user (using module "user")- all is working fine , but when I try to "delete" some group for user "test1", I see status " : ok=2 changed=1 ", but realy nothing happens. And every time I see such status.
In Linux host all i working fine.
Please fix it.

--- First time (all is fine) ---

```
hosts: my_servers remote_user: root tasks:
    name: Create FreeBSD users 
    user: 
      name={{ item.name }} 
      password={{ item.password }} 
      groups={{ item.groups }} 
      comment={{ item.comment }} 
      append=no 
   with_items: 
     - { name: 'test1' , groups: 'mysql\,cyrus', password: '11111', comment: 'Vasja' } 
     - { name: 'test2' , groups: 'mysql', password: '22222', comment: 'Kolja' } 
   when: ansible_os_family == "FreeBSD"
```

--- Second time (bug) ----

```
hosts: my_servers remote_user: root tasks:
    name: Create FreeBSD users user: name={{ item.name }} password={{ item.password }} groups={{ item.groups }} comment={{ item.comment }} append=no with_items: - { name: 'test1' , groups: 'mysql', password: '11111', comment: 'Vasja' } - { name: 'test2' , groups: 'mysql', password: '22222', comment: 'Kolja' } when: ansible_os_family == "FreeBSD"
```

```
root@kris:/home/serg/ansible # ansible-playbook -vvvv run.yml

PLAY [my_servers] *************************************************************

GATHERING FACTS ***************************************************************
ESTABLISH CONNECTION FOR USER: root
REMOTE_MODULE setup
EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '172.29.251.106', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1415297453.89-59397932578099 && echo $HOME/.ansible/tmp/ansible-tmp-1415297453.89-59397932578099'"]
PUT /tmp/tmpyPFA5r TO /root/.ansible/tmp/ansible-tmp-1415297453.89-59397932578099/setup
EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '172.29.251.106', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/local/bin/python /root/.ansible/tmp/ansible-tmp-1415297453.89-59397932578099/setup; rm -rf /root/.ansible/tmp/ansible-tmp-1415297453.89-59397932578099/ >/dev/null 2>&1'"]
ok: [freebsd]

TASK: [Create FreeBSD users] **************************************************
ESTABLISH CONNECTION FOR USER: root
REMOTE_MODULE user name=test1 password=VALUE_HIDDEN groups=mysql comment=Vasja append=no
EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '172.29.251.106', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1415297454.25-201202690342400 && echo $HOME/.ansible/tmp/ansible-tmp-1415297454.25-201202690342400'"]
PUT /tmp/tmpDSK0ET TO /root/.ansible/tmp/ansible-tmp-1415297454.25-201202690342400/user
EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '172.29.251.106', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/local/bin/python /root/.ansible/tmp/ansible-tmp-1415297454.25-201202690342400/user; rm -rf /root/.ansible/tmp/ansible-tmp-1415297454.25-201202690342400/ >/dev/null 2>&1'"]
changed: [freebsd] => (item={'comment': 'Vasja', 'password': '11111', 'name': 'test1', 'groups': 'mysql'}) => {"append": false, "changed": true, "comment": "Vasja", "group": 1002, "groups": "mysql", "home": "/home/test1", "item": {"comment": "Vasja", "groups": "mysql", "name": "test1", "password": "11111"}, "move_home": false, "name": "test1", "password": "NOT_LOGGING_PASSWORD", "shell": "/bin/sh", "state": "present", "uid": 1002}
ESTABLISH CONNECTION FOR USER: root
REMOTE_MODULE user name=test2 password=VALUE_HIDDEN groups=mysql comment=Kolja append=no
EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '172.29.251.106', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1415297454.45-101295486595285 && echo $HOME/.ansible/tmp/ansible-tmp-1415297454.45-101295486595285'"]
PUT /tmp/tmpSb6Sfc TO /root/.ansible/tmp/ansible-tmp-1415297454.45-101295486595285/user
EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '172.29.251.106', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/local/bin/python /root/.ansible/tmp/ansible-tmp-1415297454.45-101295486595285/user; rm -rf /root/.ansible/tmp/ansible-tmp-1415297454.45-101295486595285/ >/dev/null 2>&1'"]
+ok: [freebsd] => (item={'comment': 'Kolja', 'password': '22222', 'name': 'test2', 'groups': 'mysql'}) => {"append": false, "changed": false, "comment": "Kolja", "group": 1003, "groups": "mysql", "home": "/home/test2", "item": {"comment": "Kolja", "groups": "mysql", "name": "test2", "password": "22222"}, "move_home": false, "name": "test2", "password": "NOT_LOGGING_PASSWORD", "shell": "/bin/sh", "state": "present", "uid": 1003}

+PLAY RECAP ********************************************************************
freebsd : ok=2 changed=1 unreachable=0 failed=0
```
##### STEPS TO REPRODUCE

Just run my playbook
ansible-playbook run.yml
##### EXPECTED RESULTS

Change user group for user "test1" from groups=1002(test1),88(mysql),60(cyrus) to groups=1002(test1),88(mysql)
##### ACTUAL RESULTS

Still all old groups for user "test1"

uid=1002(test1) gid=1002(test1) groups=1002(test1),88(mysql),60(cyrus)

**Comment by jctanner** [comment] 2016-05-02 16:01
Test case ...

```
$ cat site.yml 
- hosts: freebsdbox
  #gather_facts: False
  tasks:
    #- shell: whoami
    - name: create the required groups
      group:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql
        - cyrus

    - name: Create FreeBSD users 
      user: 
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        groups: "{{ item.groups }}"
        comment: "{{ item.comment }}"
        append: no 
      with_items: 
        - { name: 'test1' , groups: 'mysql,cyrus', password: '11111', comment: 'Vasja' } 
        - { name: 'test2' , groups: 'mysql', password: '22222', comment: 'Kolja' } 
      when: ansible_os_family == "FreeBSD"

$ cat inventory 
freebsdbox ansible_ssh_host=10.0.0.120 ansible_ssh_user=root ansible_python_interpreter=/usr/local/bin/python2.7

$ cat test.sh 
#!/bin/bash
rm -f results.log
ansible-playbook -i inventory -vvvv site.yml | tee -a results.log
RC=$?
if [[ $RC != 0 ]]; then
    exit 99
fi

# Find the changed count ...

CHANGED=$(cat results.log | egrep ^freebsdbox | tail -n1 | awk '{print $4}' | cut -d\= -f2)
if [[ $CHANGED == 0 ]]; then
    exit $CHANGED
else
    exit $CHANGED
fi
```

Environment:
- centos7 controlhost
- freebsd 9.3 vagrant box 
  hnakamur/freebsd-9.3-amd64
  pkg add python

**Comment by jctanner** [comment] 2016-05-02 16:04
| Version | RC |
| --- | --- |
| 0.0.1 | 1 |
| 0.0.2 | 1 |
| 0.01 | 1 |
| 0.3 | 1 |
| 0.3.1 | 1 |
| 0.4 | 1 |
| 0.4.1 | 1 |
| 0.5 | 1 |
| 0.6 | 1 |
| 0.7 | 1 |
| 0.7.1 | 1 |
| 0.7.2 | 1 |
| 0.8 | 1 |
| v0.9 | 1 |
| v1.0 | 1 |
| v1.1 | 1 |
| v1.2 | 0 |
| v1.2.1 | 0 |
| v1.2.2 | 0 |
| v1.2.3 | 0 |
| v1.3.0 | 0 |
| v1.3.1 | 0 |
| v1.3.2 | 0 |
| v1.3.3 | 0 |
| v1.3.4 | 0 |
| v1.4.0 | 0 |
| v1.4.1 | 0 |
| v1.4.2 | 0 |
| v1.4.3 | 0 |
| v1.4.4 | 0 |
| v1.4.5 | 0 |
| v1.5.0 | 0 |
| v1.5.1 | 0 |
| v1.5.2 | 0 |
| v1.5.3 | 0 |
| v1.5.4 | 0 |
| v1.5.5 | 0 |
| v1.6.0 | 0 |
| v1.6.1 | 0 |
| v1.6.10 | 0 |
| v1.6.2 | 0 |
| v1.6.3 | 0 |
| v1.6.4 | 0 |
| v1.6.5 | 0 |
| v1.6.6 | 0 |
| v1.6.7 | 0 |
| v1.6.8 | 0 |
| v1.6.9 | 0 |
| v1.7.0 | 0 |
| v1.7.1 | 0 |
| v1.7.2 | 0 |
| v1.8.0 | 0 |
| v1.8.1 | 0 |
| v1.8.2 | 0 |
| v1.8.3 | 0 |
| v1.8.4 | 0 |
| v1.9.0-0.1.rc1 | 0 |
| v1.9.0-0.2.rc2 | 0 |
| v1.9.0-1 | 0 |
| v1.9.0-2 | 0 |
| v1.9.0.1-1 | 0 |
| v1.9.1-0.1.rc1 | 0 |
| v1.9.1-0.2.rc2 | 0 |
| v1.9.1-0.3.rc3 | 0 |
| v1.9.1-0.4.rc4 | 0 |
| v1.9.1-1 | 0 |
| v1.9.2-0.1.rc1 | 0 |
| v1.9.2-0.2.rc2 | 0 |
| v1.9.2-1 | 0 |
| v1.9.3-0.1.rc1 | 0 |
| v1.9.3-0.2.rc2 | 0 |
| v1.9.3-0.3.rc3 | 0 |
| v1.9.3-1 | 0 |
| v1.9.4-0.1.rc1 | 0 |
| v1.9.4-0.2.rc2 | 0 |
| v1.9.4-0.3.rc3 | 0 |
| v1.9.4-1 | 0 |
| v1.9.5-0.1.rc1 | 0 |
| v1.9.5-1 | 0 |
| v1.9.6-0.1.rc1 | 0 |
| v1.9.6-1 | 0 |
| v2.0.0-0.6.rc1 | 0 |
| v2.0.0-0.7.rc2 | 0 |
| v2.0.0-0.8.rc3 | 0 |
| v2.0.0-0.9.rc4 | 0 |
| v2.0.0.0-1 | 0 |
| v2.0.0.1-1 | 0 |
| v2.0.0.2-1 | 0 |
| v2.0.1.0-0.1.rc1 | 0 |
| v2.0.1.0-0.2.rc2 | 0 |
| v2.0.1.0-1 | 0 |
| v2.0.2.0-0.1.rc1 | 0 |
| v2.0.2.0-0.2.rc2 | 0 |
| v2.0.2.0-0.3.rc3 | 0 |
| v2.0.2.0-0.4.rc4 | 0 |
| v2.0.2.0-1 | 0 |
| v2.1.0.0-0.1.rc1 | 0 |

**Comment by jctanner** [comment] 2016-05-02 16:09
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

Our reasons and evidence for this are:
- Based on the test results, the number of changes is always zero if the users already exist in almost every version of ansible.

And we suggest that:
- Validate your usecase on a more recent version of ansible.

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by jctanner** [comment] 2016-05-02 17:28
might have misread the description.

**Comment by jctanner** [comment] 2016-05-02 18:31
Ok, I misunderstood the inital description and have modified the test.

```
$ cat test.sh 
#!/bin/bash

# Set both groups for the user
ssh root@10.0.0.120 'pw usermod test1 -G mysql,cyrus'


rm -f results.log
ansible-playbook -i inventory -vvvv site.yml | tee -a results.log
RC=$?
if [[ $RC != 0 ]]; then
    exit 99
fi
# Find the changed count ...
CHANGED=$(cat results.log | egrep ^freebsdbox | tail -n1 | awk '{print $4}' | cut -d\= -f2)
echo "CHANGED: $CHANGED"

# root@:~ # id test1
# uid=1002(test1) gid=1004(test1) groups=1004(test1),1001(mysql)
# root@:~ # pw usermod test1 -G mysql,cyrus                                                                                    
# root@:~ # id test1
# uid=1002(test1) gid=1004(test1) groups=1004(test1),1001(mysql),1002(cyrus)

# Get the current groups
RGROUPS=$(ssh root@10.0.0.120 '/usr/bin/id test1') 
RGROUPS=$(echo $RGROUPS | awk '{print $3}')
echo $RGROUPS

if [[ $RGROUPS != 'groups=1004(test1),1001(mysql)' ]]; then
    echo "$RGROUPS != groups=1004(test1),1001(mysql)"
    exit 1
else
    echo "$RGROUPS == groups=1004(test1),1001(mysql)"
    if [[ $CHANGED == 1 ]]; then
        exit 0
    else
        exit 1
    fi    
fi


$ cat site.yml 
- hosts: freebsdbox
  #gather_facts: False
  tasks:
    #- shell: whoami
    - name: create the required groups
      group:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql
        - cyrus

    - name: Create FreeBSD users 
      user: 
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        groups: "{{ item.groups }}"
        comment: "{{ item.comment }}"
        append: no 
      with_items: 
        - { name: 'test1' , groups: 'mysql', password: '11111', comment: 'Vasja' } 
      when: ansible_os_family == "FreeBSD"

$ cat inventory 
freebsdbox ansible_ssh_host=10.0.0.120 ansible_ssh_user=root ansible_python_interpreter=/usr/local/bin/python2.7
```

**Comment by jctanner** [comment] 2016-05-02 18:32
| version | rc |
| --- | --- |
| 0.0.1 | 1 |
| 0.0.2 | 1 |
| 0.01 | 1 |
| 0.3 | 1 |
| 0.3.1 | 1 |
| 0.4 | 1 |
| 0.4.1 | 1 |
| 0.5 | 1 |
| 0.6 | 1 |
| 0.7 | 1 |
| 0.7.1 | 1 |
| 0.7.2 | 1 |
| 0.8 | 1 |
| v0.9 | 1 |
| v1.0 | 1 |
| v1.1 | 1 |
| v1.2 | 0 |
| v1.2.1 | 0 |
| v1.2.2 | 0 |
| v1.2.3 | 0 |
| v1.3.0 | 0 |
| v1.3.1 | 0 |
| v1.3.2 | 0 |
| v1.3.3 | 0 |
| v1.3.4 | 0 |
| v1.4.0 | 0 |
| v1.4.1 | 0 |
| v1.4.2 | 0 |
| v1.4.3 | 0 |
| v1.4.4 | 0 |
| v1.4.5 | 0 |
| v1.5.0 | 0 |
| v1.5.1 | 1 |
| v1.5.2 | 1 |
| v1.5.3 | 0 |
| v1.5.4 | 0 |
| v1.5.5 | 0 |
| v1.6.0 | 0 |
| v1.6.1 | 0 |
| v1.6.10 | 0 |
| v1.6.2 | 0 |
| v1.6.3 | 0 |
| v1.6.4 | 0 |
| v1.6.5 | 0 |
| v1.6.6 | 0 |
| v1.6.7 | 0 |
| v1.6.8 | 0 |
| v1.6.9 | 0 |
| v1.7.0 | 0 |
| v1.7.1 | 0 |
| v1.7.2 | 0 |
| v1.8.0 | 0 |
| v1.8.1 | 0 |
| v1.8.2 | 0 |
| v1.8.3 | 0 |
| v1.8.4 | 0 |
| v1.9.0-0.1.rc1 | 0 |
| v1.9.0-0.2.rc2 | 0 |
| v1.9.0-1 | 0 |
| v1.9.0-2 | 0 |
| v1.9.0.1-1 | 0 |
| v1.9.1-0.1.rc1 | 0 |
| v1.9.1-0.2.rc2 | 0 |
| v1.9.1-0.3.rc3 | 0 |
| v1.9.1-0.4.rc4 | 0 |
| v1.9.1-1 | 0 |
| v1.9.2-0.1.rc1 | 0 |
| v1.9.2-0.2.rc2 | 0 |
| v1.9.2-1 | 0 |
| v1.9.3-0.1.rc1 | 0 |
| v1.9.3-0.2.rc2 | 0 |
| v1.9.3-0.3.rc3 | 0 |
| v1.9.3-1 | 0 |
| v1.9.4-0.1.rc1 | 0 |
| v1.9.4-0.2.rc2 | 0 |
| v1.9.4-0.3.rc3 | 0 |
| v1.9.4-1 | 0 |
| v1.9.5-0.1.rc1 | 0 |
| v1.9.5-1 | 0 |
| v1.9.6-0.1.rc1 | 0 |
| v1.9.6-1 | 0 |
| v2.0.0-0.6.rc1 | 1 |
| v2.0.0-0.7.rc2 | 1 |
| v2.0.0-0.8.rc3 | 1 |
| v2.0.0-0.9.rc4 | 1 |
| v2.0.0.0-1 | 1 |
| v2.0.0.1-1 | 1 |
| v2.0.0.2-1 | 1 |
| v2.0.1.0-0.1.rc1 | 0 |
| v2.0.1.0-0.2.rc2 | 0 |
| v2.0.1.0-1 | 0 |
| v2.0.2.0-0.1.rc1 | 0 |
| v2.0.2.0-0.2.rc2 | 0 |
| v2.0.2.0-0.3.rc3 | 0 |
| v2.0.2.0-0.4.rc4 | 0 |
| v2.0.2.0-1 | 0 |
| v2.1.0.0-0.1.rc1 | 0 |

**Comment by jctanner** [comment] 2016-05-02 18:32
The results are still mostly the same as before, except for the cases where we had regressions in the inital versions of 2.x.

**Closed as completed by jctanner** 2016-05-02 18:32 UTC
Labels: P2, bug_report
