### ISSUE TITLE
docker_container: When using restart_policy, Ansible restarts running container

### ISSUE THREAD

**Issue by dcbishop** [ansible/ansible-modules-core#3864] opened 2016-06-04 01:31 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No changes.
##### OS / ENVIRONMENT

Host: Arch
Managed: Ubuntu 16.04
##### SUMMARY

When the restart_policy is used, the container restarts each Ansible run.

This happens with both `restart_policy=on-failure` and `restart_policy=always`.

Even with `restart_policy=always`, that shouldn't happen as its a [setting telling docker how to manage the container](https://docs.docker.com/engine/reference/run/#restart-policies-restart), not telling Ansible to restart the container each run (if that was desired it would probably be in `state=restart`).

The `restart_policy` and `restart_retries` are correctly past onto docker though as seen though docker inspect.

```
$ docker inspect notebook | grep -i restartpolicy -A 3
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 5
            },
```

Setting `restart=no` doesn't help either.

Side note: It's a separate bug but the `restart_policy=unless-stopped` and `restart_policy=no` options are missing in `docker_container`, but present in `docker`.
##### STEPS TO REPRODUCE

```

---
- name: Jupyter notebook container
  docker_container:
    image: jupyter/all-spark-notebook
    name: notebook
    ports: "8888:8888"
    volumes: "{{data_location}}:/home/jovyan/work:rw"
    state: started
    restart_policy: on-failure
    restart_retries: 5
    restart: no
    network_mode: "host"
  tags: jupyter
```
##### EXPECTED RESULTS

Dockers RestartPolicy should be set, but container shouldn't actually be restarted.
##### ACTUAL RESULTS

Ansible restarts the docker container every run.
Dockers restart policy is correctly set though.

```
TASK [docker-jupyter : Jupyter notebook container] *****************************
changed: [hextor]
```

More detail.

```
TASK [docker-jupyter : Jupyter notebook container] *****************************
task path: /home/hegemon/programming/ansible/roles/docker-jupyter/tasks/main.yml:3
<hextor> ESTABLISH SSH CONNECTION FOR USER: None
<hextor> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthenticat
ion=no -o ConnectTimeout=10 -o ControlPath=/home/hegemon/.ansible/cp/ansible-ssh-%h-%p-%r hextor '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1465003680.83-100689233037855 `" 
&& echo ansible-tmp-1465003680.83-100689233037855="` echo $HOME/.ansible/tmp/ansible-tmp-1465003680.83-100689233037855 `" ) && sleep 0'"'"''
<hextor> PUT /tmp/tmpaNXfnK TO /home/hegemon/.ansible/tmp/ansible-tmp-1465003680.83-100689233037855/docker_container
<hextor> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthe
ntication=no -o ConnectTimeout=10 -o ControlPath=/home/hegemon/.ansible/cp/ansible-ssh-%h-%p-%r '[hextor]'
<hextor> ESTABLISH SSH CONNECTION FOR USER: None
<hextor> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthenticat
ion=no -o ConnectTimeout=10 -o ControlPath=/home/hegemon/.ansible/cp/ansible-ssh-%h-%p-%r -tt hextor '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-bvvrebckovfdmiopwszdr
fpftnrsibyu; LANG=en_AU.UTF-8 LC_ALL=en_AU.UTF-8 LC_MESSAGES=en_AU.UTF-8 /usr/bin/python2 /home/hegemon/.ansible/tmp/ansible-tmp-1465003680.83-100689233037855/docker_container; rm -rf "/home/hegemon/.ansible/t
mp/ansible-tmp-1465003680.83-100689233037855/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
changed: [hextor] => {"ansbile_facts": {"ansible_docker_container": {"AppArmorProfile": "", "Args": ["--", "start-notebook.sh"], "Config": {"AttachStderr": false, "AttachStdin": false, "AttachStdout": false, "
Cmd": ["start-notebook.sh"], "Domainname": "", "Entrypoint": ["tini", "--"], "Env": ["PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "DEBIAN_FRONTEND=noninteractive", "CONDA
_DIR=/opt/conda", "SHELL=/bin/bash", "NB_USER=jovyan", "NB_UID=1000", "HOME=/home/jovyan", "LC_ALL=en_US.UTF-8", "LANG=en_US.UTF-8", "LANGUAGE=en_US.UTF-8", "APACHE_SPARK_VERSION=1.6.1", "SPARK_HOME=/usr/local
/spark", "PYTHONPATH=/usr/local/spark/python:/usr/local/spark/python/lib/py4j-0.9-src.zip", "MESOS_NATIVE_LIBRARY=/usr/local/lib/libmesos.so", "SPARK_OPTS=--driver-java-options=-Xms1024M --driver-java-options=
-Xmx4096M --driver-java-options=-Dlog4j.logLevel=info", "R_LIBS_USER=/usr/local/spark/R/lib"], "ExposedPorts": {"8888/tcp": {}}, "Hostname": "hextor", "Image": "jupyter/all-spark-notebook", "Labels": {}, "OnBu
ild": null, "OpenStdin": false, "StdinOnce": false, "Tty": false, "User": "jovyan", "Volumes": {"/mnt/storage3/data/jupyter-all-spark": {}}, "WorkingDir": "/home/jovyan/work"}, "Created": "2016-06-04T01:28:05.
309498256Z", "Driver": "btrfs", "ExecIDs": null, "GraphDriver": {"Data": null, "Name": "btrfs"}, "HostConfig": {"AutoRemove": false, "Binds": ["/mnt/storage3/data/jupyter-all-spark:/home/jovyan/work:rw"], "Blk
ioBps": 0, "BlkioDeviceReadBps": null, "BlkioDeviceReadIOps": null, "BlkioDeviceWriteBps": null, "BlkioDeviceWriteIOps": null, "BlkioIOps": 0, "BlkioWeight": 0, "BlkioWeightDevice": null, "CapAdd": null, "CapD
rop": null, "Cgroup": "", "CgroupParent": "", "ConsoleSize": [0, 0], "ContainerIDFile": "", "CpuCount": 0, "CpuPercent": 0, "CpuPeriod": 0, "CpuQuota": 0, "CpuShares": 0, "CpusetCpus": "", "CpusetMems": "", "D
evices": null, "DiskQuota": 0, "Dns": null, "DnsOptions": null, "DnsSearch": null, "ExtraHosts": null, "GroupAdd": null, "IpcMode": "", "Isolation": "", "KernelMemory": 0, "Links": null, "LogConfig": {"Config"
: {}, "Type": "json-file"}, "Memory": 0, "MemoryReservation": 0, "MemorySwap": 0, "MemorySwappiness": -1, "NetworkMode": "host", "OomKillDisable": false, "OomScoreAdj": 0, "PidMode": "", "PidsLimit": 0, "PortB
indings": {"8888/tcp": [{"HostIp": "0.0.0.0", "HostPort": "8888"}]}, "Privileged": false, "PublishAllPorts": false, "ReadonlyRootfs": false, "RestartPolicy": {"MaximumRetryCount": 5, "Name": "on-failure"}, "Sa
ndboxSize": 0, "SecurityOpt": null, "ShmSize": 67108864, "StorageOpt": null, "UTSMode": "", "Ulimits": null, "UsernsMode": "", "VolumeDriver": "", "VolumesFrom": null}, "HostnamePath": "/var/lib/docker/contain
ers/8a98bb4ac722d46f7509c8ac72223572c977f3bd9e133361c28bbbaeaf3f5c78/hostname", "HostsPath": "/var/lib/docker/containers/8a98bb4ac722d46f7509c8ac72223572c977f3bd9e133361c28bbbaeaf3f5c78/hosts", "Id": "8a98bb4a
c722d46f7509c8ac72223572c977f3bd9e133361c28bbbaeaf3f5c78", "Image": "sha256:f27c18eb757025cde813b65ba845be58b6cca0ed24339bbec5ad1ba574c4a3f9", "LogPath": "/var/lib/docker/containers/8a98bb4ac722d46f7509c8ac722
23572c977f3bd9e133361c28bbbaeaf3f5c78/8a98bb4ac722d46f7509c8ac72223572c977f3bd9e133361c28bbbaeaf3f5c78-json.log", "MountLabel": "", "Mounts": [{"Destination": "/home/jovyan/work", "Mode": "rw", "Propagation": 
"rprivate", "RW": true, "Source": "/mnt/storage3/data/jupyter-all-spark"}, {"Destination": "/mnt/storage3/data/jupyter-all-spark", "Driver": "local", "Mode": "", "Name": "0ae4dc63b4566e675990f8d0ed763611e10687
c914826f4ff3e3d6b23a874456", "Propagation": "", "RW": true, "Source": "/var/lib/docker/volumes/0ae4dc63b4566e675990f8d0ed763611e10687c914826f4ff3e3d6b23a874456/_data"}], "Name": "/notebook", "NetworkSettings":
 {"Bridge": "", "EndpointID": "", "Gateway": "", "GlobalIPv6Address": "", "GlobalIPv6PrefixLen": 0, "HairpinMode": false, "IPAddress": "", "IPPrefixLen": 0, "IPv6Gateway": "", "LinkLocalIPv6Address": "", "Link
LocalIPv6PrefixLen": 0, "MacAddress": "", "Networks": {"host": {"Aliases": null, "EndpointID": "8234d6355e6786f32231a7918a870dfeda73dd1cf5d0df0db0fe392fbd1773e1", "Gateway": "", "GlobalIPv6Address": "", "Globa
lIPv6PrefixLen": 0, "IPAMConfig": null, "IPAddress": "", "IPPrefixLen": 0, "IPv6Gateway": "", "Links": null, "MacAddress": "", "NetworkID": "1746a0b39f24f90c291afb013f1770b50e15195946f261937d93d6774ff9dec8"}},
 "Ports": {}, "SandboxID": "1f0148cb9c044be2522a8e5a9f2c5694ed8087d6446b1cf7361b222c1cbcfff3", "SandboxKey": "/var/run/docker/netns/default", "SecondaryIPAddresses": null, "SecondaryIPv6Addresses": null}, "Pat
h": "tini", "ProcessLabel": "", "ResolvConfPath": "/var/lib/docker/containers/8a98bb4ac722d46f7509c8ac72223572c977f3bd9e133361c28bbbaeaf3f5c78/resolv.conf", "RestartCount": 0, "State": {"Dead": false, "Error":
 "", "ExitCode": 0, "FinishedAt": "0001-01-01T00:00:00Z", "OOMKilled": false, "Paused": false, "Pid": 17074, "Restarting": false, "Running": true, "StartedAt": "2016-06-04T01:28:08.519949445Z", "Status": "runn
ing"}}}, "changed": true, "invocation": {"module_args": {"api_version": null, "blkio_weight": null, "cacert_path": null, "capabilities": null, "cert_path": null, "command": null, "cpu_period": null, "cpu_quota": null, "cpu_shares": null, "cpuset_cpus": null, "cpuset_mems": null, "debug": false, "detach": true, "devices": null, "dns_opts": null, "dns_search_domains": null, "dns_servers": null, "docker_host": null, "
entrypoint": null, "env": null, "etc_hosts": null, "exposed_ports": null, "filter_logger": false, "force_kill": false, "groups": null, "hostname": null, "image": "jupyter/all-spark-notebook", "interactive": fa
lse, "ipc_mode": null, "keep_volumes": true, "kernel_memory": null, "key_path": null, "kill_signal": null, "labels": null, "links": null, "log_driver": "json-file", "log_options": null, "mac_address": null, "m
emory": "0", "memory_reservation": null, "memory_swap": null, "memory_swappiness": null, "name": "notebook", "network_mode": "host", "networks": null, "oom_killer": null, "paused": false, "pid_mode": null, "po
rts": "8888:8888", "privileged": false, "published_ports": ["8888:8888"], "pull": false, "read_only": false, "recreate": false, "restart": false, "restart_policy": "on-failure", "restart_retries": 5, "security
_opts": null, "shm_size": null, "ssl_version": null, "state": "started", "stop_signal": null, "stop_timeout": null, "timeout": null, "tls": null, "tls_hostname": null, "tls_verify": null, "trust_image_content"
: false, "tty": false, "ulimits": null, "user": null, "uts": null, "volume_driver": null, "volumes": ["/mnt/storage3/data/jupyter-all-spark:/home/jovyan/work:rw"], "volumes_from": null}, "module_name": "docker
_container"}}
```

**Comment by sivel** [comment] 2016-06-04 01:40
Duplicate of the already merged https://github.com/ansible/ansible-modules-core/pull/3785

**Closed as completed by sivel** 2016-06-04 01:40 UTC

**Comment by chouseknecht** [comment] 2016-06-04 06:06
The restart policy issue is fixed, as sivel indicated. However, the provided example exposed a completely different issue, which I documented here #3866
