### ISSUE TITLE
Unarchive fails in --check mode after dir is created with file

### ISSUE THREAD

**Issue by varnav** [ansible/ansible-modules-core#2026] opened 2015-09-07 16:16 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

1.9.2
##### Ansible Configuration:

Typical
##### Environment:

Centos 7 Netinstall
##### Summary:

Playbook fails in the check mode but works in real mode.
##### Steps To Reproduce:

This is 100% valid and working in real mode playbook, that fails in the check mode:

```
- name: Create dir
  file: path=/tmp/foo state=directory

- name: Copy files to dir
  unarchive: src=foo.tar.gz dest=/tmp/foo/
```
##### Expected Results:

Successful completion in check mode
##### Actual Results:

Fails with "must be an existing dir" in check mode.

**Comment by bcoca** [comment] 2015-09-08 16:48
what version of ansible?

**Comment by bcoca** [comment] 2015-09-08 16:48
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by Jmainguy** [comment] 2015-10-27 19:43
@varnav @bcoca I don't think this is a bug, seems to be expected behavior.

In check mode

```
- name: Create dir
  file: path=/tmp/foo state=directory
```

Will report back whether it would have created the directory or not, but not actually create it.

In check mode

```
- name: Copy files to dir
  unarchive: src=foo.tar.gz dest=/tmp/foo/
```

Will report back if its possible to untar it there, which in this instance it is not, since /tmp/foo does not exist (check mode did not create it in previous step).

**Comment by bcoca** [comment] 2015-10-28 00:58
Agreed, check mode applies to the individual tasks, the archive task has no info that the file task would have created that directory. You might want to have a when: condition based on the file task being ok or not skipped.

Closing as this is not a bug, just how check mode works

**Closed as completed by bcoca** 2015-10-28 00:58 UTC
