### ISSUE TITLE
sudo not working correctly on 1.9.2

### ISSUE THREAD

**Issue by damienhollis** [ansible/ansible-modules-core#1679] opened 2015-07-07 10:06 UTC
Hi,

I have been troubling shooting a problem with ansible on RHEL7.  I've just started to provision new servers using scripts that worked correctly on RHEL6.  They also worked correctly (after some tickering) on RHEL7 when I ran then as root (basically to bootstrap the environment).  However, ever since I'm been trying to run them using sudo, they have been failing.  I created a very simple playbook that used sudo and it worked fine.  So I narrowed down the problem to tasks within roles that require sudo failing and that seems to be the case.  I can see that ansible is running the tasks with sudo (using -vvv) but I don't think that the sudo password is being supplied because I get an error saying that no input was received before timeout (I don't have the actual error handy but it is something like that).  

The problem is similar to this issue: https://github.com/ansible/ansible-modules-core/issues/1490.  So to workaround it I setup passwordless sudo and now the playbooks run, which suggest that it is a problem with ansible not providing the sudo password to the tasks within roles.

Regards,
Damien

**Comment by bcoca** [comment] 2015-07-07 13:12
we really need more info, please fill in the template https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md so we can better asses this issue.

**Comment by damienhollis** [comment] 2015-07-07 21:34
Hi Brian,

Sorry, it was late when I finally got something working and wanted to get the issue submitted in case you had seen something similar.  Here is the template completed.  Let me know if you need anything else.

# Issue Type:

“Bug Report”

# Ansible Version:

$ ansible --version
ansible 1.9.2
  configured module search path = None

# Ansible Configuration:

There are no differences.  I did play with using "become" in case that resolved the issue but it didn't, so I reverted the changes.

# Environment:

RHEL 7

# Summary:

Sudo not working on all tasks

# Steps To Reproduce:

Originally I thought this issue was related to roles but while trying to reproduce it I found that the first few sudo operations work but it seems the 5th one fails - which is why my very simple test case did now work.  Here is the playbook that I'm using (of course what it is doing makes no sense):
- hosts: test
  sudo: yes
  tasks:
  - name: test sudo
    service: name=firewalld.service state=stopped enabled=no
  - name: test sudo
    service: name=firewalld.service state=stopped enabled=no
  - name: test sudo
    service: name=firewalld.service state=stopped enabled=no
  - name: test sudo
    service: name=firewalld.service state=stopped enabled=no
  - name: test sudo
    service: name=firewalld.service state=stopped enabled=no
  - name: test sudo
    service: name=firewalld.service state=stopped enabled=no
  - name: test sudo
    service: name=firewalld.service state=stopped enabled=no

## The test inventory looks like:

[test]
test  ansible_connection=local

# Expected Results:

sudo should work on all tasks.

# Actual Results:

ansible-playbook -i inventories/test --ask-sudo-pass test-1.yml
SUDO password:

PLAY [test] *******************************************************************

GATHERING FACTS ***************************************************************
ok: [test]

TASK: [test sudo] *************************************************************
ok: [test]

TASK: [test sudo] *************************************************************
ok: [test]

TASK: [test sudo] *************************************************************
ok: [test]

TASK: [test sudo] *************************************************************
ok: [test]

TASK: [test sudo] *************************************************************
fatal: [test] => timeout waiting for sudo password prompt:

FATAL: all hosts have already failed -- aborting

**Comment by damienhollis** [comment] 2015-07-07 23:27
Further information, I have just used ansible to apply changes to a remote server and it seems to have no problems with sudo.  Not sure whether ansible_connection=local could be an issue?

**Comment by damienhollis** [comment] 2015-07-07 23:30
Actually, that is not true.  It got a lot further and then failed after a long time with the same error:

"fatal: [189616-45] => ssh connection error while waiting for sudo password prompt"

**Comment by abadger** [comment] 2015-07-08 14:47
I was unable to reproduce locally on both fedora 21 and centos7.  Used your inventory and the firewalld playbook.  Maybe there's also something about the sudo configuration interacting with ansible?

**Comment by bcoca** [comment] 2015-07-08 14:49
this sounds more like a resource issue than anything else, check dmesg/logs on the target machine

**Comment by damienhollis** [comment] 2015-07-08 21:39
Hi, thanks for taking a look.  There was nothing of interest in the dmesg logs but that made me think to look in the messages log and I found this:

```
Jul  8 21:34:15 189616-46 python: ansible-service Invoked with name=firewalld.service pattern=None enabled=False state=stopped sleep=None arguments= runlevel=default
Jul  8 21:34:15 189616-46 dbus-daemon: dbus[478]: [system] Activating via systemd: service name='net.reactivated.Fprint' unit='fprintd.service'
Jul  8 21:34:15 189616-46 dbus[478]: [system] Activating via systemd: service name='net.reactivated.Fprint' unit='fprintd.service'
Jul  8 21:34:15 189616-46 systemd: Starting Fingerprint Authentication Daemon...
Jul  8 21:34:15 189616-46 systemd: fprintd.service start request repeated too quickly, refusing to start.
Jul  8 21:34:15 189616-46 systemd: Failed to start Fingerprint Authentication Daemon.
Jul  8 21:34:40 189616-46 dbus-daemon: dbus[478]: [system] Failed to activate service 'net.reactivated.Fprint': timed out
Jul  8 21:34:40 189616-46 dbus[478]: [system] Failed to activate service 'net.reactivated.Fprint': timed out
```

I'll investigate on the internet but if you know what the issue is or if you think it is an ansible problem, please let me know.  I'll update this issue with more information as I find it.

Thanks.

**Comment by bcoca** [comment] 2015-07-08 22:12
that seems that systemd is being 'smart' and not allowing you to do what you asked it to do.

**Comment by bcoca** [comment] 2015-07-08 22:13
closing this as this does not seem to be an ansible issue but the firewall, the authentication service  and systemd not liking frequent restarts.

**Closed as completed by bcoca** 2015-07-08 22:13 UTC
Labels: bug_report

**Comment by damienhollis** [comment] 2015-07-09 21:01
Hi, I have resolved the issue.  Just in case other people have this issue, all I needed to do was disable the fingerprint reader service - see this article for details: http://www.linuxquestions.org/questions/red-hat-31/fprintd-errors-in-virtual-environment-915078/

Thanks,
Damien

**Comment by neggert** [comment] 2015-07-23 14:54
Just ran into a similar problem. Disabling fingerprint reader auth fixed it.

**Comment by bcoca** [comment] 2015-07-23 15:51
why does the fingerprint reader get to stop the firewall from restarting?????

why is it running on servers?
