### ISSUE TITLE
git: not properly using key when ssh protocol is used

### ISSUE THREAD

**Issue by pmoust** [ansible/ansible-modules-core#184] opened 2014-10-14 10:47 UTC
**Issue Type:**
Bug Report

**Ansible Version:**
Ansible 1.8

**Environment:**
Running: MacOS X Mavericks
Managing: Ubuntu 14.04

**Summary:**
user with proper private key is unable to fetch remote repo via ssh using ansible git module

**Steps To Reproduce:**
assume `whatever/mchap.git` is a private repo and the root user and ansible user has proper keys.

``` yaml
- name: Grab mchap application from Github
  git: repo=ssh://git@github.com:/whatever/mchap.git accept_hostkey=yes recursive=yes version={{ item.branch }} dest=/var/www/{{ item.dir }} update=no
  with_items:
      - { name : 'production',  branch: 'master',   dir: 'mchap',  cname: 'mchap' }
      - { name : 'staging',     branch: 'next',     dir: 'mchap2', cname: 'mchap2' }
  sudo: yes
```

**Expected Results:**

Clone the repo

**Actual Results:**

```
msg: Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
failed: [10.00.33.60] => (item={'cname': 'mchap', 'name': 'staging', 'dir': 'mchap', 'branch': 'next'}) => {"cmd": "/usr/bin/git ls-remote ssh:********", "failed": true, "item": {"branch": "next", "cname": "mchap", "dir": "mchap", "name": "staging"}, "rc": 128}
stderr: ERROR: Repository not found.
fatal: Could not read from remote repository.
```

**Comment by pmoust** [comment] 2014-10-14 10:48
Same behavior even if `key_file` is specified.

**Comment by jimi-c** [comment] 2014-10-22 03:43
@pmoust I see you're using sudo in the above example - is the key available to the root user?

**Comment by pmoust** [comment] 2014-10-22 05:14
@jimi-c yes

**Comment by pmoust** [comment] 2014-11-28 08:31
@jimi-c seeing that 1.8 `recursive` option now properly checks the commit hash of submodules specified in main git repo, only thing blocking us from properly using the module is the authentication issue.

Is this paramiko or ansible issue?

**Comment by abadger** [comment] 2014-12-09 02:23
@pmoust I was just able to replicate.  It looks like the submodules in a private repo are the important piece to being able to make this occur.

**Comment by abadger** [comment] 2014-12-09 02:24
If I strip the playbook down to this:

```
- hosts: localhost
  tasks:
    - name: Grab application from Github
      git: repo=ssh://git@github.com/ansible/staging.git accept_hostkey=yes recursive=yes version=master dest="/  var/tmp/mytest" update=yes
      sudo: yes
```

The error I get is this:

```

failed: [localhost] => {"cmd": "/bin/git ls-remote ssh:********", "failed": true, "rc": 128}
stderr: ERROR: Repository not found.
fatal: Could not read from remote repository.
```

**Comment by abadger** [comment] 2014-12-15 21:22
After trying to reproduce this again today, I realized that my previous post had mispelled the private repo I was testing against.  So I'm once again unable to reproduce this.

Is there any other information you can give us or some simple test case?  Without being able to reproduce I'm not sure if the problem lies with using sudo, git submodules or something else.

**Comment by pmoust** [comment] 2014-12-15 22:42
I 'll try to come up with a proper repro case for you to investigate in a few.

**Comment by wojtek-oledzki** [comment] 2015-03-23 12:16
you can try running this to verify that it's ansible SSH settings which is breaking the ssh.

```
ansible YOUR_BOX -a "ssh -T git@github.com" -vvvv
```

Problem in my case was that some SSH settings was messing with the ssh agent on the box. This fixed it for me, but I'm forwarding my keys to the box, and you have proper keys on the box.

```
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes
```

**Comment by pmoust** [comment] 2015-03-23 14:50
@wojtek-oledzki @abadger will find some time during this week to check.

To anyone reading this, if you see me MIA for more than a week, ping back with a @pmoust mention.

**Comment by ghost** [comment] 2015-04-20 14:58
I believe I'm also experiencing the same error as @pmoust:

**Ansible version:**
Ansible 1.9.0.1 (via Homebrew)

**Environment:**
Running: MacOS X Yosemite (10.10.3)
Managing: Amazon Linux

**Summary:**
User with private key is unable to clone remote repository via ssh using Ansible git module

**Playbook step:**

```
  - name: Check out code from GitHub
    git: repo=git@github.com:my_organisation/my_private_repo.git
         accept_hostkey=yes
         key_file=/home/ec2-user/.ssh/my_ssh_key
         dest=/path/to/my_dir
         version='{{ version }}'
         recursive=no
         force=yes
```

**Playbook output for this step:**

```
TASK: [Check out code from GitHub] ****************************************
failed: [my_host] => {"cmd": "/usr/bin/git ls-remote '' -h refs/heads/v0.4.1", "failed": true, "rc": 128}
stderr: ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

msg: ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

FATAL: all hosts have already failed -- aborting
```

**From the local (control) machine:**

```
$ ansible -i hosts my_host -a "ssh -T git@github.com" -vvvv
<my_host> ESTABLISH CONNECTION FOR USER: ribmo
<my_host> REMOTE_MODULE command ssh -T 
<my_host> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/ribmo/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 my_host /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1429541329.3-3552782092648 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1429541329.3-3552782092648 && echo $HOME/.ansible/tmp/ansible-tmp-1429541329.3-3552782092648'
<my_host> PUT /var/folders/jb/11ny_l3x27x3rm8gx83qvw_00000gn/T/tmpv_wAf1 TO /home/ec2-user/.ansible/tmp/ansible-tmp-1429541329.3-3552782092648/command
<my_host> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/ribmo/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 my_host /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/ec2-user/.ansible/tmp/ansible-tmp-1429541329.3-3552782092648/command; rm -rf /home/ec2-user/.ansible/tmp/ansible-tmp-1429541329.3-3552782092648/ >/dev/null 2>&1'
my_host | FAILED | rc=255 >>
Permission denied (publickey).
```

**From the remote machine:**

```
$ ssh git@github.com -i /home/ec2-user/.ssh/my_ssh_key
PTY allocation request failed on channel 0
Hi [redacted]! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed.
```

**Comment by ribmo** [comment] 2015-04-20 15:18
FWIW, I've only started experiencing the above issue since a HDD migration where I reinstalled OS X from scratch. Prior to the rebuild, I was using Ansible 1.8.4 and this playbook executed without errors.

**Comment by ghost** [comment] 2015-04-20 15:36
Goodness me, please ignore the above comment - it turns out that due to a restructuring of teams within the organisation, the user really did not have correct access rights! The user now has read permissions and I am no longer experiencing this error.

**Comment by arogulin** [comment] 2015-06-06 21:39
I have the same problem with ansible v1.9.1 on MacOS 10.9.5. My playbook contains:

```
- name: git pull
  git:
    repo=ssh://git@bitbucket.org:my_user/my_repo.git
    dest=/folder/repo
```

Output:

```
failed: [host.com] => {"cmd": "/usr/bin/git ls-remote origin -h refs/heads/master", "failed": true, "rc": 128}
stderr: conq: invalid repository syntax.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

SSH keys are properly installed. I check this as @wojtek-oledzki suggests:

```
$ ansible host -a "ssh -T git@bitbucket.org"
host.com | success | rc=0 >>
logged in as my_user.

You can use git or hg to connect to Bitbucket. Shell access is disabled.
```

I tried to add "accept_hostkey=yes" and "key_file" without any success.

**Comment by sivel** [comment] 2015-06-06 21:47
@saitovod, as the error mentions your repository URL (`ssh://git@bitbucket.org:my_user/my_repo.git`) is malformed.

It should either be (URL syntax):

`ssh://git@bitbucket.org/my_user/my_repo.git`

or (SCP syntax):

`git@bitbucket.org:my_user/my_repo.git`

https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#The-SSH-Protocol

**Comment by arogulin** [comment] 2015-06-06 22:36
Thank you so much, @sivel! "ssh://git@bitbucket.org/my_user/my_repo.git" - worked!
I used "ssh://git@bitbucket.org:my_user/my_repo.git" because bitbucket.org suggests this ssh url and ".git/config" contains the same url:

```
[remote "origin"]
        url = git@bitbucket.org:my_user/my_repo.git
        fetch = +refs/heads/*:refs/remotes/origin/*
```

**Comment by ericm24** [comment] 2015-07-20 18:29
I think I'm seeing the same problem.   Attempting to run ansible-pull.

ansible-pull -o -C develop -d /dev2/ansible/projectdir -i /dev2/ansible/inventory/localhost -U git://github.com/myrepo.git

ansible version: 1.9.1
OS X: 10.10

output:
Starting ansible-pull at 2015-07-20 13:23:14
localhost | FAILED >> {
    "cmd": "/usr/bin/git ls-remote origin -h refs/heads/develop", 
    "failed": true, 
    "msg": "fatal: remote error: \n  Repository not found.", 
    "rc": 128, 
    "stderr": "fatal: remote error: \n  Repository not found.\n", 
    "stdout": ""
}

**Comment by dave-kong** [comment] 2015-08-06 21:34
@sivel Damn, you saved me, too!  It's exactly the ':' vs. '/' issue.
Github copy of git@github.com:blah works by itself, but when using ssh:// prepend, must change the : to /

**Comment by ghost** [comment] 2015-11-26 09:30
I had problem when deploying with sudo: true, so currently I dont use sudo in git. But note that I have to change folder permissions, before and after this line:

```
- name: deploy with git
  git: >
    repo="{{ git_repository }}"
    dest="{{ git_repository_dest }}" 
  sudo: false
```

**Comment by tamakisquare** [comment] 2015-12-07 07:04
I had the same issue and it was resolved by setting `sudo: no`, but I don't understand why would that solve the issue. Can anyone explain to me what exactly was the issue and why would deploying with `sudo: no` fixes the issue? Thanks.

**Comment by jctanner** [comment] 2016-04-26 21:26
In ansible 1.9.4 I can't reproduce this issue as initially defined, but I can get an error based on the url given as an example.

Given this playbook ...

```
$ cat site.yml
- hosts: localhost
  gather_facts: False
  connection: local
  vars:
    testdir: /tmp/repotests
  tasks:
    - set_fact:
        srcdir: "{{ testdir + '/localrepo' }}"
        dstdir: "{{ testdir + '/checkout' }}"
        whoami: "{{ lookup('pipe', 'whoami') }}"

    - file: path="{{ srcdir }}" state=absent

    - shell: stat "{{ srcdir }}"
      ignore_errors: True
      register: repoexists
    - shell: git init "{{ srcdir }}"
      when: "repoexists.rc != 0"
    - shell: cd "{{ srcdir }}"; echo "test" > afile
      when: "repoexists.rc != 0"
    - shell: cd "{{ srcdir }}"; git add afile
      when: "repoexists.rc != 0"
    - shell: cd "{{ srcdir }}"; git commit -m "test"
      when: "repoexists.rc != 0"
    - shell: cd "{{ srcdir }}" ; git update-ref HEAD master
      when: "repoexists.rc != 0"

    - file:
        path: "{{ dstdir }}"
        state: absent
    - git:
         repo: "{{ 'ssh://' + whoami + '@localhost:' + srcdir }}"
         dest: "{{ dstdir }}"
         accept_hostkey: yes
         key_file: ~/.ssh/id_rsa
```

This error occurs ...

```
failed: [localhost] => {"cmd": "/usr/bin/git ls-remote 'ssh:********@localhost:/tmp/repotests/localrepo' -h refs/heads/HEAD", "failed": true, "rc": 128}
stderr: ssh: Could not resolve hostname localhost:: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

msg: ssh: Could not resolve hostname localhost:: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

FATAL: all hosts have already failed -- aborting
```

The duplicate colons in "localhost::" are something that git creates if there is a colon after the hostname and using the ssh:// protocol ...

```
[vagrant@localhost AMC-184]$ git ls-remote ssh://vagrant@remotehost:/tmp/repotests/localrepo -h refs/heads/HEAD
ssh: Could not resolve hostname remotehost:: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[vagrant@localhost AMC-184]$ git ls-remote ssh://vagrant@remotehost/tmp/repotests/localrepo -h refs/heads/HEAD
[vagrant@localhost AMC-184]$ echo $?
0
```

The resolution, as previously stated by @sivel in this bug is to not put a colon after the hostname.

**Closed as completed by jctanner** 2016-04-26 21:26 UTC
Labels: P2, bug_report

**Comment by pmoust** [comment] 2016-04-27 07:31
Aye, that's it, ty @jctanner
