### ISSUE TITLE
synchronize applies sudo incorrectly

### ISSUE THREAD

**Issue by UnkindPartition** [ansible/ansible-modules-core#1162] opened 2015-04-18 20:02 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.8.2
  configured module search path = None
```
##### Environment:

Control: Fedora 21, Target: Debian 7
##### Summary:

When invoking rsync, it looks like sudo is applied to the invokation on the control machine, not on the target one.
##### Steps To Reproduce:

Have the control machine prompt password upon sudo, and the target one not to.

Inventory file:

```
vagrant ansible_sudo=true ansible_ssh_user=vagrant
```

Execute

```
ansible vagrant -vvvvv -m synchronize -a 'set_remote_user=no src=x dest=/etc/z'
```
##### Expected Results:

I'd expect the command to succeed. E.g. if I replace synchronize with copy in the above example (and remove `set_remote_user=no`), it succeeds.
##### Actual Results:

```
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1429387186.36-81932903674806 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1429387186.36-81932903674806 && echo $HOME/.ansible/tmp/ansible-tmp-1429387186.36-81932903674806']
<127.0.0.1> PUT /tmp/tmpJQlYGS TO /home/feuerbach/.ansible/tmp/ansible-tmp-1429387186.36-81932903674806/synchronize
<127.0.0.1> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=ylobszwtfqjppaosnitxtqifoyqeimcy] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-ylobszwtfqjppaosnitxtqifoyqeimcy; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/feuerbach/.ansible/tmp/ansible-tmp-1429387186.36-81932903674806/synchronize; rm -rf /home/feuerbach/.ansible/tmp/ansible-tmp-1429387186.36-81932903674806/ >/dev/null 2>&1'"'"''
vagrant | FAILED >> {
    "failed": true, 
    "msg": "[sudo via ansible, key=ylobszwtfqjppaosnitxtqifoyqeimcy] password: \n", 
    "parsed": false
}
```

I.e. it tries to run sudo on the control machine and fails.

**Comment by fdutheil** [comment] 2015-07-27 13:54
Ansible Version:
ansible 1.9.2

Environment:
Control: Ubuntu 14.04, Target: FreeBSD 10 + Ubuntu 14.04

I can confirm that it's impossible to make synchronize work when sudo is involved. I can see in the  control machine logs that ansible tries to use the ansible_ssh_user to "sudo" on the control malchine.
Pretty blocking bug!

```
Jul 27 15:46:00 <control_machine> sudo: pam_unix(sudo:auth): conversation failed
Jul 27 15:46:00 <control_machine> sudo: pam_unix(sudo:auth): auth could not identify password for [<ansible_ssh_user>]
```

**Comment by rcarrillocruz** [comment] 2015-08-07 15:37
I'm hitting this too, I get a sudo auth failure on the control machine.

copy module works, but is way slower.

**Comment by timrchavez** [comment] 2015-08-07 19:46
FWIW I'm experiencing this issue on 2.0.0

**Comment by MichaelDrogalis** [comment] 2015-08-13 14:19
This is still hanging around for me also.

**Comment by derkork** [comment] 2015-12-15 10:07
I also got this one (Ansible 1.9.4).

**Comment by fdutheil** [comment] 2015-12-17 14:08
I don't understand why this bug is only P3, and why there is no progress update on this. It's been 8 months now since the first report.

**Comment by spieden** [comment] 2015-12-21 20:40
Just hit this with 1.9.4. I can't even seem to work around it by setting "sudo: no" on the task. Does anyone else have a workaround?

**Comment by abadger** [comment] 2015-12-23 17:36
I agree that synchronize behaves in a non-standard manner.  However, it is a known limitation of the module.  See the notes section of the docs http://docs.ansible.com/ansible/synchronize_module.html#notes

We're open to changes to this (although figuring out how to manage both the intuitive behaviour and backwards compatible behaviour may be difficult.) but at the moment, it simply is the way that synchronize operates.

My personal workaround has been to use two steps to move files around.  First, synchronize from the local machine to a remote machine directory that the remote_user owns.  Then synchronize from the first directory on the remote machine to the second machine on the remote machine.  This has drawbacks (two copies of the files.  For sensitive information, have to sudo to root, does not work with an unprivileged user.) but it works for many cases.

```
---
- hosts: rhel7-test
  become: True
  become_method: sudo
  tasks:
  # testdata is accessible to the account of the user running ansible
  # If it contains sensitive information, it is only accessible to the user
  # running ansible.  After the first synchronize, it will only be accessible
  # to the remote_user (the one we logged into the remote box as)
  - synchronize:
      src: /var/tmp/testdata/
      dest: /var/tmp/testdata-copy
      perms: true
    become: False
  - synchronize:
      src: /var/tmp/testdata-copy/
      dest: /var/tmp/final-destination
      owner: false
      group: false
      perms: true
    delegate_to: rhel7-test
  # At this point, final-destination is owned by the sudo user with the
  # permission bits that were on the original machine.
```

Note: I've been testing this on ansible-2.0.  I don't know if there's bugs in 1.9.x (or earlier) which make this fail.

**Comment by tima** [comment] 2015-12-23 17:58
Thanks @abadger. Looks about right to me given the circumstances.

**Comment by Janzert** [comment] 2016-01-19 03:18
Just upgraded from 1.7 or 8 to 2.0 and ran into this so it does seem like there is some behavior change from the older versions.

**Comment by abadger** [comment] 2016-01-26 05:31
Did some extensive testing of what 1.9.4 behaviour is and found that in 1.9.4 sudo _is_ being run on the remote machine, not on the controller.  In 2.0.0.x this behaviour changed and sudo started being run on the controller again.  Because of that, I've spent some time changing synchronize in 2.0.1 (the forthcoming release) to reimplement the 1.9.4 behaviour.  In general, in 2.0.1 the module should execute rsync on the controller (or the delegate_to host if one is specified).  That rsync will include --rsync-path="sudo rsync" if sudo is requested.  That parameter will make rsync execute sudo on the remote machine before executing the remote rsync.

This mean that sudo is run on the remote machine not on the controler.  However, it also means that the remote machine must implement passwordless sudo.  password-sudo would require some way to give the password to rsync and we don't have that capability yet.  This should reimplement the 1.9.4 behaviour.

You can see my testcases and the expected outcomes for them here: https://gist.github.com/abadger/0fc9e36a295979210698

As far as I can tell, the testcases show that sudo is now being correctly run on the remote machine, not the controller so I'm going to close this issue.

**Closed as completed by abadger** 2016-01-26 05:31 UTC
Labels: feature_idea

**Comment by jaxzin** [comment] 2016-08-12 16:59
@abadger Is there an issue open to track support for password-sudo?

**Comment by tima** [comment] 2016-08-13 02:00
@jaxzin: ansible/ansible#13099
