### ISSUE TITLE
wait_for: AttributeError: 'long' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible-modules-core#3742] opened 2016-05-25 19:11 UTC
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

```
wait_for
```
##### ANSIBLE VERSION

```
2.0.2.0
```
##### SUMMARY

`wait_for` fails 
##### STEPS TO REPRODUCE

```
- name: Wait for instance to come online (10 minute timeout)
  become: false
  local_action:
    module: wait_for
    host: "{{ ansible_ssh_host|default(inventory_hostname) }}"
    port: "{{ ansible_ssh_port|default(ssh_port|default(ansible_port|default(22))) }}"
    delay: 30
    timeout: 600
    state: started

```
##### ACTUAL RESULTS

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/2.0.2.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 122, in run
    res = self._execute()
  File "/usr/local/Cellar/ansible/2.0.2.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 389, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/usr/local/Cellar/ansible/2.0.2.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 585, in _get_connection
    if i.startswith('ansible_') and i.endswith('_interpreter'):
AttributeError: 'long' object has no attribute 'startswith'

fatal: [myhos]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by jctanner** [comment] 2016-05-26 13:21
I believe this was fixed by https://github.com/ansible/ansible/commit/fb7940fc50cc9f5dd5e794e6c8149f89084cfe05

**Comment by jctanner** [comment] 2016-05-26 13:30
@hryamzik to reproduce this, I had to add a fact with a numeric key ...

```
$ cat host_vars/el6host.yaml 
23: anewhope
```

**Comment by jctanner** [comment] 2016-05-26 14:10
Confirmed that this is fixed in 2.1 ...

```
v1.9.4-1:3
v1.9.5-0.1.rc1:3
v1.9.5-1:3
v1.9.6-0.1.rc1:3
v1.9.6-1:3
v2.0.0-0.6.rc1:2
v2.0.0-0.7.rc2:2
v2.0.0-0.8.rc3:2
v2.0.0-0.9.rc4:2
v2.0.0.0-1:2
v2.0.0.1-1:2
v2.0.0.2-1:2
v2.0.1.0-0.1.rc1:2
v2.0.1.0-0.2.rc2:2
v2.0.1.0-1:2
v2.0.2.0-0.1.rc1:2
v2.0.2.0-0.2.rc2:2
v2.0.2.0-0.3.rc3:2
v2.0.2.0-0.4.rc4:2
v2.0.2.0-1:2
v2.1.0.0-0.1.rc1:2
v2.1.0.0-0.2.rc2:0
v2.1.0.0-0.3.rc3:0
v2.1.0.0-0.4.rc4:0
v2.1.0.0-1:0
```

**Comment by jctanner** [comment] 2016-05-26 14:10
Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by jctanner** 2016-05-26 14:10 UTC
Labels: P2, bug_report

**Comment by hryamzik** [comment] 2016-05-26 14:12
@jctanner thanks, I'll give it a try.

**Comment by hryamzik** [comment] 2016-05-26 19:12
@jctanner your workaround doesn't work, it just changes `long` to `int` in the error message. =)

**Comment by hryamzik** [comment] 2016-05-26 19:18
Got fixed with `if isinstance(i, basestring):` in `task_executor.py`.

Checked out current dev code – looks fine there.
