### ISSUE TITLE
acl module changed behavior (default acl also adds user acl)

### ISSUE THREAD

**Issue by hloeffler** [ansible/ansible-modules-core#2598] opened 2015-12-01 07:00 UTC
Type: Bug

in ansible 2.0 the acl module wants to be smarter than me:

if i use:

```
 - acl: name=/testdir etype=user entity=test permissions="r" default=yes state=present
```

it also adds the acl "user:test:r--"

in 1.9.4 it only adds a new default acl

**Comment by hloeffler** [comment] 2015-12-01 07:02
https://github.com/ansible/ansible/issues/13291#issuecomment-160722851

**Comment by robynbergeron** [comment] 2015-12-01 17:56
[module: files/acl.py]

**Comment by robynbergeron** [comment] 2015-12-01 18:22
@hloeffler -- Thanks for submitting this bug report.

@astorije @bcoca -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by bcoca** [comment] 2015-12-08 19:44
fixed via merged #2649

**Comment by hloeffler** [comment] 2015-12-09 07:08
@bcoca no?

cat acl_fail.yml 

```
- hosts: localhost
  tasks:
    - acl: name=/tmp etype=user entity=man permissions="r" default=yes state=present
```

getfacl /tmp

on 1.9:

```
# file: tmp
# owner: root
# group: root
# flags: --t
user::rwx
group::rwx
other::rwx
default:user::rwx
default:user:man:r--
default:group::rwx
default:mask::rwx
default:other::rwx

```

on devel:

```
# file: tmp/
# owner: root
# group: root
# flags: --t
user::rwx
user:man:r--
group::rwx
mask::rwx
other::rwx
```

**Comment by quoing** [comment] 2015-12-09 07:24
@hloeffler 
Seems ok in my case, see test case below.. could you be more specific about platform you are runing on also share get/setfacl version.. (eg. getfacl -v).

Playbook:

```
- hosts: bruce
  vars:
    - mydir: "/tmp/abc"
  become: yes
  tasks:
    - debug: msg="[Test 8] hloeffler"
    - file: path={{ mydir }} state=directory
    - shell: getfacl {{ mydir }}
      register: out1
    - acl: name={{ mydir }} etype=user entity=www-data permissions="r" default=yes state=present
    - shell: getfacl {{ mydir }}
      register: out2
    - debug: var=out1.stdout_lines
    - debug: var=out2.stdout_lines
    - file: path={{ mydir }} state=absent
```

Output:

```
TASK [debug msg=[Test 8] hloeffler] ********************************************
ok: [bruce.mess.cz] => {
    "changed": false,
    "msg": "[Test 8] hloeffler"
}

TASK [file path={{ mydir }} state=directory] ***********************************
changed: [bruce.mess.cz] => {"changed": true, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/tmp/abc", "size": 4096, "state": "directory", "uid": 0}

TASK [command] *****************************************************************
changed: [bruce.mess.cz] => {"changed": true, "cmd": "getfacl /tmp/abc", "delta": "0:00:00.005478", "end": "2015-12-09 08:19:26.471748", "rc": 0, "start": "2015-12-09 08:19:26.466270", "stderr": "getfacl: Removing leading '/' from absolute path names", "stdout": "# file: tmp/abc\n# owner: root\n# group: root\nuser::rwx\ngroup::r-x\nother::r-x", "stdout_lines": ["# file: tmp/abc", "# owner: root", "# group: root", "user::rwx", "group::r-x", "other::r-x"], "warnings": []}

TASK [acl etype=user state=present name={{ mydir }} default=yes permissions=r entity=www-data] ***
changed: [bruce.mess.cz] => {"acl": ["user::rwx", "user:www-data:r--", "group::r-x", "mask::r-x", "other::r-x"], "changed": true, "msg": "user:www-data:r is present"}

TASK [command] *****************************************************************
changed: [bruce.mess.cz] => {"changed": true, "cmd": "getfacl /tmp/abc", "delta": "0:00:00.005464", "end": "2015-12-09 08:19:26.716700", "rc": 0, "start": "2015-12-09 08:19:26.711236", "stderr": "getfacl: Removing leading '/' from absolute path names", "stdout": "# file: tmp/abc\n# owner: root\n# group: root\nuser::rwx\ngroup::r-x\nother::r-x\ndefault:user::rwx\ndefault:user:www-data:r--\ndefault:group::r-x\ndefault:mask::r-x\ndefault:other::r-x", "stdout_lines": ["# file: tmp/abc", "# owner: root", "# group: root", "user::rwx", "group::r-x", "other::r-x", "default:user::rwx", "default:user:www-data:r--", "default:group::r-x", "default:mask::r-x", "default:other::r-x"], "warnings": []}

TASK [debug var=out1.stdout_lines] *********************************************
ok: [bruce.mess.cz] => {
    "changed": false,
    "out1.stdout_lines": [
        "# file: tmp/abc",
        "# owner: root",
        "# group: root",
        "user::rwx",
        "group::r-x",
        "other::r-x"
    ]
}

TASK [debug var=out2.stdout_lines] *********************************************
ok: [bruce.mess.cz] => {
    "changed": false,
    "out2.stdout_lines": [
        "# file: tmp/abc",
        "# owner: root",
        "# group: root",
        "user::rwx",
        "group::r-x",
        "other::r-x",
        "default:user::rwx",
        "default:user:www-data:r--",
        "default:group::r-x",
        "default:mask::r-x",
        "default:other::r-x"
    ]
}

TASK [file path={{ mydir }} state=absent] **************************************
changed: [bruce.mess.cz] => {"changed": true, "path": "/tmp/abc", "state": "absent"}
```

**Comment by hloeffler** [comment] 2015-12-09 07:30
@quoing 
Ubuntu 14.04.3 LTS

getfacl 2.2.52

ansible 2.1.0 (devel c1cec64aa8) last updated 2015/12/09 07:52:23 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 191347676e) last updated 2015/12/09 07:52:47 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD a10bdd6be9) last updated 2015/12/09 07:52:51 (GMT +200)

```
TASK [debug var=out1.stdout_lines] *********************************************
ok: [localhost] => {
    "changed": false, 
    "out1.stdout_lines": [
        "# file: tmp/abc", 
        "# owner: root", 
        "# group: root", 
        "user::rwx", 
        "group::r-x", 
        "other::r-x"
    ]
}

TASK [debug var=out2.stdout_lines] *********************************************
ok: [localhost] => {
    "changed": false, 
    "out2.stdout_lines": [
        "# file: tmp/abc", 
        "# owner: root", 
        "# group: root", 
        "user::rwx", 
        "user:www-data:r--", 
        "group::r-x", 
        "mask::r-x", 
        "other::r-x"
    ]
}

TASK [file path={{ mydir }} state=absent] **************************************
changed: [localhost]
```

**Comment by quoing** [comment] 2015-12-09 08:28
@hloeffler 

seems you are not on latest devel HEAD

```
# git reflog
f2b72e6 HEAD@{0}: clone: from https://github.com/ansible/ansible-modules-core
```

**Comment by hloeffler** [comment] 2015-12-09 08:45
@quoing 
i did a fresh
git clone
git checkout devel
git submodule update --init
. hacking/env-setup

and get:

ansible 2.1.0 (devel c1cec64aa8) last updated 2015/12/09 09:42:17 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 191347676e) last updated 2015/12/09 09:42:39 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD a10bdd6be9) last updated 2015/12/09 09:42:43 (GMT +200)

**Comment by quoing** [comment] 2015-12-09 09:47
@hloeffler 

git clone --recursive https://github.com/ansible/ansible.git ansible
cd ansible/lib/ansible/modules/core
git checkout devel

works for me

**Comment by hloeffler** [comment] 2015-12-09 09:51
@quoing 
thanks

```
ok: [localhost] => {
    "changed": false, 
    "out2.stdout_lines": [
        "# file: tmp/abc", 
        "# owner: root", 
        "# group: root", 
        "user::rwx", 
        "group::r-x", 
        "other::r-x", 
        "default:user::rwx", 
        "default:user:www-data:r--", 
        "default:group::r-x", 
        "default:mask::r-x", 
        "default:other::r-x"
    ]
}
```

**Comment by hloeffler** [comment] 2015-12-09 10:24
@quoing 
i still have playbooks that will change acls:

before: (no change with 1.9)

```
# file: var/log/mysql/mysql-slow.log
# owner: mysql
# group: adm
user::rw-
user:developer:r--
group::r-x          #effective:r--
mask::r--
other::---
```

after with 2.0:

```
# file: var/log/mysql/mysql-slow.log
# owner: mysql
# group: adm
user::rw-
user:developer:r--
group::r-x
mask::r-x
other::---
```

acl:

```
- acl: name={{ item.name }} entity={{ item.entity }} etype={{ item.etype }} permissions={{ item.permissions }} default={{ item.default }} state=present
  with_items:
    - { name: '/var/log/mysql/mysql-slow.log', default: 'no', entity: 'developer', etype: 'user', permissions: 'r--' }
```

**Comment by quoing** [comment] 2015-12-10 09:03
@bcoca @hloeffler 
Doesn't look like issue of setting of ACL in Ansible playbook. Effective permissions and mask is "calculated" by setfacl based on mask and posix permission. So it might differ.

There is currently no option to handle mask and I see it as enhancement of ACL module.

**Comment by jctanner** [comment] 2016-05-12 20:52
Testcase ...

```
- hosts: el6host:u1404
  user: root
  gather_facts: False
  tasks:
    - file: path=/testdir state=absent
    - file: path=/testdir state=directory
    - copy: content="foobar" dest=/testdir/foobar.txt
    - user: name=developer state=present
    #- acl: name=/testdir etype=user entity=test permissions="r" default=yes state=present
    - acl:
        name: "{{ item.name }}"
        entity: "{{ item.entity }}"
        etype: "{{ item.etype }}"
        permissions: "{{ item.permissions }}"
        default: "{{ item.default }}"
        state: present
      with_items:
        - name: '/testdir/foobar.txt'
          default: 'no'
          entity: 'developer'
          etype: 'user'
          permissions: 'r--'

    - shell: "getfacl /testdir/foobar.txt | egrep ^mask | cut -d\\: -f3"
      register: facl

    - debug: var=facl

    - fail:
      when: facl.stdout != 'r--'
```

Results ...

| version | rc |
| --- | --- |
| 0.0.1 | 127 |
| 0.0.2 | 127 |
| 0.01 | 127 |
| 0.3 | 127 |
| 0.3.1 | 127 |
| 0.4 | 127 |
| 0.4.1 | 127 |
| 0.5 | 127 |
| 0.6 | 1 |
| 0.7 | 1 |
| 0.7.1 | 1 |
| 0.7.2 | 1 |
| 0.8 | 1 |
| v0.9 | 1 |
| v1.0 | 1 |
| v1.1 | 1 |
| v1.2 | 1 |
| v1.2.1 | 1 |
| v1.2.2 | 1 |
| v1.2.3 | 1 |
| v1.3.0 | 1 |
| v1.3.1 | 1 |
| v1.3.2 | 1 |
| v1.3.3 | 1 |
| v1.3.4 | 1 |
| v1.4.0 | 2 |
| v1.4.1 | 2 |
| v1.4.2 | 2 |
| v1.4.3 | 2 |
| v1.4.4 | 2 |
| v1.4.5 | 2 |
| v1.5.0 | 0 |
| v1.5.1 | 0 |
| v1.5.2 | 0 |
| v1.5.3 | 0 |
| v1.5.4 | 0 |
| v1.5.5 | 0 |
| v1.6.0 | 0 |
| v1.6.1 | 0 |
| v1.6.10 | 0 |
| v1.6.2 | 0 |
| v1.6.3 | 0 |
| v1.6.4 | 0 |
| v1.6.5 | 0 |
| v1.6.6 | 0 |
| v1.6.7 | 0 |
| v1.6.8 | 0 |
| v1.6.9 | 0 |
| v1.7.0 | 0 |
| v1.7.1 | 0 |
| v1.7.2 | 0 |
| v1.8.0 | 0 |
| v1.8.1 | 0 |
| v1.8.2 | 0 |
| v1.8.3 | 0 |
| v1.8.4 | 0 |
| v1.9.0-0.1.rc1 | 0 |
| v1.9.0-0.2.rc2 | 0 |
| v1.9.0-1 | 0 |
| v1.9.0-2 | 0 |
| v1.9.0.1-1 | 0 |
| v1.9.1-0.1.rc1 | 0 |
| v1.9.1-0.2.rc2 | 0 |
| v1.9.1-0.3.rc3 | 0 |
| v1.9.1-0.4.rc4 | 0 |
| v1.9.1-1 | 0 |
| v1.9.2-0.1.rc1 | 0 |
| v1.9.2-0.2.rc2 | 0 |
| v1.9.2-1 | 0 |
| v1.9.3-0.1.rc1 | 0 |
| v1.9.3-0.2.rc2 | 0 |
| v1.9.3-0.3.rc3 | 0 |
| v1.9.3-1 | 0 |
| v1.9.4-0.1.rc1 | 0 |
| v1.9.4-0.2.rc2 | 0 |
| v1.9.4-0.3.rc3 | 0 |
| v1.9.4-1 | 0 |
| v1.9.5-0.1.rc1 | 0 |
| v1.9.5-1 | 0 |
| v1.9.6-0.1.rc1 | 0 |
| v1.9.6-1 | 0 |
| v2.0.0-0.6.rc1 | 0 |
| v2.0.0-0.7.rc2 | 0 |
| v2.0.0-0.8.rc3 | 0 |
| v2.0.0-0.9.rc4 | 0 |
| v2.0.0.0-1 | 0 |
| v2.0.0.1-1 | 0 |
| v2.0.0.2-1 | 0 |
| v2.0.1.0-0.1.rc1 | 0 |
| v2.0.1.0-0.2.rc2 | 0 |
| v2.0.1.0-1 | 0 |
| v2.0.2.0-0.1.rc1 | 0 |
| v2.0.2.0-0.2.rc2 | 0 |
| v2.0.2.0-0.3.rc3 | 0 |
| v2.0.2.0-0.4.rc4 | 0 |
| v2.0.2.0-1 | 0 |
| v2.1.0.0-0.1.rc1 | 0 |

**Comment by jctanner** [comment] 2016-05-12 20:59
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

Our reasons and evidence for this are:
- See test results above.

And we suggest that:
- Retest with a more current version of ansible and if the issue still occurs, please provide the complete ansible commands run with full -vvvv output. 
- If the testcase above doesn't cover the issue described, please also show what would need to change.

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by jctanner** 2016-05-12 20:59 UTC
Labels: P2, bug_report
