### ISSUE TITLE
ec2_vpc creates a new vpc if you change the resource_tags

### ISSUE THREAD

**Issue by davidecerri** [ansible/ansible-modules-core#3207] opened 2016-03-09 00:31 UTC
##### Issue Type:
- Bug Report
##### Plugin Name:

[ec2_vpc]
##### Ansible Version:

ansible 2.0.1.0
##### Ansible Configuration:

vanilla
##### Environment:

N/A
##### Summary:

changing the resource_tags causes ec_vpc to create a new vpc.
vpc should be identified by CIDR and region, so changing tags should be safe. 
##### Steps To Reproduce:

create a vpc using ec2_vpc
vpc_info:
  region: us-east-1 
  state: present
  cidr_block: "10.100.0.0/16"
  resource_tags:
    Environment: "test"
    Name: "test"
  internet_gateway: True

then run it again with a new tag:
vpc_info:
  region: us-east-1 
  state: present
  cidr_block: "10.100.0.0/16"
  resource_tags:
    Test_tag: "oopsie"
    Environment: "test"
    Name: "test"
  internet_gateway: True
##### Expected Results:

i would expect the original vpc to have a new tag.
##### Actual Results:

i get 2 vpc with the same CIDR, one with 2 tags and one with 3 tags.

**Comment by mscherer** [comment] 2016-03-17 22:29
Duplicate of #3194 ? (if so, can you close this issue ?)

**Closed as completed** 2016-03-18 15:54 UTC
Labels: bug_report
