### ISSUE TITLE
s3 module fails when overwrite=no and checksums are different 

### ISSUE THREAD

**Issue by pgehres** [ansible/ansible-modules-core#489] opened 2014-12-10 18:38 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9 (devel 3b80f63e22) last updated 2014/12/08 09:59:08 (GMT -700)
  lib/ansible/modules/core: (detached HEAD b766390ae2) last updated 2014/12/08 09:59:11 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 19e688b017) last updated 2014/12/08 09:59:14 (GMT -700)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/12/08 09:59:18 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/12/08 09:59:21 (GMT -700)
##### Environment:

Mac OSX (Yosemite) -> Centos 6.5
##### Summary:

We are using the s3 module to download artifacts for installation. Once we have installed something, we don't want to redownload the file causing ansible to reinstall. To accomplish this we use "overwrite: no" as part of the task.  
##### Steps To Reproduce:

Upload a file to s3. Use the s3 module to download the file. Change the file in s3. Run the task again with "overwrite: no"
##### Expected Results:

The task should display the warning that the checksums are different in the verbose output but should not change the file, succeed, and move on to the next task.  This behavior would match the behavior of the template and copy modules.
##### Actual Results:

The task fails with the message "msg: WARNING: Checksums do not match. Use overwrite parameter to force download."

**Comment by pgehres** [comment] 2014-12-10 18:44
@bcoca if there is agreement that this is a bug, I will submit a pull request. Looks to be a one-line change.

**Comment by bcoca** [comment] 2014-12-10 18:47
I have not reproduced the issue, but if it is as you describe, I agree, it is a bug. The task should be OK, with a warning if overwrite=no.

**Comment by ChadScott** [comment] 2015-01-29 22:16
Guys, this issue is completely hosing our environment. We've submitted a detailed description as well as a pull request to resolve it and nothing has happened in almost two months.

Can I respectfully ask for someone to reexamine this, please?

**Comment by ghost** [comment] 2015-02-15 19:38
+1

**Comment by abadger** [comment] 2015-03-11 00:53
Pull request is here: https://github.com/ansible/ansible-modules-core/pull/490

Looks like copy has a force parameter which seems to do the same thing as overwrite but it doesn't emit a warning.  template does not document the force parameter but it does have one and it operates in the same manner as copy.  So probably three bugs that need to be fixed there.

**Comment by abadger** [comment] 2015-03-11 15:29
@pgehres, @bcoca and others... I see in the code and see that there's also an overwrite check for uploading to s3 that's presently set to fail.  Should that also become a success if overwrite is set to False?

**Comment by abadger** [comment] 2015-03-12 16:34
I decided it should be a success as the transfer to the remote is actually what force does in copy and template (rather than the download).  Merged the PR and the additional change both to devel and to 1.9.  Feel free to test and open a new issue if there's any further problem.  Thanks!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by abadger** 2015-03-12 16:34 UTC
Labels: bug_report, cloud
