### ISSUE TITLE
Documentation error in gc_storage 

### ISSUE THREAD

**Issue by davidmweber** [ansible/ansible-modules-core#1256] opened 2015-05-05 16:25 UTC
The documentation calls for gcs_access_key and gcs_secret_key but the code is looking for gs_access_key and gs_secret_key. This caused me some head scratching. The documentation is also unclear as to what these entities are and how to obtain them. There is nothing in Google's GCS documentation that has these names. A hint on how to get the correct keys would be great

**Comment by bcoca** [comment] 2015-05-05 17:49
@erjohnso

**Comment by davidmweber** [comment] 2015-05-07 06:52
The documentation also indicates that GCS_SECRET_KEY and GCS_ACCESS_KEY can be environmental variables but neither the code or my tests show that this works.

**Comment by bogdanghervan** [comment] 2015-08-18 19:27
This is a duplicate of #733.

**Comment by bcoca** [comment] 2015-08-19 23:48
closing as dupe

**Closed as completed by bcoca** 2015-08-19 23:48 UTC
Labels: docs_report
