### ISSUE TITLE
ec2_asg: fails when there are no instances

### ISSUE THREAD

**Issue by bryanlarsen** [ansible/ansible-modules-core#2672] opened 2015-12-11 15:25 UTC
## Use case

we do auto-scale groups in pairs, one for spot pricing, one for full pricing.   Most times, one of the groups doesn't have any instances
## To reproduce

```
- ec2_asg: desired_capacity=0 replace_all_instances=yes ...
```

and run it twice.   Creating the auto scaling group will succeed, but updating it fails.   We don't actually use desired_capacity=0 in our playbook, but it's the easiest way to reproduce the problem.
## The error

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/blarsen/.ansible/tmp/ansible-tmp-1449847198.77-184523039425864/ec2_asg", line 2990, in <module>
    main()
  File "/home/blarsen/.ansible/tmp/ansible-tmp-1449847198.77-184523039425864/ec2_asg", line 2984, in main
    replace_changed, asg_properties=replace(connection, module)
  File "/home/blarsen/.ansible/tmp/ansible-tmp-1449847198.77-184523039425864/ec2_asg", line 2718, in replace
    instances = props['instances']
KeyError: 'instances'
```
## Workaround

put ec2_asg in the playbook twice.   The first with replace_all_instances set to no, the second with replace_all_instances set to yes, and use ignore_errors.
## Versions Tested

1.9.4 and 0d23b3df526875c8fc6edf94268f3aa850ec05f1

**Comment by jimi-c** [comment] 2016-02-07 21:13
This appears to be a duplicate of #2652, so closing in favor of that issue.

Thanks!

**Closed as completed** 2016-02-07 21:13 UTC
