### ISSUE TITLE
lineinfile: unexpected behaviour when insertbefore/insertafter doesn't match

### ISSUE THREAD

**Issue by cmock** [ansible/ansible-modules-core#279] opened 2014-11-05 19:38 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

N/A
##### Summary:

When using the insertbefore/insertafter arguments to lineinfile, and that regexp does not match, the line is not inserted into the file at all.
##### Steps To Reproduce:

`lineinfile: regexp="^edit" insertbefore="^before" line="edit foobar" state=present`
##### Expected Results:

The file should contain the line "edit foobar", whether a line "before" is present or not. Without the insertbefore/insertafter matching, I'd expect the added line to be added at the end of the file.
##### Actual Results:

The line "edit foobar" is only inserted when the line "before" is present. When it is absent, nothing happens.

The module code says in a comment

```
# Add it to the end of the file if requested or
# if insertafter=/insertbefore didn't match anything
# (so default behaviour is to add at the end)
```

and a few lines below

```
# Do nothing if insert* didn't match
```

Which is also what the code implements.

I consider the behaviour indicated in the first comment to be what I expect, and the current behaviour to be surprising.

**Comment by sterfield** [comment] 2015-08-03 21:30
Hi,

I'm sorry, but this is not the behavior I can see with Ansible 1.9.2

The current algorithm is:

1) line mentioned
Searching for "line".
- If line is found, then do nothing
- If line is not found, then add the line at the very end of the file (because if insertafter and insertbefore are not filled, then insertafter is forced to EOF).

2a) line mentioned and insertbefore=BOF
- If line is found, then do nothing
- If line is not found, then add the line at the beginning of the file

2b) line mentioned and insertbefore=BOF and regexp  = regexp2
- if line is found then do nothing
- if line is not found and regexp is found then change the "regexp2" line by "line" (insertbefore is ignored)
- if line is not found and regexp is not found, then line is added at the beginning of the file.

2c) line mentioned and insertbefore = regexp
- if line is found, then do nothing
- if line is not found, and insertbefore regexp is not found, then add the line at the end of the file
- If line is not found, and insertbefore regexp is found, then add the line before the 'insertbefore' line.

2d)  line mentioned and insertbefore = regexp and regexp = regexp2
- if line is found, then do nothing
- if line is not found and insertbefore regexp is found and regexp is found then change the "regepx2" line by "line"
- if line is not found and insertbefore regexp is found and regexp is not found, then insert "line" before "regexp" line
- if line is not found and insertbefore regexp is not found and regexp is found, then change "regexp2" by "line"
- if line is not found and insertbefore regexp is not found and regexp is not found, then add the line at the end of the file.

3a, 3b, 3c and 3d) same as 2 but with insertafter in spite of insertbefore
see relevant 2x) section.

In the case you are mentioning, if regexp match but insertbefore doesn't, then the line containing the regexp is modified with the content of "line". Insertbefore is totally ignored.

If you want, you can discuss the lineinfile behavior in the thread I've opened here : https://groups.google.com/forum/#!topic/ansible-project/riuUuT7LJ0I

Thanks,

**Comment by jctanner** [comment] 2016-04-28 01:04
Testcase used ....

```
$ cat inventory
localhost

$ cat site.yml
- hosts: localhost
  gather_facts: False
  tasks:
    - copy:
        content: "after\nbefore\n"
        dest: /tmp/withbefore.txt
    - copy:
        content: ""
        dest: /tmp/nobefore.txt
    - lineinfile:
        regexp: "^edit"
        insertbefore: "^before"
        line: "edit_foobar"
        state: present
        create: yes
        dest: "{{ item }}"
      with_items:
        - /tmp/nobefore.txt
        - /tmp/withbefore.txt

$ cat test.sh
#!/bin/bash

ansible-playbook -i inventory -c local -vvvv site.yml

echo "#### WITHBEFORE ###"
cat /tmp/withbefore.txt
echo "#### NOBEFORE ####"
cat /tmp/nobefore.txt

pcregrep -M "after\nedit_foobar\nbefore" /tmp/withbefore.txt >/dev/null
RC1=$?
pcregrep -M "edit_foobar\n" /tmp/nobefore.txt >/dev/null
RC2=$?

if [[ $RC1 == 0 ]] && [[ $RC2 == 0 ]]; then
    exit 0
else
    exit 1
fi
```

Results ...

```
v1.5.3:1
v1.5.4:1
v1.5.5:1
v1.6.0:1
v1.6.1:1
v1.6.10:1
v1.6.2:1
v1.6.3:1
v1.6.4:1
v1.6.5:1
v1.6.6:1
v1.6.7:1
v1.6.8:1
v1.6.9:1
v1.7.0:1
v1.7.1:1
v1.7.2:1
v1.8.0:1
v1.8.1:1
v1.8.2:1
v1.8.3:1
v1.8.4:1
v1.9.0-0.1.rc1:0
v1.9.0-0.2.rc2:0
v1.9.0-1:0
v1.9.0-2:0
v1.9.0.1-1:0
v1.9.1-0.1.rc1:0
v1.9.1-0.2.rc2:0
v1.9.1-0.3.rc3:0
v1.9.1-0.4.rc4:0
v1.9.1-1:0
v1.9.2-0.1.rc1:0
v1.9.2-0.2.rc2:0
v1.9.2-1:0
v1.9.3-0.1.rc1:0
v1.9.3-0.2.rc2:0
v1.9.3-0.3.rc3:0
v1.9.3-1:0
v1.9.4-0.1.rc1:0
v1.9.4-0.2.rc2:0
v1.9.4-0.3.rc3:0
v1.9.4-1:0
v1.9.5-0.1.rc1:0
v1.9.5-1:0
v1.9.6-0.1.rc1:0
v1.9.6-1:0
v2.0.0-0.6.rc1:0
v2.0.0-0.7.rc2:0
v2.0.0-0.8.rc3:0
v2.0.0-0.9.rc4:0
v2.0.0.0-1:0
v2.0.0.1-1:0
v2.0.0.2-1:0
v2.0.1.0-0.1.rc1:0
v2.0.1.0-0.2.rc2:0
v2.0.1.0-1:0
v2.0.2.0-0.1.rc1:0
v2.0.2.0-0.2.rc2:0
v2.0.2.0-0.3.rc3:0
v2.0.2.0-0.4.rc4:0
v2.0.2.0-1:0
v2.1.0.0-0.1.rc1:0
```

**Comment by jctanner** [comment] 2016-04-28 01:06
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

Our reasons and evidence for this are:
- Based on the test results in my previous comment, the reported behavior existed until 1.9.0-0.1.rc1, and has been corrected since that release.

And we suggest that:
- Update to a version of ansible that is at least 1.9.0 or higher, but preferably a current release.

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by jctanner** 2016-04-28 01:06 UTC
Labels: P2, bug_report
