### ISSUE TITLE
copy/template modules leave source in remote_tmp

### ISSUE THREAD

**Issue by visit1985** [ansible/ansible-modules-core#3572] opened 2016-04-29 15:13 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

```
copy
template
```
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
none
```
##### OS / ENVIRONMENT

```
CentOS Linux release 7.2.1511 (Core)
```
##### SUMMARY

copy and template module leave `$HOME/.ansible/tmp/ansible-tmp-1461941904.93-114576180700549/source` after successful execution.

It's conspicuous, that there are two different temp folders are used, while only the later one is deleted.

This worked in 1.9.4.
##### STEPS TO REPRODUCE

```
~ $ echo 'This is a test!' > a.out
~ $ ansible localhost -m copy -a "src=a.out dest=/tmp/b.out" -vvvv | grep PUT
127.0.0.1 PUT /tmp/tmpn5lAfb TO $HOME/.ansible/tmp/ansible-tmp-1461941904.93-114576180700549/source
127.0.0.1 PUT /tmp/tmpeDN0Wj TO $HOME/.ansible/tmp/ansible-tmp-1461941904.96-17498317945463/copy
~ $ rm a.out /tmp/b.out
~ $ cat $HOME/.ansible/tmp/ansible-tmp-1461941904.93-114576180700549/source
This is a test!
```

**Comment by bcoca** [comment] 2016-04-29 15:55
dupe of already fixed http://github.com/ansible/ansible/issues/14917

**Closed as completed by bcoca** 2016-04-29 15:55 UTC
Labels: bug_report

**Comment by visit1985** [comment] 2016-04-29 15:58
@bcoca wrong reference?

**Comment by visit1985** [comment] 2016-04-29 21:24
@bcoca thanks!
