### ISSUE TITLE
unarchive: "creates" parameter ignored

### ISSUE THREAD

**Issue by fdutheil** [ansible/ansible-modules-core#546] opened 2014-12-19 09:22 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.1
##### Environment:

Ubuntu 14.04 as master for CentOS 6.5
##### Summary:

In the unarchive module, I want the "creates" parameter to do as documented: "a filename, when it already exists, this step will not be run. (added in Ansible 1.6)" So that the module doesn't report a change when the content is already present
##### Steps To Reproduce:

```
  tasks:
    - name: extract some files
      unarchive:
       src: mytar.tar.gz
       dest: /opt/
       creates: "/opt/directory_in_mytar/file_in_mytar.thing"
    - name: fixing unix permissions
      file:
        path: "/opt/directory_in_mytar"
        owner: "apache"
        group: "apache"
        mode: "u=rwX,g=rX,o=rX"
        recurse: yes
        state: directory
```
##### Expected Results:

No "changed" stated and no extraction of the archive if the file is present on the remote system.
##### Actual Results:

Unarchive module is always executed, never skipped/stating "OK".

**Comment by jnakatsui** [comment] 2014-12-24 23:57
+1

Here is a Travis build if it helps. It's failing the idempotentency check.

https://travis-ci.org/jnakatsui/ansible-role-gogs/builds/45063051

**Comment by sysadmin75** [comment] 2014-12-27 20:58
I wasn't able to reproduce this issue. I use the example given and in my tests the unarchive is skipped when creates= is specified and it exists.

**Comment by fdutheil** [comment] 2014-12-29 15:54
OK, so i went deeper on the reproducing phase following @sysadmin75 feedback... 
I missed something I always do after extracting an archive: correcting unix permissions.

This step seems to alter the logic of the "creates": that looks more like a "exists_and_not_altered" or something the second time it must be evaluated. Which is totally not what I want.
Maybe 2 differents keywords/statements are needed there: a simple "creates" and an aditional "unaltered".

Anyway, as this, it's really misleading or unwanted.

**Comment by jnakatsui** [comment] 2014-12-31 18:40
@fdutheil I have removed specifying permissions in the build but the idempotency check indicates this is still failing.

Are the steps to reproduce accurate except for removing the permission changes? (i.e. owner/group/mode)

https://travis-ci.org/jnakatsui/ansible-role-gogs/builds/45565984

**Comment by fdutheil** [comment] 2015-01-12 10:22
@jnakatsui: yes, i did create the tar.gz manually containing only "directory_in_mytar/file_in_mytar.thing":

```
$ tar -ztf mytar.tar.gz 
directory_in_mytar/
directory_in_mytar/file_in_mytar.thing
```

2 consecutive calls with owner/mode task gives always a changed status:

```
$ ansible-playbook test.yml -i hosts-staging -e "hosts=webserver-qa-1"

PLAY [test] ******************************************************************* 

TASK: [extract some files] **************************************************** 
changed: [webserver-qa-1]

TASK: [fixing unix permissions] *********************************************** 
changed: [webserver-qa-1]

PLAY RECAP ******************************************************************** 
webserver-qa-1             : ok=2    changed=2    unreachable=0    failed=0   

$ ansible-playbook test.yml -i hosts-staging -e "hosts=webserver-qa-1"

PLAY [test] ******************************************************************* 

TASK: [extract some files] **************************************************** 
changed: [webserver-qa-1]

TASK: [fixing unix permissions] *********************************************** 
changed: [webserver-qa-1]

PLAY RECAP ******************************************************************** 
webserver-qa-1             : ok=2    changed=2    unreachable=0    failed=0   
```

If I remove the unix permission task:

```
$ ansible-playbook test.yml -i hosts-staging -e "hosts=webserver-qa-1"

PLAY [test] ******************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [webserver-qa-1]

TASK: [extract some files] **************************************************** 
changed: [webserver-qa-1]

PLAY RECAP ******************************************************************** 
webserver-qa-1             : ok=2    changed=1    unreachable=0    failed=0   

$ ansible-playbook test.yml -i hosts-staging -e "hosts=webserver-qa-1"

PLAY [test] ******************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [webserver-qa-1]

TASK: [extract some files] **************************************************** 
ok: [webserver-qa-1]

PLAY RECAP ******************************************************************** 
webserver-qa-1             : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by abadger** [comment] 2015-01-13 17:39
I think you've identified two separate issues here.  I'm about to commit some code that should fix the problem with creates= but the problem with changing permissions remains.  I think that the code that checks permissions is doing the right thing technically but it would be nice for people to be able to set permissions, owner, and group in a way that didn't cause a unarchive to repeat work and report changed.

Once creates is fixed, you'll at least be able to work around that problem by specifying creates=.

Given that, I think I'll mention the problem with specifying owner and group in a separate task in https://github.com/ansible/ansible-modules-core/issues/234 and work on any potential fixes there.

**Comment by abadger** [comment] 2015-01-13 17:45
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by abadger** 2015-01-13 17:45 UTC
Labels: P2, bug_report
