### ISSUE TITLE
mysql_user module cannot drop multiple users without hostname

### ISSUE THREAD

**Issue by teemule11** [ansible/ansible-modules-core#728] opened 2015-01-30 14:58 UTC
##### Summary:

It is not possible to DROP multiple users of the same username but with different hosts using the mysql_user module, even though the docs attached to this module say so. The Test Case covering the removal of users does not reflect upon this problem.
##### Steps To Reproduce:

I am reporting a discrepancy between ansible docs and the real behavior in mysql_user module. My plan was to remove all occurrences of a user in the mysql users table. 

Ansible user docs here: (http://docs.ansible.com/mysql_user_module.html) show  an example stating that it is possible to delete a mysql user completely, disregarding the host the user is tied to:

```
  # Ensure no user named 'sally' exists, also passing in the auth credentials.
  - mysql_user: login_user=root login_password=123456 name=sally state=absent
```

This does not work, though. I rebuilt the test that covers this function, which can be found here: ansible/test/integration/roles/test_mysql_user/tasks/remove_user.yml

My own code is as follows:

```
- name: create user
  mysql_user: name=bob host='myhost' password=222 state="present" login_user=root login_password=123

- name: remove mysql user
  mysql_user: name=bob password=222 state=absent login_user=root login_password=123
  register: result

# test as found in ansible/test/integration/roles/test_mysql_user/tasks/remove_user.yml
- name: assert output message mysql user was removed {{state}}
  assert: { that: "result.changed == true" }
```

It will fail to delete the user 'bob@myhost'. If you add "host=myhost" to the remove action, everything works fine.

The mysql log executing this code will show:

```
               50 Query     CREATE USER 'bob'@'myhost' IDENTIFIED BY PASSWORD '*899ECD04E40F745BD52A4C552BE4A818AC65FAF8'
               50 Quit
               51 Connect   root@localhost on mysql
               51 Query     set autocommit=0
               51 Query     SELECT count(*) FROM user WHERE user = 'bob' AND host = 'localhost'
               51 Quit
```

This corresponds exactly to what is happening in the mysql module, located at: ansible-modules-core/database/mysql/mysql_user.py; lines 510 and following. Since a default for hostname has been set (see line 444), the docs example which omits the hostname cannot work - the host parameter will always be set to "localhost".
##### Suggested resolution

There is no easy fix to produce the result I desired - even mysql itself does not offer a way to delete a user for multiple hosts with one command. For now I would propose adjusting the docs and fixing the test case in ansible/test/integration/roles/test_mysql_user/tasks/remove_user.yml, which obviously does not catch this misbehavior.

**Comment by Jmainguy** [comment] 2015-11-11 04:50
@teemule11 @bcoca Would yall rather it remove all instances of that user, if host= is excluded, or should we leave it at the default host=localhost if omitted and change the docs? I could go either way.

**Comment by teemule11** [comment] 2015-11-11 07:43
Jonathan,

I would prefer having all instances of that user being removed; theres a clear usecase in zeroing out all databases for a fresh start on installation or when purging a user from a database.

Thanks for picking this item up!

Torsten

**Comment by tersmitten** [comment] 2015-11-11 09:28
Is #2333 related?

**Comment by Jmainguy** [comment] 2015-11-11 17:44
@teemule11 @tersmitten Yeah #2333 Looks like it will handle this with its hosts_all function.

@leehuk can you make hosts_all default to true IF host is not passed and state=other than present?

That would fix this bug.

**Comment by leehuk** [comment] 2015-11-12 11:16
@Jmainguy @teemule11 I agree hosts_all would be a sensible default, but I'm worried making it default now could cause a regression for someone.  As its just the example thats wrong and the options documentation correctly states the host default is 'localhost', if someone has a playbook where they rely on host defaulting to 'localhost' (either for a user removal or a GRANT change) it could be an unexpected behaviour change for them for that it suddenly applies to all user entries with that name.

#2333 already fixes the example above to show it only removes 'sally'@'localhost' and then adds a separate example with hosts_all to show clearing all hosts, so it does resolve this bug as-is and I'm wondering whether its better just to leave it at that.

I'm happy to swap the default over to hosts_all if thats what everyone wants, its just as this is my first PR here as an outsider I dont want to break anything!

Cheers,

**Comment by teemule11** [comment] 2015-11-13 08:53
@leehuk I agree with you not to make hosts_all the default, good point. To me the only thing of importance is that the module provides a way to delete databases from all hosts; defaulting to all hosts is not necessary and could indeed break bc. The fix in #2333 is perfectly fine with me.

**Comment by Jmainguy** [comment] 2016-01-05 20:10
@teemule11 Since #2333 got merged, can this be closed?

**Comment by teemule11** [comment] 2016-01-07 08:03
Definately, thanks Jonathan for your support!

**Comment by Jmainguy** [comment] 2016-02-23 15:45
@bcoca this can be closed per above ^^

**Closed as completed** 2016-02-23 15:51 UTC
Labels: bug_report
