### ISSUE TITLE
Error with yum module on CentOS 7.0

### ISSUE THREAD

**Issue by bwainstock** [ansible/ansible-modules-core#2828] opened 2016-01-17 18:54 UTC
##### Issue Type

Bug Report
##### Ansible Version

ansible 1.9.4
  configured module search path = None
##### Ansible Configuration

Stock config on CentOS 7.2.1511
##### Environment

Server and host: 

```
[tigren@admin ~]$ uname -a
Linux admin.internal.lab 3.10.0-327.4.4.el7.x86_64 #1 SMP Tue Jan 5 16:07:00 UTC 2016 x86_64     x86_64 x86_64 GNU/Linux
[tigren@admin ~]$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
```
##### Summary:

Yum module throws error when checking state of package
##### Steps to Reproduce

Run basic ad-hoc check against host

```
ansible host -m yum -a "name=iftop state=latest" -b
```
##### Expected Results:

```
127.0.0.1 | success >> {
"changed": false, 
"msg": "", 
"rc": 0, 
"results": [
    "All packages providing iftop are up to date", 
    ""
]
}
```
##### Actual Results

```
127.0.0.1 | FAILED >> {
"cmd": "/usr/bin/repoquery --show-duplicates --plugins --quiet -q '--disablerepo=*' --pkgnarrow=installed --qf '%{name}-%{version}-%{release}.%{arch}' iftop", 
"failed": true, 
"msg": "[Errno 8] Exec format error", 
"rc": 8
}
```

**Comment by abadger** [comment] 2016-02-08 17:24
Not seeing this locally and "Exec format error" is pretty strange.  It means that python is attempting to run something that isn't executable on that machine.  Can you log into the remote machine and verify that the bash (provides /bn/sh) and yum-utils (provides repoquery) packages are okay?

```
$ rpm -qf /bin/sh
[Should tell you the bash package]
$ rpm -qf /usr/bin/repoquery
[Should tell you yum-utils]
$ rpm -V yum-utils bash
```

Also you can try running the repoquery command that is in the failed results and see if that works.

**Comment by abadger** [comment] 2016-03-20 14:18
Closing for lack of information.  From the error message, this unlikely to have been caused by code within anislbe itself.

**Closed as completed by abadger** 2016-03-20 14:18 UTC
