### ISSUE TITLE
mysql_db fails when login_port value in unquoted

### ISSUE THREAD

**Issue by mykola42** [ansible/ansible-modules-core#818] opened 2015-02-19 01:47 UTC
mysql_db module works well when login_port value is quoted (login_port: "3306"), but it fails when the value is unquoted (login_port: 3306):

```
File "/Users/user/.ansible/tmp/ansible-tmp-1424309772.84-207399355587003/mysql_db", line 131, in db_dump
    cmd += " --host=%s --port=%s" % (pipes.quote(host), pipes.quote(port))
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pipes.py", line 269, in quote
    for c in file:
TypeError: 'int' object is not iterable

FATAL: all hosts have already failed -- aborting
```

**Comment by Jmainguy** [comment] 2015-02-19 20:58
@mykola42 Can you provide some more details on how you produced this error. I just tried on latest devel branch and could not reproduce.

```
[root@phy01 tmp]# ansible localhost -m mysql_db -a "name=yarg login_port=3306"
localhost | success >> {
    "changed": true,
    "db": "yarg"
}

[root@phy01 tmp]# ansible localhost -m mysql_db -a "name=yarg login_port=3306"
localhost | success >> {
    "changed": false,
    "db": "yarg"
}

[root@phy01 tmp]# ansible localhost -m mysql_db -a "name=yarg login_port='3306'"
localhost | success >> {
    "changed": false,
    "db": "yarg"
}
```

**Comment by mykola42** [comment] 2015-02-19 21:24
@Jmainguy I'm actually using mysql_db module in my playbook:

```
---
- name: Test mysql_db module
  hosts: all
  gather_facts: False
  connection: local
  tasks:
  - name: Backup MySQL
    mysql_db:
      login_host: "127.0.0.1"
      login_port: "3306"
      login_user: "root"
      login_password: "root"
      state: "dump"
      name: "test"
      target: "~/Downloads/temp/test.sql"
```

And it works, because login_port value was quoted:

```
$ ansible-playbook -i inventory/mysql_servers backup_mysql.yml

PLAY [Test mysql_db module] *************************************************** 

TASK: [Backup MySQL] ********************************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                 : ok=1    changed=1    unreachable=0    failed=0   
```

And it fails when I have login_port value unquoted (this is the only one difference):

```
---
- name: Test mysql_db module
  hosts: all
  gather_facts: False
  connection: local
  tasks:
  - name: Backup MySQL
    mysql_db:
      login_host: "127.0.0.1"
      login_port: 3306
      login_user: "root"
      login_password: "root"
      state: "dump"
      name: "test"
      target: "~/Downloads/temp/test.sql"
```

The output is:

```
$ ansible-playbook -i inventory/mysql_servers backup_mysql.yml

PLAY [Test mysql_db module] *************************************************** 

TASK: [Backup MySQL] ********************************************************** 
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/mykola/.ansible/tmp/ansible-tmp-1424380664.74-318954798701/mysql_db", line 2088, in <module>
    main()
  File "/Users/mykola/.ansible/tmp/ansible-tmp-1424380664.74-318954798701/mysql_db", line 340, in main
    socket=module.params['login_unix_socket'])
  File "/Users/mykola/.ansible/tmp/ansible-tmp-1424380664.74-318954798701/mysql_db", line 131, in db_dump
    cmd += " --host=%s --port=%s" % (pipes.quote(host), pipes.quote(port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pipes.py", line 269, in quote
    for c in file:
TypeError: 'int' object is not iterable

failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/mykola/.ansible/tmp/ansible-tmp-1424380664.74-219871789838659/mysql_db", line 2088, in <module>
    main()
  File "/Users/mykola/.ansible/tmp/ansible-tmp-1424380664.74-219871789838659/mysql_db", line 340, in main
    socket=module.params['login_unix_socket'])
  File "/Users/mykola/.ansible/tmp/ansible-tmp-1424380664.74-219871789838659/mysql_db", line 131, in db_dump
    cmd += " --host=%s --port=%s" % (pipes.quote(host), pipes.quote(port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pipes.py", line 269, in quote
    for c in file:
TypeError: 'int' object is not iterable

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 

localhost                 : ok=0    changed=0    unreachable=0    failed=1   
```

My configuration:
Mac OS X 10.10.2
$ ansible --version
ansible 1.8.3
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)

**Comment by abadger** [comment] 2015-03-03 22:27
@mykola42 could you give that commit a try?  (at least the mysql_db.py portion which is where you're having your issue).  I think it will work but it never hurts to have a little testing :-)

**Comment by abadger** [comment] 2015-03-05 02:58
Merged pr.  I think that should fix things for you.  If not, please open a new ticket and I'll take a look.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed** 2015-03-05 02:57 UTC
Labels: P2, bug_report
