### ISSUE TITLE
docker login fails in docker-py version check: fatal: [172.20.1.12]: FAILED! => {"changed": false, "failed": true, "msg": "Error: docker-py version is 1.10.1. Minimum version required is 1.7.0."}

### ISSUE THREAD

**Issue by pmoosh** [ansible/ansible-modules-core#4770] opened 2016-09-10 01:08 UTC
Done
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker
docker-login
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

Tower 3.0
##### OS / ENVIRONMENT

centos 3.10.0-327.10.1.el7.x86_64
##### SUMMARY

docker-login checks docker-py version and fails
fatal: [172.20.1.12]: FAILED! => {"changed": false, "failed": true, "msg": "Error: docker-py version is 1.10.1. Minimum version required is 1.7.0."}
##### STEPS TO REPRODUCE

create a playbook that uses docker login.
Install the newest docker-py

```

```

##### EXPECTED RESULTS

That I am able to login to the docker hub
##### ACTUAL RESULTS

fatal: [172.20.1.12]: FAILED! => {"changed": false, "failed": true, "msg": "Error: docker-py version is 1.10.1. Minimum version required is 1.7.0."}

```

```

**Comment by srstsavage** [comment] 2016-09-10 01:40
Yes. This is very bad.

**Comment by srstsavage** [comment] 2016-09-10 01:49
The problem is actually in the Ansible core project, not here.

https://github.com/ansible/ansible/issues/17495

**Comment by chouseknecht** [comment] 2016-09-10 08:16
This is fixed in latest _devel_ branch by https://github.com/ansible/ansible/commit/1684c2da5d0daa4e3a23773c77244e5c0cec1e66

**Closed as completed by chouseknecht** 2016-09-10 08:16 UTC
