### ISSUE TITLE
cloud/docker: creation of containers not possible because of "Could not convert 0 to integer" exception

### ISSUE THREAD

**Issue by berendt** [ansible/ansible-modules-core#3078] opened 2016-02-19 20:53 UTC
##### Issue Type:
- Bug Report
##### Plugin Name:

cloud/docker
##### Ansible Version:

```
ansible 2.1.0
```
##### Environment:

Fedora 23
##### Summary:

Trying to create a Docker container fails with the following exception:

```
FAILED! => {"changed": false, "failed": true, "msg": "Could not convert 0 to integer"}
```

Issue is in method `_human_to_bytes` (https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker.py#L531-L545).

Explicitly setting `memory_limit` parameter does not solve the issue. 
##### Steps To Reproduce:

```
- name: start a hello world container
  docker:
    name: container
    image: hello-world
```
##### Expected Results:

A running container.
##### Actual Results:

```
FAILED! => {"changed": false, "failed": true, "msg": "Could not convert 0 to integer"}
```

**Comment by cluetjen** [comment] 2016-02-19 21:49
same issue here on Ubuntu 14.04 (clean install) with docker host from packages and ansible devel.

**Comment by berendt** [comment] 2016-02-19 22:29
I tested on Ubuntu 15.10 with `docker-py (1.7.0)` (installed with pip). But it has not worked with the `python-docker` package provided by Ubuntu, too.

**Comment by CaptTofu** [comment] 2016-02-24 16:54
I have the same error. Docker-py 1.8 dev and Ansible 2.1.0

Just tested with Docker-py 1.8 dev and Ansible 2.0.1.0 and it works.

**Comment by kamsz** [comment] 2016-02-26 13:27
@kaczynskid pushed a fix that works :+1: :)

**Comment by jmatsushita** [comment] 2016-02-28 21:20
@kaczynskid Thanks! Your fix work for me!

**Comment by basnijholt** [comment] 2016-03-01 20:48
Having same issue on Centos 7, Ansible 2.1.0, and pip `docker-py`.

**Comment by lerenn** [comment] 2016-03-04 15:09
Same issue too (Fedora 23 and Ansible 2.1.0).

**Comment by qwding** [comment] 2016-03-11 04:10
Same issue on Ubuntu 14.04,Ansible 2.1.0

**Comment by puneetjindal** [comment] 2016-03-20 09:44
PKMIL if the issue is resolved. I am trying to start the container centos:7 docker image with ansible 1.9

**Comment by puneetjindal** [comment] 2016-03-20 13:17
@CaptTofu : Can you please share how this problem resolved. Here my piece of code in my tasks file

### ```
- name: Install centos latest docker
  docker:
    name: centos
    image: centos
    state: present
- name: application service
  docker:
    image: centos:7
    name: lab
    state: reloaded

```
```

**Comment by MikeVL** [comment] 2016-03-22 18:29
I have some error if i set memory_limit via jinja variable:

```
- name: run uwsgi docker container
  docker:
    name: "uwsgi-{{ item.key|replace('_', '-') }}"
    image: "{{ django_container.image }}"
    pull: missing
    expose:
      - "{{ django_container.uwsgi_socket }}"
    ports:
      - "{{ item.value.port }}:{{ django_container.uwsgi_socket }}"
    volumes:
      - "{{ django_container.django_settings }}:/etc/django.conf.py:ro"
      - "/mnt/media:/mnt/media:rw"
    env: "{{ django_container.environment|combine(item.value.get('environment', {})) }}"
    memory_limit: "{{ item.value.get('memory_limit', '0') }}"
    restart_policy: always
    restart_policy_retry: 10
    state: reloaded
    command: "uwsgi {{ item.value.config_name }}"
  with_dict: "{{ uwsgi_backends }}"
```

```
failed: [django1.stack.local] => (item={'value': {u'environment': {u'STATIC_URL': u'/static/'}, u'config_name': u'default_site', u'port': 9104, u'hosts_group': u'uwsgi_backends_ajax'}, 'key': u'ajax'}) => {"failed": true, "item": {"key": "ajax", "value": {"config_name": "default_site", "environment": {"STATIC_URL": "/static/"}, "hosts_group": "uwsgi_backends_ajax", "port": 9104}}, "msg": "Could not convert 0 to integer"}
```

**Comment by ThomasSteinbach** [comment] 2016-03-24 19:33
This issue is not just a bug, it is a BLOCKER. Currently you can't start Docker containers with ansible/devel. Simply try to run any container like

```
- docker:
    name: myjenkins
    image: jenkins
```

and you will run into the `Could not convert 0 to integer` error. I propose to care about this issue before releasing a new version of Ansible.

**Comment by MikeVL** [comment] 2016-03-24 22:00
My config works fine without section:

`memory_limit: "{{ item.value.get('memory_limit', '0') }}"`

ansible version 2.0.1.0

**Comment by IlyaSemenov** [comment] 2016-03-25 05:19
@puneetjindal To temporarily fix the issue run this on the machine that runs ansible (not the target machine):

```
curl https://github.com/kaczynskid/ansible-modules-core/commit/46970d6d7add50780e8cedb5067ae5d29a763141.patch | patch /usr/local/Cellar/ansible//HEAD/libexec/lib/python2.7/site-packages/ansible/modules/core/cloud/docker/docker.py
```

Of course, adjust the path if you're not using Mac/Homebrew, do the backups, etc.

**Comment by jordy25519** [comment] 2016-03-31 21:23
@IlyaSemenov Your fix has worked successfully for me on Ubuntu 14.04
Path to patch file was `<repo_root_dir>/lib/ansible/modules/core/cloud/docker/docker.py`

**Comment by WinstonSureChill** [comment] 2016-04-13 11:52
+1

**Comment by ThomasSteinbach** [comment] 2016-04-19 23:31
My PR #3491 should fix the issue. I hope the next ansible pip package will include this fix.

**Closed as completed** 2016-04-21 11:28 UTC
Labels: bug_report

**Comment by scalolli** [comment] 2016-12-15 14:54
We have upgraded to a newer version of ansible and this seems to have started failing again. Any help would be appreciated
