### ISSUE TITLE
service module enable/disable does not work properly with sysv init scripts

### ISSUE THREAD

**Issue by MikeN123** [ansible/ansible-modules-core#1387] opened 2015-05-21 08:20 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.1
  configured module search path = None
##### Ansible Configuration:

Nothing.
##### Environment:

Mac OS X client running against a Debian 8.0 (jessie) host.
##### Summary:

The service module uses `systemctl is-enabled` to check service state on a systemd enabled system, which does not work for sysv services (at least not on Debian). There is also a bug report at Debian for this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=751638

I believe the actual bug is in Debian, but hopefully a workaround can be provided by Ansible.
##### Steps To Reproduce:

Try to enable some sysv-only init script on a Debian jessie system:

```
    - name: auto-start my-service
      service: name=my-service enabled=yes
```
##### Expected Results:

The first time it should report `changed = True`, and it should report `changed = False` on further invocations.
##### Actual Results:

Always reports `changed = True`.

**Comment by bcoca** [comment] 2015-06-26 23:39
closing this as duplicate of #915

**Closed as completed by bcoca** 2015-06-26 23:39 UTC
Labels: bug_report
