### ISSUE TITLE
Better handling for ssh restart

### ISSUE THREAD

**Issue by larry-s** [ansible/ansible-modules-core#1533] opened 2015-06-17 02:30 UTC
**Issue Type:** Feature request

**Ansible Version:** 
ansible 1.9.1
no configuration changes

**Environment:**
Ubuntu 14.04.02

**Summary:**
Restarting ssh is an essential operation as part of updating security settings when setting up a machine. The naive approach using the service module fails. This needs to be supported better. Some suggections on how to do this are:
- transparent - in the service module detect that ssh is being restarted and handle this specially
- documentation - in the documentation for the service module add an example of how to restart ssh
- separate module - add a separate core module for restarting ssh

**Steps To Reproduce:**
This fails:

```
- name: Restart SSH
  service: name=ssh state=restarted
```

This is the method recommended by support:

```
- name: Restart SSH
  shell: sleep 3; /etc/init.d/sshd restart
  async: 1
  poll: 0
```

**Comment by bcoca** [comment] 2015-06-17 18:01
closing as dupe of #1298

**Closed as completed by bcoca** 2015-06-17 18:01 UTC
Labels: feature_idea
