### ISSUE TITLE
EC2 module spot-pricing broken in 1.8.*

### ISSUE THREAD

**Issue by josephtate** [ansible/ansible-modules-core#423] opened 2014-12-02 08:58 UTC
##### Issue Type:

Regression
##### Ansible Version:

1.8.2
##### Environment:

N/A
##### Summary:

Commit 7f11c3d7cc9b4b71d72ad6a59e2b7aa22ecf93cf broke ec2 spot instance launching after 1.7.2. I'll work on a pull request to fix.
##### Steps To Reproduce:

```
    - name: Launch EC2 instances
      register: ec2
      local_action:
        module: ec2
        keypair: "{{ssh_key}}"
        instance_type: "{{instance_type}}"
        spot_price: "{{spot_price}}"
        count: 1
        group: "{{security_group | default('ZZ9-Benchmark-Group')}}"
        image: "{{ami}}"
        kernel: "{{kernel}}"
        instance_tags: { Name: "{{instance_name}}" }
        region: us-west-2
        wait: true
        vpc_subnet_id: "{{vpc_subnet| default(None)}}"
        assign_public_ip: "{{ 'on' if vpc_subnet|default(None) else 'off'}}"
        zone: us-west-2c
        volumes:
          - device_name: /dev/sda1
            volume_size: "{{ebs_vol_size}}"
            device_type: gp2
            delete_on_termination: true
          - device_name: /dev/xvdb
            ephemeral: ephemeral0
          - device_name: /dev/xvdc
            ephemeral: ephemeral1
          - device_name: /dev/xvdd
            ephemeral: ephemeral2
          - device_name: /dev/xvde
            ephemeral: ephemeral3
```
##### Expected Results:

The task should complete successfully instead of failing with a traceback.
##### Actual Results:

```
TASK: [Launch EC2 instances] ************************************************** 
<127.0.0.1> REMOTE_MODULE ec2 region=us-west-2 group=vpc-scratch-system,vpc-crunchapp-web-server assign_public_ip=on keypair='Jenkins Home Key' instance_type=r3.xlarge vpc_subnet_id=subnet-e3ac82a5 image=ami-3daad70d zone=us-west-2c spot_price=0.35 kernel=''
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1417507235.39-63284618195147 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1417507235.39-63284618195147 && echo $HOME/.ansible/tmp/ansible-tmp-1417507235.39-63284618195147']
<127.0.0.1> PUT /tmp/tmp2RXzHC TO /var/lib/jenkins/.ansible/tmp/ansible-tmp-1417507235.39-63284618195147/ec2
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /var/lib/jenkins/.ansible/tmp/ansible-tmp-1417507235.39-63284618195147/ec2; rm -rf /var/lib/jenkins/.ansible/tmp/ansible-tmp-1417507235.39-63284618195147/ >/dev/null 2>&1']
failed: [localhost -> 127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1417507235.39-63284618195147/ec2", line 2962, in <module>
    main()
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1417507235.39-63284618195147/ec2", line 1194, in main
    (instance_dict_array, new_instance_ids, changed) = create_instances(module, ec2)
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1417507235.39-63284618195147/ec2", line 932, in create_instances
    terminated_instances = [ str(instance.id) for instance in res.instances
AttributeError: 'ResultSet' object has no attribute 'instances'
```

**Comment by alexclifford** [comment] 2014-12-02 21:51
Were changes at this time also the cause for #396?

**Comment by josephtate** [comment] 2014-12-03 05:27
@alexclifford I don't believe they are related. I didn't bisect, just used git blame to figure out which changeset was at fault.

**Comment by andys** [comment] 2014-12-07 23:57
:panda_face: just experienced this, in 1.8.1 and 1.8.2

**Comment by jbbarth** [comment] 2015-01-06 16:24
I confirm the bug and confirm that the commit identified by @josephtate is responsible for this bad behaviour (I hope you don't mind Joseph, you said you would submit a PR but it's been a month so I guess you were busy elsewhere). I submitted a PR and I wish it is included soon in a stable release.

PS: sorry for the noise in the linked commits, the only correct is the last one, I pushed multiple times on my own repo but wrong branch / wrong comment in the commit so...

**Comment by josephtate** [comment] 2015-01-06 16:42
Thanks jjbarth. I got busy and reverted to 1.7.2 because of other bugs in 1.8.*.

**Comment by m-o-e** [comment] 2015-02-03 10:06
+1 bump for merge, I've also been bitten by this :beetle:

**Comment by pkoperek** [comment] 2015-02-08 22:46
any news? was just hit by that problem...

**Comment by jamesdmorgan** [comment] 2015-02-11 17:19
+1 this is affecting me too

**Comment by m-o-e** [comment] 2015-02-11 18:39
I've been running with this patch for over a week now without problems.

Please merge.

**Comment by bcoca** [comment] 2015-02-11 18:55
closing issue through merge of #597

**Closed as completed by bcoca** 2015-02-11 18:55 UTC
Labels: P2, bug_report
