### ISSUE TITLE
sudo hangs with 2.0/current master

### ISSUE THREAD

**Issue by rlpowell** [ansible/ansible-modules-core#1490] opened 2015-06-08 19:50 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0 (devel bbfc982dd5) last updated 2015/06/08 11:08:49 (GMT -700)
  lib/ansible/modules/core: (detached HEAD b138411671) last updated 2015/06/08 11:09:12 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 1276420a3a) last updated 2015/06/08 11:09:34 (GMT -700)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/08 11:09:54 (GMT -700)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/08 11:10:13 (GMT -700)
  configured module search path = None
```
##### Ansible Configuration:

Completely clean git clone, no config file.
##### Environment:

Fedora 21
##### Summary:

ansible -s -k -K hangs on the current git version (i.e. cd ansible ; source
./hacking/env-setup), but succeeds if I go to the v1/ directory and source the
./hacking/env-setup there
##### Steps To Reproduce:

Follow the instructions at
http://docs.ansible.com/intro_installation.html#running-from-source , and run
something like this:

$ ansible -i ~/scratch/ansible-inventory -vvvv -s -k -K -m shell vrici -a 'uname -a'
##### Expected Results:

Success/not hanging.
##### Actual Results:

```
rlpowell@stodi> ansible -i ~/scratch/ansible-inventory -vvvv -s -k -K -m shell vrici -a 'uname -a'
SSH password:
SUDO password[defaults to SSH password]:
<192.168.123.133> ESTABLISH SSH CONNECTION FOR USER: rlpowell
<192.168.123.133> EXEC sshpass -d12 ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o GSSAPIAuthentication=no -o PubkeyAuthentication=no -o ConnectTimeout=15
 192.168.123.133 mkdir -p $HOME/.ansible/tmp/ansible-tmp-1433791097.0-58803106616011 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1433791097.0-58803106616011 && echo $HOME/.ansible/tmp/ansible-tmp-1433791097.0-588
03106616011
<192.168.123.133> ESTABLISH SSH CONNECTION FOR USER: rlpowell
<192.168.123.133> PUT /tmp/tmpZ2HM9c TO /home/rlpowell/.ansible/tmp/ansible-tmp-1433791097.0-58803106616011/command
<192.168.123.133> ESTABLISH SSH CONNECTION FOR USER: rlpowell
<192.168.123.133> EXEC sshpass -d12 ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o GSSAPIAuthentication=no -o PubkeyAuthentication=no -o ConnectTimeout=15
 192.168.123.133 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=mlcgxrrkqxvfuozypptvuhbrwcljdqym] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-mlcgxrrkqxvfuozypptvuhbrwcljdqym; LANG=en_US.
UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/rlpowell/.ansible/tmp/ansible-tmp-1433791097.0-58803106616011/command; rm -rf /home/rlpowell/.ansible/tmp/ansible-tmp-1433791097.0-588031066
16011/ >/dev/null 2>&1'"'"''
vrici | FAILED! => {u'msg': u'[sudo via ansible, key=mlcgxrrkqxvfuozypptvuhbrwcljdqym] password: \r\nOpenSSH_6.6.1, OpenSSL 1.0.1k-fips 8 Jan 2015\r\ndebug1: Reading configuration data /home/rlpowell/.ssh/config\r
\ndebug1: /home/rlpowell/.ssh/config line 38: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Tr
ying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_s
ession: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 846\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session:
 master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to 192.168.123.133 closed.\r\n', u'failed': True, u'chang
ed': False, u'parsed': False, u'invocation': {u'module_name': u'command', u'module_args': {u'_raw_params': u'uname -a', u'_uses_shell': True}}}

-- It hangs for a minute or so before the "failed" step
```

**Comment by bcoca** [comment] 2015-06-08 19:58
confirmed in devel ... darnitthiswasworkinglastweek!!!

**Comment by rlpowell** [comment] 2015-06-08 20:01
FWIW, I would bet good money that it's simply never sending my sudo password.

**Comment by sivel** [comment] 2015-06-09 15:06
To my knowledge, none of the connection plugins in devel have sudo support right now.

Plugins:
1. ssh - completely commented out sudo functionality
2. paramiko - has functionality, but invalid variable references
3. local - completely commented out sudo functionality.

Currently they only work with passwordless sudo.

Also, this issue was created in the wrong repo.  This repo is for core modules, not the ansible core itself.  The correct repo is https://github.com/ansible/ansible

Also this is a duplicate of https://github.com/ansible/ansible/issues/11169

**Comment by bcoca** [comment] 2015-06-12 17:17
closing as dupe of https://github.com/ansible/ansible/issues/11169

**Closed as completed by bcoca** 2015-06-12 17:17 UTC
Labels: P1, bug_report
