### ISSUE TITLE
bug module apt_repository broken for debian

### ISSUE THREAD

**Issue by guits** [ansible/ansible-modules-core#1824] opened 2015-07-28 15:52 UTC
Hello,

i think there is a problem with the module apt_repository.

i have a very basic usage of the module under debian (jessie).

```
- name: add my repo
  apt_repository: "repo='deb http://mylogin:mypassword@my.repo.com wheezy main' mode=644 state=present"
- name: add gpg public key for my repo
  apt_key: url=http://mylogin:mypassword@my.repo.com/key/mykey.pub state=present
```

i got the following python traceback :

```
  Traceback (most recent call last):
  File \"/root/.ansible/tmp/ansible-tmp-1438092928.49-68932008668391/apt_repository\", line 2948, in <module> main()
  File \"/root/.ansible/tmp/ansible-tmp-1438092928.49-68932008668391/apt_repository\", line 454, in main
  if state == 'present' and expanded_repo not in sourceslist.repos_urls:
  AttributeError: 'SourcesList' object has no attribute 'repos_urls'
```

this error is at :
https://github.com/ansible/ansible-modules-core/blob/stable-1.9/packaging/os/apt_repository.py#L449

```
        if state == 'present' and expanded_repo not in sourceslist.repos_urls:
```

using `repos_urls` method, i'm using debian so my `sourcelist` variable is an instance of `SourceList()` :
https://github.com/ansible/ansible-modules-core/blob/stable-1.9/packaging/os/apt_repository.py#L436

```
            sourceslist = SourcesList()
```

but the method `repos_urls()` is only implemented in `UbuntuSourcesList()` for Ubuntu

**Comment by bcoca** [comment] 2015-07-28 19:16
duplicate of #1684

**Closed as completed by bcoca** 2015-07-28 19:16 UTC
Labels: bug_report
