### ISSUE TITLE
[Feature] Termination Protection for EC2 instances

### ISSUE THREAD

**Issue by MrMMorris** [ansible/ansible-modules-core#1069] opened 2015-04-02 20:04 UTC
Didn't see this option anywhere so I thought I'd ask:

Is there a way to turn on Termination Protection for instances with the EC2 module?

If not, I think it would be a very good feature to help me sleep at night :wink:

**Comment by bcoca** [comment] 2015-04-15 19:44
closing as dupe of #205

**Closed as completed by bcoca** 2015-04-15 19:44 UTC
