### ISSUE TITLE
[command, shell] escaped template gets mangled

### ISSUE THREAD

**Issue by seschwar** [ansible/ansible-modules-core#741] opened 2015-02-02 12:14 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.8.2
  configured module search path = /usr/share/ansible
```
##### Environment:

Debian unstable
##### Summary:

Escaped templates (`{{foo}}`) are mangled (`{#foo#}`) when using `command` and `shell`.
##### Steps To Reproduce:

Run the following playbook:

```
- hosts: localhost
  connection: local
  tasks:
    - action: "{{ item }} /bin/echo -n {{ '{{' }}foo{{ '}}' }}"
      with_items:
        - command
        - raw
        - script
        - shell
      register: _
    - debug:
        var: _
```

Examine the values of the `stdout` fields.
##### Expected Results:

The `stdout` of all `action`s should be `{{foo}}`.
##### Actual Results:

`stdout` for the `command` and `shell` module is `{#foo#}`
instead of `{{foo}}`.  `stdout` for the `raw` and `script`
module is `{{foo}}`, as expected.

**Comment by bcoca** [comment] 2015-02-02 13:06
The issue is that any return values from the module get 'sanatized' to avoid possible variable injection, so the values are correctly sent to the module but when registered it removes {{ }} pairs for comments {# #} as a security measure.

I'm closing this as it is not a bug, but works as expected.

**Closed as completed by bcoca** 2015-02-02 13:06 UTC
