### ISSUE TITLE
v2: ec2_eip breaks with «'Address' object has no attribute 'device_id'»

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible-modules-core#2058] opened 2015-09-13 16:39 UTC
**Issue type**: Bug report
**Ansible version**: devel@f0efe1e
**Ansible configuration**: N/A (defaults)
**Environment**: Linux, Python 2.7.3, boto 2.38.0, boto3 1.1.3
**Summary**:

I have a task like this:

```
    - name: Associate elastic IPs
      ec2_eip:
        state: present
        region: "{{ item.instances[0].region }}"
        instance_id: "{{ item.instances[0].id }}"
        reuse_existing_ip_allowed: true
      with_items: ec2_instances.results
      when: ec2_instances.changed
      register: eips
```

**Steps to reproduce**:

Execute the above task in a playbook (`ec2_instances` is the registered result of an earlier `ec2` task).

**Expected results**:

An elastic IP is associated with the instances in `ec2_instances` (note that this exact playbook used to work fine earlier, even with devel a few weeks ago).

**Actual results**:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/ams/.ansible/tmp/ansible-tmp-1442161124.52-136109087281836/ec2_eip", line 2290, in <module>
    main()
  File "/home/ams/.ansible/tmp/ansible-tmp-1442161124.52-136109087281836/ec2_eip", line 347, in main
    module.check_mode, isinstance=is_instance)
  File "/home/ams/.ansible/tmp/ansible-tmp-1442161124.52-136109087281836/ec2_eip", line 259, in ensure_present
    address = allocate_address(ec2, domain, reuse_existing_ip_allowed)
  File "/home/ams/.ansible/tmp/ansible-tmp-1442161124.52-136109087281836/ec2_eip", line 207, in allocate_address
    if not a.device_id]
AttributeError: 'Address' object has no attribute 'device_id'
```

cc: @evanccnyc as author of commit 06e72290 in `ansible-modules-core` that added the `a.device_id` access that's failing. If I change it to `a.instance_id` as it was before the commit, it works again. cc: @bretmartin because he was helping me look into this earlier.

**Comment by evanccnyc** [comment] 2015-09-13 21:27
Weird, I swear I tested this. I will look at this today and tomorrow.

**Comment by evanccnyc** [comment] 2015-09-13 21:34
I see what the problem is. We need to search for either instance_id or association_id in this area:

https://github.com/ansible/ansible-modules-core/blob/devel/cloud/amazon/ec2_eip.py#L205-L208

Something like this:

```

        unassociated_addresses = [a for a in all_addresses
                                  if not (a.instance_id or a.association_id)]
        if unassociated_addresses:
            return unassociated_addresses[0]
```

I'll test this tomorrow.

**Comment by evanccnyc** [comment] 2015-09-13 21:40
2nd try:

```
        if domain == 'vpc':
            unassociated_addresses = [a for a in all_addresses
                                      if not a.association_id]
        else:
            unassociated_addresses = [a for a in all_addresses
                                      if not a.instance_id]
        if unassociated_addresses:
                 return unassociated_addresses[0]

```

That should do it. Ill do a test tomorrow to make sure.

**Comment by amenonsen** [comment] 2015-09-14 06:09
If I apply your suggested patch, I get "You must specify an allocation id when mapping an address to a VPC instance". I don't know what that means, but adding `in_vpc: yes` to the `ec2_eip` task makes it go away (which I didn't actually expect, since the message sounded like that _was_ the problem).

**Comment by jimi-c** [comment] 2015-09-14 15:47
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-09-14 15:47 UTC
