### ISSUE TITLE
can't upload to S3 in 1.9.0

### ISSUE THREAD

**Issue by smiller171** [ansible/ansible-modules-core#1013] opened 2015-03-27 16:57 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.0.1
##### Environment:

Ubuntu 14.04 deploying against AWS API
##### Summary:

Upload to S3 is broken in 1.9.0

Reverting to 1.8.2 fixes the problem. I did not test on 1.8.3 or 1.8.4 because of other known issues that affect my playbooks.
##### Steps To Reproduce:

``` yaml
- name: s3 upload test
  hosts: localhost
  connection: local
  tasks:
  - name: push updated vars file to S3
    s3:
      bucket: workbench-dev
      src: "/tmp/lcs.var"
      object: "/vars/ansible-scott/workbench/lcs.var"
      mode: put
      overwrite: True
```
##### Expected Results:

File is uploaded to S3, overwriting existing file
##### Actual Results:

```
TASK: [push updated vars file to S3] ****************************************** 
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/smiller/.ansible/tmp/ansible-tmp-1427475075.52-143985703155210/s3", line 2299, in <module>
    main()
  File "/home/smiller/.ansible/tmp/ansible-tmp-1427475075.52-143985703155210/s3", line 405, in main
    bucketrtn = bucket_check(module, s3, bucket)
  File "/home/smiller/.ansible/tmp/ansible-tmp-1427475075.52-143985703155210/s3", line 162, in bucket_check
    except s3.provider.storage_response_error, e:
AttributeError: 'NoneType' object has no attribute 'provider'


FATAL: all hosts have already failed -- aborting
```

**Comment by bcoca** [comment] 2015-03-27 17:21
closing as duplicate of #964, test against current development it should be fixed there

**Closed as completed by bcoca** 2015-03-27 17:21 UTC

**Comment by smiller171** [comment] 2015-03-27 18:18
confirmed working on devel :+1:
