### ISSUE TITLE
win_template module does not delete temp folder

### ISSUE THREAD

**Issue by NRay7882** [ansible/ansible-modules-core#3032] opened 2016-02-12 20:29 UTC
**Issue Type:**
Bug Report

**Ansible Version:**
2.0.0.2

**Ansible Configuration:**
Sample config is attached.

**Environment:**
Ansible OS: Ubuntu 14.04.3 LTS
Target OS: Windows Server 2012 R2, x64, SP1

**Summary:**
We've noticed when using win_template it will create a temp dir with a 'source' file, which contains the contents of our PS script with the resolved ansible vars, then it copies 'copy.ps1' to the target machine and executes it. When it's successful, Ansible cleans up the copy.ps1 and it's temp directory, but never the one created initially with win_template. We are using win_template to fill-out a config file, for this reason we want it removed after execution.

I've included a sample from our play for the entire win_template task, in this sample "ansible-tmp-1455303612.46-80681088225906" is the directory that does not get removed and "ansible-tmp-1455303614.07-104233586262299" is the copy.ps1 directory that does get removed. We are not using ANSIBLE_KEEP_REMOTE_FILES in our execution. As a workaround, we are adding a step to remove this directory once the win_template task is finished.

From the main.yml:

``` yaml
    - name: Copy backup script to temp drive on host
      win_template:
        src: backup.ps1
        dest: "AppData\\Local\\Temp\\backup.ps1"
```

Response:

```
TASK [win_tasks : Copy backup script to temp drive on host] ********
task path: /jenkins/build/path/roles/win_tasks/tasks/main.yml:3
<10.xxx.xxx.xxx> ESTABLISH WINRM CONNECTION FOR USER: <user> on PORT 5986 TO 10.xxx.xxx.xxx
<10.xxx.xxx.xxx> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1455303612.46-80681088225906").FullName | Write-Host -Separator '';
<10.xxx.xxx.xxx> EXEC Set-StrictMode -Version Latest
If (Test-Path -PathType Leaf "AppData\\Local\\Temp\\backup.ps1")
{
$sp = new-object -TypeName System.Security.Cryptography.SHA1CryptoServiceProvider;
$fp = [System.IO.File]::Open("AppData\\Local\\Temp\\backup.ps1", [System.IO.Filemode]::Open, [System.IO.FileAccess]::Read);
[System.BitConverter]::ToString($sp.ComputeHash($fp)).Replace("-", "").ToLower();
$fp.Dispose();
}
ElseIf (Test-Path -PathType Container "AppData\\Local\\Temp\\backup.ps1")
{
Write-Host "3";
}
Else
{
Write-Host "1";
}
<10.xxx.xxx.xxx> PUT "/tmp/tmpg9ltJo" TO "C:\Users\<user>\AppData\Local\Temp\ansible-tmp-1455303612.46-80681088225906\source"
<10.xxx.xxx.xxx> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1455303614.07-104233586262299").FullName | Write-Host -Separator '';
<10.xxx.xxx.xxx> PUT "/tmp/tmpcExQ25" TO "C:\Users\<user>\AppData\Local\Temp\ansible-tmp-1455303614.07-104233586262299\copy.ps1"
<10.xxx.xxx.xxx> EXEC Set-StrictMode -Version Latest
Try
{
& "C:\Users\<user>\AppData\Local\Temp\ansible-tmp-1455303614.07-104233586262299\copy.ps1"
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\<user>\AppData\Local\Temp\ansible-tmp-1455303614.07-104233586262299" -Force -Recurse -ErrorAction SilentlyContinue }
changed: [<vm_name>] => {"changed": true, "invocation": {"module_args": {"dest": "AppData\\\\Local\\\\Temp\\\\backup.ps1", "src": "backup.ps1"}, "module_name": "win_template"}, "operation": "file_copy", "original_basename": "backup.ps1", "size": 3302}
```

**Steps To Reproduce:**
1. Create a Windows play containing the win_template task. Have it transfer a file from your Ansible host to your Windows target machine.
2. After execution, review the directory where the file(s) were sent to on the Windows target machine, there should be an 'ansible-tmp-******' directory left behind by win_template with a source file contained inside.

**Expected Results:**
As with the other tasks, this module should clean up after itself and remove the tmp directory created by win_template

**Actual Results:**
A directory containing a 'source' file with no extension is left in the tmp directory and is not removed.

Sample .cfg: [ansible_config.txt](https://github.com/ansible/ansible-modules-core/files/128635/ansible_config.txt)

**Comment by jhawkesworth** [comment] 2016-02-19 01:30
Thank you for the bug report.

Reproduced in 2.0.1 RC2 

I need to examine this further and may need some advice from the core team where responsibility for cleaning up the folder containing the source file should lie (in action plugin or connection plugin)

Reproducer playbook - cat amc3032.yml

``` yaml

---
- hosts: windows
  tasks:
    - name: Copy backup script to temp drive on host
      win_template:
        src: backup.ps1
        dest: "AppData\\Local\\Temp\\backup.ps1"
```

Reproducer powershell template/ script - cat backup.ps1

``` yaml
echo {{ ansible_hostname}}
```

**Comment by justenwalker** [comment] 2016-02-19 04:23
I could be completely wrong, trying to follow all of the various bits and pieces of the plugin library is kind of daunting, but after some looking I have a feeling that [ansible/plugins/action/copy.py:L283](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/copy.py#L283) is false because the copy module ran with 1 source file - perhaps the assumption is that the action plugin cleans up after both by re-using the same temp folder - which might be true in SSH but not WinRM.

## Given

```
A: C.DEFAULT_KEEP_REMOTE_FILES = False
B: delete_remote_tmp
C: module_executed

P:  (not C.DEFAULT_KEEP_REMOTE_FILES and not delete_remote_tmp) or (not C.DEFAULT_KEEP_REMOTE_FILES and delete_remote_tmp and not module_executed)
```

## Then

Simplify `P`

```
(!A && !B) || (!A && B && !C) ->
!A = 1; (1 && !B) || (1 && B && !C) ->
!B || (B && !C)
```

<table>
<tr>
  <th>B</th>
  <th>C</th>
  <th>!B || (B && !C)</th>
</tr>
<tr>
  <th>0</th>
  <th>0</th>
  <th>1</th>
</tr>
<tr>
  <th>1</th>
  <th>0</th>
  <th>1</th>
</tr>
<tr>
  <th>1</th>
  <th>1</th>
  <th>0</th>
</tr>
<tr>
  <th>0</th>
  <th>1</th>
  <th>1</th>
</tr>
</table>

## Therefore

Remote temp files will not be deleted when:

delete_remote_tmp = True
module_executed = True

I believe the [copy module runs](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/copy.py#L243) for `win_template` which implies `module_executed = True`
and [delete_remote_tmp = (len(source_files) == 1)](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/copy.py#L141) and I know we only have one source file.

Also, the if statement can be simplified which might make it easier to tell if it's correct.
`!A` can be factored out, and the remaining `!B || (B && !C)` looks like a NAND so it's just `!(B&&C)`

```
(!A && !B) || (!A && B && !C) ->
!A && (!B || (B && !C)) ->
!A && !(B && C)
```

``` python
if not C.DEFAULT_KEEP_REMOTE_FILES and not ( delete_remote_tmp and module_executed ):
```

**Comment by jhawkesworth** [comment] 2016-02-23 08:53
Thanks for your analysis @justenwalker 
I tried switching th e logic as you suggest but I hit a couple of fails and have gone back to trying to debug.

It appears that something slightly different happens with template on linux.  This isn't an entirely analogous test as I was running against localhost instead of a remote machine, but with the following playbook I get an empty folder left behind in my /home/<my_user>/.ansible/tmp/ dir:

``` yaml
---
- hosts: localhost
  tasks:
    - name: Copy backup script to temp drive on host
      template:
        src: backup.ps1
        dest: /tmp/backup.ps1
```

I will continue to investigate.

**Comment by justenwalker** [comment] 2016-02-23 15:35
Something that I can't understand: Why would you not want to delete the temp folder if the module was executed? 

This makes more sense to me, but I might be missing something more subtle:

``` python
if not C.DEFAULT_KEEP_REMOTE_FILES and delete_remote_tmp:
```

**Comment by jhawkesworth** [comment] 2016-02-23 18:29
Not tested, but I imagine with_items might add complexity to this.

**Comment by jhawkesworth** [comment] 2016-02-24 08:54
Some testing has shown that the copy action plugin doesn't seem to be involved, (or at least its run method).  template action plugin does get called.
Right now I can't even re-run the amc3032.yml playbook without retrieving a traceback, thus:

``` bash
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/jon/ansible-dev/ansible/lib/ansible/executor/task_executor.py", line 120, in run
    res = self._execute()
  File "/home/jon/ansible-dev/ansible/lib/ansible/executor/task_executor.py", line 418, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/jon/ansible-dev/ansible/lib/ansible/plugins/action/template.py", line 144, in run
    remote_checksum = self.get_checksum(dest, task_vars, not directory_prepended, source=source)
  File "/home/jon/ansible-dev/ansible/lib/ansible/plugins/action/template.py", line 48, in get_checksum
    return dest_stat['checksum']
```

continuing to investigate.

**Comment by jhawkesworth** [comment] 2016-02-24 18:28
Having updated to latest devel, traceback has gone but temp folder containing source still left behind after each playbook run.

**Comment by jhawkesworth** [comment] 2016-02-24 18:41
Ok, so I think it is as simple as adding

``` python
            self._remove_tmp_path(tmp)
```

on L 180 of plugins/action/template.py

More testing needed to see if it breaks anything though.

**Comment by jhawkesworth** [comment] 2016-02-26 08:53
Fix described above seems to remove the temp files.  However, the win_test_template integration test seem to be failing for me against latest development so investigating that at the moment.

**Comment by jhawkesworth** [comment] 2016-03-02 08:27
The win_test_template integration test issue has been resolved in latest devel branch now so I am back on this.  Fix above still leaving temp dirs behind when re-running the reproducer playbook above.

**Comment by bcoca** [comment] 2016-03-08 22:17
closing this as dupe of above, this is not a module issue but an ansible one.

**Closed as completed by bcoca** 2016-03-08 22:17 UTC
Labels: bug_report
