### ISSUE TITLE
template incorrectly reports remote file as different (on alternate hosts) when using ansible_ssh_host

### ISSUE THREAD

**Issue by dazwin** [ansible/ansible-modules-core#950] opened 2015-03-16 22:25 UTC
I have a role with two hosts using ansible_ssh_host, and a couple of host_vars files to configure different values for each one...

```
hosts:
    [database]
    dba-01 ansible_ssh_host=dba-01.fqdn.com
    dba-02 ansible_ssh_host=dba-02.fqdn.com
```

```
hosts/host_vars/dba-01
    cassandra_private_fqdn: "cass-01.fqdn.com"
```

```
hosts/host_vars/dba-02
    cassandra_private_fqdn: "cass-02.fqdn.com"
```

I then have a template file that uses the host-specific values:

```
roles/cassandra/templates/cassandra.yaml.j2
    broadcast_rpc_address: {{ cassandra_private_fqdn }}
```

Every time I run the playbook, the destination file of each host is alternately flagged as having changed. Here are snippets from three successive runs (while I was diagnosing this, I modified ansible/runner/action_plugins/template.py to print the local and remote checksums):

```
TASK: [cassandra | Configure Cassandra] *************************************** 
Local checksum 64c5c941f0dfe7b0f3d766c8819e964bd2e83a66 vs ee14d7fa43913cf7ad03c75867710dd9abcee259
Local checksum ee14d7fa43913cf7ad03c75867710dd9abcee259 vs ee14d7fa43913cf7ad03c75867710dd9abcee259
changed: [dba-01] => {"changed": true, "checksum": "64c5c941f0dfe7b0f3d766c8819e964bd2e83a66", "dest": "/etc/cassandra/cassandra.yaml", "gid": 0, "group": "root", "md5sum": "e766aeafda40b16daac2c837a1ba7537", "mode": "0644", "owner": "root", "size": 35801, "src": "/tmp/ansible-tmp-1426542768.04-170619872478768/source", "state": "file", "uid": 0}
ok: [dba-02] => {"changed": false, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/cassandra/cassandra.yaml", "size": 35801, "state": "file", "uid": 0}
```

```
TASK: [cassandra | Configure Cassandra] *************************************** 
Local checksum 64c5c941f0dfe7b0f3d766c8819e964bd2e83a66 vs 64c5c941f0dfe7b0f3d766c8819e964bd2e83a66
Local checksum ee14d7fa43913cf7ad03c75867710dd9abcee259 vs 64c5c941f0dfe7b0f3d766c8819e964bd2e83a66
ok: [dba-01] => {"changed": false, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/cassandra/cassandra.yaml", "size": 35801, "state": "file", "uid": 0}
changed: [dba-02] => {"changed": true, "checksum": "ee14d7fa43913cf7ad03c75867710dd9abcee259", "dest": "/etc/cassandra/cassandra.yaml", "gid": 0, "group": "root", "md5sum": "71ad4547b5ca00b338dd7b8235f455f0", "mode": "0644", "owner": "root", "size": 35801, "src": "/tmp/ansible-tmp-1426542824.92-189738812858915/source", "state": "file", "uid": 0}
```

```
TASK: [cassandra | Configure Cassandra] *************************************** 
Local checksum 64c5c941f0dfe7b0f3d766c8819e964bd2e83a66 vs ee14d7fa43913cf7ad03c75867710dd9abcee259
Local checksum ee14d7fa43913cf7ad03c75867710dd9abcee259 vs ee14d7fa43913cf7ad03c75867710dd9abcee259
ok: [dba-02] => {"changed": false, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/cassandra/cassandra.yaml", "size": 35801, "state": "file", "uid": 0}
changed: [dba-01] => {"changed": true, "checksum": "64c5c941f0dfe7b0f3d766c8819e964bd2e83a66", "dest": "/etc/cassandra/cassandra.yaml", "gid": 0, "group": "root", "md5sum": "e766aeafda40b16daac2c837a1ba7537", "mode": "0644", "owner": "root", "size": 35801, "src": "/tmp/ansible-tmp-1426542873.97-189236155318291/source", "state": "file", "uid": 0}
```
- On every run, the remote files on both hosts are correct. This is a problem with files incorrectly marked as changed and, in my case, results in unnecessary server restarts etc.
- The problem occurs whether I use a FQDN or IP address in ansible_ssh_host
- If I --limit=dba-01 (or 02), then the problem goes away
- If I do not use ansible_ssh_host and configure to use the full hostnames directly, the problem also goes away

**Comment by dazwin** [comment] 2015-03-16 22:26
Using ansible v1.8.4

**Comment by vovansystems** [comment] 2015-03-31 15:23
i have the same issue - every time a file is copied and is changed, when working with template in a playbook:

```
---
- hosts: all

  tasks:
  - group_by: key=os_Debian

- hosts: os_Debian
  gather_facts: False

  vars:

  - admin_email: email@domain.com
  - timezone: Europe/Minsk

  roles:
   - role: common
```

task:

```
  - name: Set timezone variables
    template: src=timezone.j2 
      dest=/etc/timezone 
      backup=yes
```

contents of `timezone.j2`:

```
{{ timezone }}
```

verbose info from ansible:

```
TASK: [common | Set timezone variables] ***************************************
changed: [192.168.1.81] => {"backup_file": "/etc/timezone.2015-03-31@16:28:06~", "changed": true, "checksum": "8c1d3ff8d98af685c5349fd8fa88b985470721d0", "dest": "/etc/timezone", "gid": 0, "group": "root", "md5sum": "155157633daf72b295d9dde4b7aed6b8", "mode": "0644", "owner": "root", "size": 12, "src": "/root/.ansible/tmp/ansible-tmp-1427809749.93-176621724369182/source", "state": "file", "uid": 0}
```

with `backup=no`:

```
TASK: [common | Set timezone variables] ***************************************
changed: [192.168.1.81] => {"changed": true, "checksum": "8c1d3ff8d98af685c5349fd8fa88b985470721d0", "dest": "/etc/timezone", "gid": 0, "group": "root", "md5sum": "155157633daf72b295d9dde4b7aed6b8", "mode": "0644", "owner": "root", "size": 12, "src": "/root/.ansible/tmp/ansible-tmp-1427810344.71-240004956180329/source", "state": "file", "uid": 0}
```

checksums from remote machine are different:

```
root@debian2:/etc# ls -la time*
-rw-r--r-- 1 root root 13 Mar 31 16:34 timezone
-rw-r--r-- 1 root root 17 Mar 28 14:19 timezone.2015-03-31@09:24:07~
-rw-r--r-- 1 root root 13 Mar 31 16:24 timezone.2015-03-31@16:26:26~
-rw-r--r-- 1 root root 13 Mar 31 16:26 timezone.2015-03-31@16:28:06~
-rw-r--r-- 1 root root 13 Mar 31 16:28 timezone.2015-03-31@16:34:13~

root@debian2:/etc# md5sum time*
c3a818149bfcce82d23928e2f5c5814b  timezone
28076efbe3eee21644ce11cb2e942a1a  timezone.2015-03-31@09:24:07~
c3a818149bfcce82d23928e2f5c5814b  timezone.2015-03-31@16:26:26~
c3a818149bfcce82d23928e2f5c5814b  timezone.2015-03-31@16:28:06~
c3a818149bfcce82d23928e2f5c5814b  timezone.2015-03-31@16:34:13~

root@debian2:/etc# sha256sum time*
ef763f2226740ac2141ddc4b92616fe48121a64af91e0969c8ce59c4030629d3  timezone
97a96def5389f70f749d69d5f58872871561f3155381b303845589bafcd48a0f  timezone.2015-03-31@09:24:07~
ef763f2226740ac2141ddc4b92616fe48121a64af91e0969c8ce59c4030629d3  timezone.2015-03-31@16:26:26~
ef763f2226740ac2141ddc4b92616fe48121a64af91e0969c8ce59c4030629d3  timezone.2015-03-31@16:28:06~
ef763f2226740ac2141ddc4b92616fe48121a64af91e0969c8ce59c4030629d3  timezone.2015-03-31@16:34:13~

root@debian2:/etc# sha1sum time*
7fa896c171bc4030441c1d6bb0d4c4c5320964c5  timezone
ec3db0f5f9dd340fa169824332903411285b1d52  timezone.2015-03-31@09:24:07~
7fa896c171bc4030441c1d6bb0d4c4c5320964c5  timezone.2015-03-31@16:26:26~
7fa896c171bc4030441c1d6bb0d4c4c5320964c5  timezone.2015-03-31@16:28:06~
7fa896c171bc4030441c1d6bb0d4c4c5320964c5  timezone.2015-03-31@16:34:13~
```

my versions are (ansible was installed through pip `pip install ansible`)

```
# ansible --version
ansible 1.9.0.1
  configured module search path = None
# uname -a
Linux debian1 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux
```

**Comment by bcoca** [comment] 2015-03-31 16:39
so I have been unable to reproduce this, are you doing any additional configuration for jinja2?

**Comment by abadger** [comment] 2015-03-31 16:59
Another possible thing to check -- what's the local and remote host types?  If there's something different about how the local host determines checksums than the remote host that could also be a source of the issue.

**Comment by vovansystems** [comment] 2015-03-31 17:00
@bcoca no, i don't have any additional configuration for jinja2.

i think that the issue is in my jinja2 template - i don't have a blank line in the end of the file - `{{ timezone }}`, when i change it to `{{ timezone }}\n` ansible playbook works as a charm. 

please, let me know if you reproduce this issue, otherwise i can send you an archive with my playbook and this role.

**Comment by bcoca** [comment] 2015-03-31 17:01
he, my test file does not have a \n either, but timezone file does require this, could it be the OS changing it automatically?

**Comment by dazwin** [comment] 2015-03-31 17:06
FWIW, I also had a timezone problem and yes, the Debian tzdata package replaces /etc/timezone during a dpkg-reconfigure, as well as resolves any TZ aliases - I had to specifically set the value to Etc/UTC and append a newline.

However, I think this is different from my original issue

**Comment by vovansystems** [comment] 2015-03-31 17:09
@bcoca oh! you are right - the `dpkg-reconfigure --frontend noninteractive tzdata` handler modifies that file! thank you very much and sorry for my inadvertence

**Comment by abadger** [comment] 2015-03-31 17:12
@dazwin Okay -- so if you are able to distill down a small step-by-step reproducer that could help.  bcoca and I have both tested things based on your description of your setup but neither have been able to reproduce.  Need some more info to be able to diagnose what's going on.

**Comment by jctanner** [comment] 2016-05-03 00:19
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

Our reasons and evidence for this are:
- I verified the change behavior across all release versions of ansible and found the expected behavior in each case.
- I suspect that if this issue was seen in an environment, it was likely due to the connection being local or running the task across two hostnames where one is a cname for the other.
- Without an ansible version, full ansible-playbook cli args and complete -vvvv output, we don't have enough data to sufficiently reproduce this problem without guessing at the conditions.

And we suggest that:
- If this is still an issue for you, please open a new issue with all attributes of the issue template completely filled out.

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by jctanner** 2016-05-03 00:19 UTC
Labels: P2, bug_report
