### ISSUE TITLE
assemble module does not support 'check mode'

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#661] opened 2015-01-19 13:45 UTC
**Issue Type:** Bug Report
**Ansible Version:** Current
**Steps to Reproduce:**
Assemble module has no check mode functionality. This may lead to an integrity loss in the following example case:
1. Upload fragments with file module
2. Compile a single file from the fragments using assemble module
In _check mode_ upload won't happen at the step 1. However, the step 2 will run resulting in an empty assembled file.
**Expected Result:**
 Assemble module does nothing in check mode
**Actual Result:**
Assemble module runs as usual in check mode

**Comment by bcoca** [comment] 2015-01-19 14:20
confirmed and reproduced issue

**Comment by rbu** [comment] 2015-07-13 13:41
This bug needs to be fixed. It is a major misbehaviour of Ansible that running a play in "Dry Run" mode (--check), it changes files on the server.

In addition, consider these implications:
1. Assembling files that are copied to the server (which are not there, due to it being a dry-run)
2. Handler notifications being missed because in the second (non-dry-run) the assembled file does not change

**Comment by bcoca** [comment] 2015-07-13 14:36
fixed via http://github.com/ansible/ansible/commit/d8abae71a477a9a49764840355063422c7188e3c

**Closed as completed by bcoca** 2015-07-13 14:36 UTC
Labels: bug_report

**Comment by rbu** [comment] 2015-07-13 16:41
Thanks for the quick quick fix
