### ISSUE TITLE
Ansible is unable to restart ssh on Ubuntu 14.04

### ISSUE THREAD

**Issue by svetlyak40wt** [ansible/ansible-modules-core#1298] opened 2015-05-09 16:53 UTC
Hi! I'm trying this simple playbook:

```
- hosts: any
  user: root
  tasks:
    - name: Restart sshd
      service:
        name: 'ssh'
        state: 'restarted'
```

I receive this error on hosts with Ubuntu 14.04:

```
TASK: [Restart sshd] **********************************************************
failed: [clupea.svetlyak.ru] => {"failed": true}

FATAL: all hosts have already failed -- aborting
```

but it completes with success on Ubuntu 12.04.

And if I run manually `service ssh restart` then it restarts as expected.

Probably, solving #882 issue could provide more info about what is happening.

**Comment by leucos** [comment] 2015-05-11 08:27
I can confirm this, I'm having the same issue.Questions are also popping up on SO http://stackoverflow.com/questions/30162528/ansible-service-restart-failed

After a quick look at the generated code on minion, it seems that service module wants to use `/etc/init.d/ssh` instead of `restart ssh`

**Comment by leucos** [comment] 2015-05-11 08:49
It seems that a fix is coming down the pipe: https://github.com/ansible/ansible-modules-core/commit/c4f6e63117cd378ed5b144bf6c8391420a2381ab

**Comment by bcoca** [comment] 2015-05-11 15:18
closing as dupe of #999, which has already been fixed in development

**Closed as completed by bcoca** 2015-05-11 15:18 UTC

**Comment by dmick** [comment] 2015-07-10 22:02
This was actually fixed by https://github.com/ansible/ansible-modules-core/commit/c4f6e63117cd378ed5b144bf6c8391420a2381ab, which I painfully discovered just now, not the commit for #999
