### ISSUE TITLE
get_url frequently produces corrupted files

### ISSUE THREAD

**Issue by warrenseine** [ansible/ansible-modules-core#2536] opened 2015-11-24 09:04 UTC
Frequently, `get_url` succeeds but the downloaded file is corrupted. I should use the `checksum` argument to ensure the success of the download, but still, I'm wondering _why_ it fails. Running the same HTTP request with `curl` on the same machine "always" succeeds (quoting, because this definitely requires some proper testing).

I've had issues with HTTPS related to the Python version in the past but this is pure HTTP. The connection may not be perfect but I haven't encountered this kind of issue elsewhere. I'm downloading from a Jenkins server.

Have you had similar reports at times? Do you have any recommendation to diagnose it?

**Comment by robynbergeron** [comment] 2015-11-30 13:14
[module: network/basics/get_url.py]

**Comment by robynbergeron** [comment] 2015-11-30 13:15
@warrenseine -- Thanks for submitting this bug report.

@jpmens -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by Jmainguy** [comment] 2015-12-03 04:50
@warrenseine just tried with a 1gb file, 7 times, always had the same md5sum. Is there a specific url that gets corruped, or a size, or how much is "frequently", 1 in 10?

**Comment by warrenseine** [comment] 2015-12-03 06:40
This is not a specific URL, but all the URL have tried come from our build server. So that might be the issue on the server side. I'd say it happens about 1 in 4 and there is no specific size (average is 50 MB). I will make some proper test first before bothering you more.

**Comment by warrenseine** [comment] 2015-12-07 08:36
And not happening with proper tests on my side either. I still don't know what's happening, but in the end, I don't think it's Ansible-related or even Python-related. There must be something going on in the network.

Should we close?

**Comment by Jmainguy** [comment] 2015-12-07 14:47
Yeah I cannot reproduce, I say its safe to close. If you or anyone else can reproduce this easily, than we can just open up a new issue.

**Comment by bcoca** [comment] 2015-12-13 05:16
closing as per above

**Closed as completed by bcoca** 2015-12-13 05:16 UTC
Labels: bug_report

**Comment by abresson** [comment] 2017-03-03 07:17
Hello,

I'm having the same issue, using ansible 2.3.0 (devel 1c2e8fde29) last updated 2017/03/01 16:02:44 (GMT +200)

As example :


- name: vagrant, wget 
  get_url:
    url: "https://releases.hashicorp.com/vagrant/1.9.2/vagrant_1.9.2_x86_64.rpm"
    dest: /tmp/vagrant_1.9.2_x86_64.rpm_geturl
  when:
    ansible_os_family == "RedHat" and
    vagrant_present.rc != 0

VS

- name: vagrant, wget 
  shell: "wget -qO /tmp/vagrant_1.9.2_x86_64.rpm_wget https://releases.hashicorp.com/vagrant/1.9.2/vagrant_1.9.2_x86_64.rpm"
  when:
    ansible_os_family == "RedHat" and
    vagrant_present.rc != 0

This also happens when using yum module and getting an http rpm.

[root@centosfresh ~]# date
Fri Mar  3 08:16:50 CET 2017
[root@centosfresh ~]# md5sum /tmp/vagrant* ; ls -lh /tmp/vagrant*
f80b68e1a7b2fee8387b186cc1b267e9  /tmp/vagrant_1.9.2_x86_64.rpm_geturl
a8c65fb7e55053920994daa05bee2cea  /tmp/vagrant_1.9.2_x86_64.rpm_wget
-rw-r--r-- 1 root root 84M Mar  3 07:55 /tmp/vagrant_1.9.2_x86_64.rpm_geturl
-rw-r--r-- 1 root root 84M Mar  1 17:08 /tmp/vagrant_1.9.2_x86_64.rpm_wget


regards
