### ISSUE TITLE
Region cn-north-1 not supported

### ISSUE THREAD

**Issue by monasuncion** [ansible/ansible-modules-core#431] opened 2014-12-03 09:06 UTC
##### Issue Type:

Bug/Feature Idea
##### Ansible Version:

Ansible 1.7.2
##### Environment:

Fedora release 19
##### Summary:

We want to use Ansible in our EC2 deployments in China. I was able to successfully ping our instances there by changing the ec2.ini properties:

regions = cn-north-1
regions_exclude = us-gov-west-1

Unfortunately, when I tried to run a playbook I got this error:
TASK: [test elb creation in China] ********************************************
failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: value of region must be one of: ap-northeast-1,ap-southeast-1,ap-southeast-2,eu-west-1,sa-east-1,us-east-1,us-west-1,us-west-2, got: cn-north-1
##### Steps To Reproduce:
- Installed Ansible through yum
- Installed aws cli
- created ec2.ini and ec2.py files
- change ec2.ini property values

regions = cn-north-1
regions_exclude = us-gov-west-1
- ran this command and it ran successfully
  ansible -i hosts -m ping -u ec2-user 'cn-north-1:&security_group_ecc-vpcsg'
- created a playbook to create an EC2 elb. When I run the playbook 
  ansible-playbook -i hosts recognizer-elb.yml --verbose
- I get the following errors:

Unfortunately, when I tried to run a playbook I got this error:
TASK: [test elb creation in China] ********************************************
failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: value of region must be one of: ap-northeast-1,ap-southeast-1,ap-southeast-2,eu-west-1,sa-east-1,us-east-1,us-west-1,us-west-2, got: cn-north-1
- Below is the test playbook
  ---
  # Test create elb in China
- name: "test ELB creation in China"
  hosts: localhost
  gather_facts: true
  tasks:
        - name: "test elb creation in China"
          local_action:
                module: ec2_elb_lb
                name: "ccn-elb-test"
                scheme: internal
                state: present
                region: cn-north-1
                subnets:
                        - subnet-36ebf854
                listeners:
                        - protocol: http
                          load_balancer_port: 80
                          instance_port: 80
  
  ```
            health_check:
                    ping_protocol: http # options are http, https, ssl, tcp
                    ping_port: 80
                    ping_path: "/index.html" # not required for tcp or ssl
                    response_timeout: 5 # seconds
                    interval: 30 # seconds
  ```
##### Expected Results:

I expect to have created the ELB in China Region since I was able to successfully ssh and ping the instance.

Does this mean there is no support for China Regions yet? If so, When would this be available?

Opsworks and Beanstalk are not available in AWS China. We are thinking of using Ansible there.
##### Actual Results:

Unfortunately, when I tried to run a playbook I got this error:
TASK: [test elb creation in China] ********************************************
failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: value of region must be one of: ap-northeast-1,ap-southeast-1,ap-southeast-2,eu-west-1,sa-east-1,us-east-1,us-west-1,us-west-2, got: cn-north-1

**Comment by bcoca** [comment] 2014-12-03 12:57
This seems a duplicate of #351, support was added but it was done following Amazon's documentation, which seems to be incorrect and a patch is probably needed.

**Closed as completed by bcoca** 2014-12-03 12:57 UTC
Labels: P2, bug_report
