### ISSUE TITLE
Bug report: on RH5, yum module thinks a package is installed when it is not

### ISSUE THREAD

**Issue by stefano-cherchi** [ansible/ansible-modules-core#786] opened 2015-02-13 17:30 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Ansible server: 
Red Hat Enterprise Linux Server release 6.5 (Santiago)
Python 2.6.6

Ansible client:
Red Hat Enterprise Linux Server release 5.5 (Tikanga)
Python 2.4.3
##### Summary:

on RH5, yum module thinks a package is installed when actually it is not

In a playbook, I have a task to install ipa-client:

```
- name: Install ipa-client rpm package
  yum:
    name={{ item }}
    disable_gpg_check=yes
    state=installed
  with_items:
   - ipa-client
```

When it runs on a RH6 machine it behaves as expected, but on RH5 it won't install the package even if it is not installed on the system. 

It throws no errors. It just logs: 

```
TASK: [RH5 | Install ipa-client rpm package] ********************************** 
ok: [ipaclient1] => (item=ipa-client)
```

as if the package was already installed, when it is not. 

I've been able to reproduce this problem on three different RH5 servers. I run the same task on many RH6 servers and it worked flawlessly.

As a workaround, I "manually" installed the package by replacing the "yum" module task with an equivalent one, based on the "command" module:

```
- name: Manually install the ipa-client rpm package
  command: yum -y --nogpgcheck install ipa-client
```
##### Steps To Reproduce:

create a playbook containing the above task based on the yum module
run it on a Red Hat 5 machine
##### Expected Results:

the ipa-client package and all its dependencies are installed
##### Actual Results:

the ipa-client package and all its dependencies are not installed, no error is thrown, an "ok" message is logged, as if the package was already installed on the system

**Comment by abadger** [comment] 2015-03-03 23:19
I'm not able to reproduce this.  Here's the configurations I tested:

controller: fedora 21
Target: CentOS release 5.11 (Final)
ansible: - 1.7.2
              - devel branch checkout

```
$ ansible-playbook -i 'rhel5-test,' /var/tmp/yum.yml --sudo -K
sudo password: 

PLAY [rhel5-test] ************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [rhel5-test]

TASK: [Install ipa-client rpm package] **************************************** 
changed: [rhel5-test] => (item=ipa-client)

PLAY RECAP ******************************************************************** 
rhel5-test                 : ok=2    changed=1    unreachable=0    failed=0   

[pts/31@roan /srv/ansible/ansible-1.7.0]$ ansible-playbook -i 'rhel5-test,' /var/tmp/yum.yml --sudo -K
sudo password: 

PLAY [rhel5-test] ************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [rhel5-test]

TASK: [Install ipa-client rpm package] **************************************** 
ok: [rhel5-test] => (item=ipa-client)

PLAY RECAP ******************************************************************** 
rhel5-test                 : ok=2    changed=0    unreachable=0    failed=0
```

There's a large number of variables that need to be eliminated to figure out what could be the problem:
- The yum module on RHEL-5.5 could be buggy.  There are newer point releases of RHEL5 and one of those may contain an update to yum, yum-metadata-parser, or rpm that fixes this.
- ansible-1.7.2 might have a bug in combination with RHEL-5.5's yum.  Looking at the changelog I doubt that but you could upgrade to ansible 1.8.4 to check.
- Something about the yum repositories for ipa-client on your box may be strange.  I don't see how the yum comamndline would work while the yum module wouldn't work, though.
- This problem affects RHEL5 but not CentOS5.  That seems pretty doubtful as well.

github tickets aren't the fasted way to track down a non-reproducible error... might be better to take this to the mailing list for diagnosis and then revisit the ticket if we can narrow down the inputs to make this reproducible by us.

**Comment by jctanner** [comment] 2016-05-02 20:43
Since we were unable to reproduce your issue, and you were unable to respond to our information request, I am going to close this issue. Thank you for filing it and please followup with any other bugs you may find in the future.

**Closed as completed by jctanner** 2016-05-02 20:43 UTC
Labels: P2, bug_report
