### ISSUE TITLE
Regression due to #1138

### ISSUE THREAD

**Issue by arturhoo** [ansible/ansible-modules-core#1313] opened 2015-05-12 19:49 UTC
Hi there,

I believe #1138 introduces a regression on the services module, at least on Ubuntu 14.04.

The simple playbook below works on Ansible 1.9.0.1 but fails on 1.9.1

``` yaml

---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: reload ssh
      service:
        name: ssh
        state: reloaded

```

Breaking on 1.9.1:

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [default]

TASK: [reload ssh] ************************************************************
failed: [default] => {"failed": true}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/artur/playbook.retry

default                    : ok=1    changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

On 1.9.0.1:

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [default]

TASK: [reload ssh] ************************************************************
changed: [default]

PLAY RECAP ********************************************************************
default                    : ok=2    changed=1    unreachable=0    failed=0
```

A handy `Vagrantfile`

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
```

**Comment by bcoca** [comment] 2015-05-12 19:51
check current devel, 

The detection fix did not get a 'apply' fix at the time which introduced a new problem, this should be fixed in devel.

**Comment by bcoca** [comment] 2015-05-12 19:52
closing as dupe of #1298

**Closed as completed by bcoca** 2015-05-12 19:52 UTC
Labels: bug_report
