### ISSUE TITLE
change detection issue in check mode and templates with ~ expansion

### ISSUE THREAD

**Issue by romainrichard** [ansible/ansible-modules-core#29] opened 2014-09-29 21:24 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.3 and 1.7.1
##### Environment:

Ubuntu 14.04
##### Summary:

When inside a template, the tilde expansion doesn't seem to work correctly.

Before the migration, this was https://github.com/ansible/ansible/issues/8949.
##### Steps To Reproduce:

Here's the contents of the playbook:

``` bash
romain:~/workspace/it_ansible_check_issue $ tree
.
├── copy.yml
└── roles
    └── copy
        ├── tasks
        │   └── main.yml
        └── templates
            └── template.j2

4 directories, 3 files
```

``` bash
romain:~/workspace/it_ansible_check_issue $ cat copy.yml 

---
- name: copy template to servers
  hosts: all
  roles:
    - copy
```

``` bash
romain:~/workspace/it_ansible_check_issue $ cat roles/copy/tasks/main.yml 
# copy/tasks/main.yml

---
- name: copy template to host (tilde)
  template: >
    src=template.j2
    dest=~romain/template_tilde

- name: copy template to host (slash)
  template: >
    src=template.j2
    dest=/home/romain/template_slash
```

``` bash
romain:~/workspace/it_ansible_check_issue $ cat roles/copy/templates/template.j2 
test
```

Here's what happens when running the playbook without `--check`:

``` bash
romain:~/workspace/it_ansible_check_issue $ ansible-playbook copy.yml -i localhost,

PLAY [copy template to servers] *********************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [copy | copy template to host (tilde)] ********************************** 
ok: [localhost]

TASK: [copy | copy template to host (slash)] ********************************** 
ok: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

Here's what happens when running the playbook with `--check`:

``` bash
romain:~/workspace/it_ansible_check_issue $ ansible-playbook copy.yml -i localhost, --check

PLAY [copy template to servers] *********************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [copy | copy template to host (tilde)] ********************************** 
changed: [localhost]

TASK: [copy | copy template to host (slash)] ********************************** 
ok: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=1    unreachable=0    failed=0
```
##### Expected Results:

Running the playbook with or without the `--check` option shows the same number of changes.
##### Actual Results:

Running the playbook with `--check` option shows changes that don't happen when the playbook is run without it.

**Comment by mpdehaan** [comment] 2014-10-01 15:27
Thanks for the report!

I'm pretty sure tilde expansion _does_ work with templates, but this may be a check mode issue, so I'm going to note this in the description.

**Comment by romainrichard** [comment] 2014-10-01 15:40
Yes and no, if you take a look at this comment: https://github.com/ansible/ansible/issues/8949#issuecomment-55831114, you will see that it doesn't work with and without the check mode, the only difference being that we don't see it when the playbook is ran without the check mode.

**Comment by verm666** [comment] 2015-07-01 12:11
Can't reproduce it on 1.9.1 and devel version. @gregdek, you can close this issue, i guess.

**Closed as completed** 2015-07-04 02:09 UTC
Labels: bug_report
