### ISSUE TITLE
Copy module copies files to '/' directory instead of specified destination

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible-modules-core#1705] opened 2015-07-10 11:16 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

Current Ansible devel / v2
##### Ansible Configuration:

Ansible installed using a `.deb` package created by `make deb` command.
##### Environment:

Debian, Ubuntu
##### Summary:

`copy` module, when used to copy contents of directories instead of single files, copies them to `/` directory instead of destination directory.
##### Steps To Reproduce:

Example playbook:

```
- hosts: all
  sudo: True

  tasks:
    - copy:
        src: 'files/'
        dest: '/tmp/'
```

Create a `files/` directory in your current directory with some example files. Create files with the same name as directories in `/`, for example `tmp` or `etc`.
##### Expected Results:

Files are copied to specified directory without issues.
##### Actual Results:

Files are copied to `/` directory. Example out of Ansible if a conflicting filename is used:

```
TASK [Copy files] ***************************************************************
fatal: [hostname]: FAILED! => {"msg": "attempted to take checksum of directory: /tmp", "failed": true, "changed": false, "invocation": {"module_name": "copy", "module_args": {"dest": "/tmp/", "src": "/var/local/drybjed/.ansible/tmp/ansible-tmp-1436526765.13-1117624961432/source", "original_basename": "/tmp"}}, "checksum": "972a1a11f19934401291cc99117ec614933374ce"}
```

**Comment by bcoca** [comment] 2015-08-07 04:50
so i cannot seem to reproduce this in current devel as i'm hitting another issue:

```
FAILED! => {"failed": true, "msg": "ERROR! ssh connection closed waiting for password prompt"}
```

**Comment by bcoca** [comment] 2015-08-07 20:28
so after dealing with become issues i can now run this and the files end up in /tmp not in /

@drybjed can you test again with current devel?

**Comment by drybjed** [comment] 2015-08-07 20:59
On latest devel (dbab703) it seems to work as expected.

**Comment by bcoca** [comment] 2015-08-07 21:06
weeee! ... er I mean, closing since it works now.

**Closed as completed by bcoca** 2015-08-07 21:06 UTC
Labels: P1, bug_report
