### ISSUE TITLE
EC2_LC module fails when no default VPC is used in the region.

### ISSUE THREAD

**Issue by zephyrict** [ansible/ansible-modules-core#2035] opened 2015-09-09 10:35 UTC
##### Issue Type:
- Bug Report
  - feature request
##### Ansible Version:

ansible 1.9.3
Also tried with the early 2.0.0 version.
##### Ansible Configuration:

Nothing special, just the inventory, sudo_user, remote_user and added additional roles_path.
##### Environment:

Ubuntu 14.04 for manager and managed
##### Summary:

I’m trying to auto-configure elb and asg, but when using the ec2_lc module for the preparation I get the error that I don’t have a default VPC
##### Steps To Reproduce:

Try to run the prepare launch task using ec2_lc module without a default VPC
##### Expected Results:

It should work even when no default VPC is used, or an option to declare the VPC would be helpful. 
##### Actual Results:

```
failed: [localhost] => {"failed": true}
msg: BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://autoscaling.amazonaws.com/doc/2011-01-01/">
  <Error>
    <Type>Sender</Type>
    <Code>ValidationError</Code>

▽
  1 ---
    <Message>No default VPC for this user</Message>
  </Error>
  <RequestId>b4f24941-9384-32-9bc2-ef8e4ec57f44</RequestId>
</ErrorResponse>
FATAL: all hosts have already failed -- aborting
```

**Comment by raben2** [comment] 2016-01-25 09:13
This is a boto issue since the module can not be addressed with a vpc identifier. 
https://github.com/boto/boto/issues/3270

**Comment by bcoca** [comment] 2016-02-02 20:31
closing as dupe of #1719

**Closed as completed by bcoca** 2016-02-02 20:31 UTC
Labels: P2, bug_report
