### ISSUE TITLE
Unarchive doesn't recognize gzip file

### ISSUE THREAD

**Issue by phraktle** [ansible/ansible-modules-core#2442] opened 2015-11-10 16:20 UTC
(Ansible version 1.9.4)

The following throws "Failed to find handler to unarchive. Make sure the required command to extract the file is installed."

```
- name: get the latest geo data
  get_url: url=http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz dest=/tmp/

- name: decompress geo data
  unarchive: copy=no src=/tmp/GeoLite2-City.mmdb.gz dest=/tmp/
```

The file is a straightforward gzip archive:

```
# file GeoLite2-City.mmdb.gz 
GeoLite2-City.mmdb.gz: gzip compressed data, was "GeoLite2-City.mmdb", from Unix, last modified: Tue Nov  3 23:16:32 2015
```

which decompresses fine with gzip -d ...

**Comment by bcoca** [comment] 2015-11-10 18:42
unarchive does not support plain gzip compressed files only tar + gzip archives, closing this as dupe of #2420

**Closed as completed by bcoca** 2015-11-10 18:42 UTC
