### ISSUE TITLE
owner and group parameters are not used in unarchive module

### ISSUE THREAD

**Issue by vjestin** [ansible/ansible-modules-core#234] opened 2014-10-28 16:26 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

Ubuntu 14.04
##### Summary:

In the unarchive module, I want to use owner and group parameters so the unzipped files owner/group settings are set accordingly. Unfortunately, those parameters seem to be ignored, no matter if copy parameter is set to yes or no.
##### Steps To Reproduce:

```
- name: extract some files
  unarchive:
   src=mytar.tar.gz
   dest=/opt/
   owner=tomcat
   group=tomcat
  sudo: yes
```
##### Expected Results:

(Given mytar.tar.gz archive contains a directory named mydir)

```
ls -l /opt
drwxr-xr-x   5 tomcat tomcat  4096 Apr 22  2014 mydir
```
##### Actual Results:

```
ls -l /opt
drwxr-xr-x   5 root root  4096 Apr 22  2014 mydir
```

Easy workaround: set owner/group settings with a separate "file" task.

**Comment by bcoca** [comment] 2014-11-11 13:59
These options are not referenced or used at all in unarchive. The problem stems from a bleed over from the shared file module documentation which unarchive doesn't currently use.

**Comment by profhase** [comment] 2014-11-12 09:56
Nevertheless I see it both as a bug and as a feature request:
A bug because one usually gets an error on unsupported parameters (unsupported parameter)
A feature request because it seems logical to me that there is no semantical difference to a file module so there is a very inconvinient workaround by adding a file task just to chmod the unarchived folder
See also:
https://github.com/ansible/ansible/issues/9289

**Comment by itatabitovski** [comment] 2015-01-12 17:09
This is still a bug in ansible 1.8.2

If you add a task or handler (file) to chmod/chown the unarchived folder, the next time you run the playbook the unarchive task will return "changed"

**Comment by abadger** [comment] 2015-01-13 17:53
it looks like owner/group/mode were added to the documentation by mistake.  We were leaning towards fixing the documentation but @itatabitovski's comment (which is similar to the analysis in https://github.com/ansible/ansible-modules-core/issues/546 ) shows that there would be a use case for chmod/chown in the unarchive module.

The fix to #546 at least means that you can use creates= as a workaround.

**Comment by abadger** [comment] 2015-01-15 04:29
Second part which properly detects whether user, group, or mode will be changed committed in: e3759bd0d396d63b869732a63ecae5ca7a2a9641

One note:  This fix works for tar archives only.  Zip archives did not implement detection of changes to begin with.  I took a brief look at whether that would be doable.  It looks like detection of changes to the files themselves may be doable using the python stdlib ZipFile module.  But detection of changes to user, group, and mode is much more problematic.  Those fields may or may not exist depending on what operating system and with which software the archive was created.  One would have to read the zip specification and then make a best attempt to implement the common cases.

In any case, since ZipFile change detection is currently not functional (I'm guessing that people simply use the creates= parameter as a work around) I'm not going to implement that.  But I'll review a pull request if someone wants to implement it.  Just be warned that it's nontrivial and I'd want it to at least handle the data format for unix-like user, group, and mode.

**Comment by abadger** [comment] 2015-01-15 04:30
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by abadger** 2015-01-15 04:30 UTC
Labels: bug_report

**Comment by abadger** [comment] 2015-01-15 04:33
And just to clarify that caveat -- setting user, group, and mode works for zipfiles.  It's just detecting whether a zipfile needs to be re-unzipped or user/mode/group needs to be reapplied that is unimplemented and needs to be worked around via the creates= parameter.

**Comment by totoropy** [comment] 2016-03-25 18:21
Hi, I just want to share my experience with unarchive.
This task changed permissions of top level directories ./ and ../ to www-data:www-data 0644.
It locked whole machine!!! Pretty scary :-) 
ansible-playbook 2.0.1.0

```
- name: copy of application
  unarchive: >
    dest=/opt/web-apps/web2py/applications/myapp
    src=files/web2py.app.myapp.tar.gz
    owner=www-data
    group=www-data
    mode=0644
```

Do I use it wrong or is it bug?

**Comment by jcranky** [comment] 2016-04-09 07:18
Is this really fixed? I don't seem to be able to get the owner / group to be set at all. Ansible version: _2.0.1.0_

**Comment by jcranky** [comment] 2016-04-09 07:24
Ok, I just tested a bit more. It actually works for _tgz_ files, but not for _zip_ files.

**Comment by vertrost** [comment] 2016-08-12 15:43
still not resolved in ansible 2.1.0.0

**Comment by membrive** [comment] 2016-11-10 08:16
Same problem in ansible 2.2.0.0 extracting .tar.gz files, only in the top level directory.

**Comment by marcowork** [comment] 2017-01-10 15:31
can we reopen this? as @membrive  already mentioned it still not working with .tar.gz

**Comment by while1eq1** [comment] 2017-04-05 14:35
I can confirm this still does not work with .tar.gz (ansible 2.2.2.0)

**Comment by chriswhite199** [comment] 2017-06-08 21:19
Observation from 2.3.0.0 - for tar.gz files all the archive files get the correct owner / group attributes, but for child directories in the archive, the user/group attrs are not correctly set.

**Comment by seungdols** [comment] 2017-07-31 11:20
still...Ansible In version 2.3.1.0, the owner of tar.gz sub-directories is still unchanged. However, a single file applies. Do you have any other alternatives?

**Comment by fxer** [comment] 2017-10-23 18:07
Having this issue on Ansible 2.4 still

**Comment by paulcalabro** [comment] 2017-11-07 02:45
Experiencing this issue while using Ansible 2.4 as well.

**Comment by pescobar** [comment] 2018-01-28 11:38
I am also having this issue with version 2.4.2.0

The owner/group is properly applied for all the files inside the tarball but not for the top folder. e.g.

I uncompress a tar.gz like this:

```
- name: Uncompress the tarball to {{ install_foder }} . By default /opt
  unarchive:
    src: "{{ tarball_path }}"
    dest: "{{ tomcat_install_folder }}"
    remote_src: yes
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
```

but notice that the top folder `.` is still owned by root

```
[vagrant@centos7 ~]$ ls -la /opt/apache-tomcat-8.5.27
total 92
drwxr-xr-x. 9 root   root     160 Jan 28 11:29 .
drwxr-xr-x. 4 root   root     149 Jan 28 11:29 ..
drwxr-x---. 2 tomcat tomcat  4096 Jan 28 11:29 bin
drwx------. 3 tomcat tomcat   254 Jan 28 11:29 conf
drwxr-x---. 2 tomcat tomcat  4096 Jan 28 11:29 lib
-rw-r-----. 1 tomcat tomcat 57092 Jan 18 20:15 LICENSE
drwxr-x---. 2 tomcat tomcat   197 Jan 28 11:29 logs
-rw-r-----. 1 tomcat tomcat  1723 Jan 18 20:15 NOTICE
-rw-r-----. 1 tomcat tomcat  7138 Jan 18 20:15 RELEASE-NOTES
-rw-r-----. 1 tomcat tomcat 16246 Jan 18 20:15 RUNNING.txt
drwxr-x---. 2 tomcat tomcat    48 Jan 28 11:29 temp
drwxr-x---. 7 tomcat tomcat    81 Jan 18 20:13 webapps
drwxr-x---. 3 tomcat tomcat    22 Jan 28 11:29 work
```

**Comment by willthames** [comment] 2018-01-28 11:54
This issue is closed, and is in a closed repository. 

Please check if this issue is still occurring in the ansible/ansible repo - if not, please open a new issue.

This looks a bit like #21397 - some extra feedback there might be helpful.

**Comment by pescobar** [comment] 2018-01-28 14:27
@willthames I have reported the bug in https://github.com/ansible/ansible/issues/35426#issuecomment-361057789

**Comment by dagwieers** [comment] 2018-01-28 18:28
The problem is very simple, that directory is not part of the archive. So we cannot simply invent an owner or permissions for entries that are missing. You will have to talk to the project so they fix their archive.
