### ISSUE TITLE
docker module supposed to be able to upgrade?

### ISSUE THREAD

**Issue by bfleming-ciena** [ansible/ansible-modules-core#27] opened 2014-09-29 21:19 UTC
If you're familiar with the apt module, you can specify state=latest to get ansible to upgrade.

I want to do the same with docker. I want to run an image, and when that image has been updated I want the old container stopped and the new version of the container started.

Does the docker module support this?  I've tried and it doesn't work as I hoped.

Example playbook which I hoped to re-use over and over to ensure my target is at the latest.

hosts: localhost 
sudo: yes
tasks:

name: ensure redis container is running
docker: image=dockerfile/redis name=redis command=" bash -c 'redis-server /etc/redis/redis.conf'"

name: ensure latest version of the web container is running
docker: image=snazzy/cyweb ports=5000:5000 links=redis:redis name=cyweb

Thanks

**Comment by vlfig** [comment] 2014-10-02 11:13
Ansible docker module does not ensure correct container state after an image tag update.

When an image gets built and tagged with the same string that was provided to the docker plugin as the `image` param, the container associated with the previous image (no longer tagged) keeps running. No container associated with the given image name is running.

```
- name: run latest gocd-server
  sudo: yes
  docker: "image=organisation/gocd-server:latest state=running ports=8000:8000"
```

Steps to reproduce:
1. build an image and tag it.
2. run the above ansible task
3. rebuild the image (associate same tag with a different image)
4. run the above ansible task again
5. verify container running is based of the original image and no container associated with the now-tagged image is running.

Example (edited for clarity):

```
docker@mylovelydockerhost:~$ sudo docker images
REPOSITORY                         TAG                 IMAGE ID             CREATED       
organisation/gocd-server           latest              1246944e6539         16 hours ago  
coreplatform/gocd-agent            latest              8d2dee2ff4dc         18 hours ago  

docker@mylovelydockerhost:~$ sudo docker ps -a
CONTAINER ID        IMAGE                              COMMAND              CREATED       
2497cb1c0044        organisation/gocd-agent:latest     "/bin/sh -c '/etc/in 20 minutes ago
1566143ac885        organisation/gocd-server:latest    "/bin/bash"          16 hours ago  
```

All is well. Now run `docker build -t organisation/gocd-server:latest` pointing to a different Dockerfile. The tag gets updated.

```
docker@mylovelydockerhost:~$ sudo docker images
REPOSITORY                         TAG                 IMAGE ID             CREATED       
organisation/gocd-server           latest              d28b2c1fc0b7         20 minutes ago
<none>                             <none>              1246944e6539         16 hours ago  
coreplatform/gocd-agent            latest              8d2dee2ff4dc         18 hours ago  
```

Now run the above mentioned ansible task.

```
docker@mylovelydockerhost:~$ sudo docker ps -a
CONTAINER ID        IMAGE                              COMMAND              CREATED       
2497cb1c0044        organisation/gocd-agent:latest     "/bin/sh -c '/etc/in 20 minutes ago
1566143ac885        1246944e6539                       "/bin/bash"          16 hours ago  
```

It is not true that:
`docker: image=organisation/gocd-server:latest state=running ports=8000:8000`

**Comment by somethingnew2-0** [comment] 2014-10-03 21:16
I have this same problem, I assumed that the ansible docker task would pull the latest everytime and restart the container if there was an update to that tag.  In spite of this, I think this code does the trick, but I'm still debugging.  I would love to see this issue solved.

```
- name: Pull and run Docker image
    docker: image=dockerfile/redis:latest name=redis state={{ item }}
    with_items:
      - absent
      - running
```

**Comment by somethingnew2-0** [comment] 2014-10-04 01:43
After some digging I have a solution https://github.com/somethingnew2-0/ansible-modules-core/commit/656c00f59cd79e5872b3daa09c215206a5ca6b65

Basically delete this block below which causes the code to pull the new image every time we create the container.  This will only work if the container was removed before (via absent) as with my `with_items` task above.

```
try:
    containers = do_create(count, params)
except:
```

There's probably a more elegant solution that could check to see if the docker image repo has the same tag as the current running container.  If it doesn't it could pull it down and restart the container.

Something like the following commit https://github.com/somethingnew2-0/ansible-modules-core/commit/a7db153290cba4fd1011b2854fe73bdcd9edd367

**Comment by somethingnew2-0** [comment] 2014-10-08 16:42
Well I tried, but the docker module wasn't doing it for me. Here's what I ended up using:

```
- hosts: all
  serial: 1
  vars:
    repo: myrepo
    container: myname
  tasks: 
  - name: Pull and run Docker image
    command: "{{ item }}"
    ignore_errors: yes
    with_items:
      - docker pull {{ repo }}/{{ container }}
      - docker stop {{ container }}
      - docker rm {{ container }}
      - docker run -d -P --name={{ container }} {{ repo }}/{{ container }}
```

Key takeaways:
`serial: 1` means only one host is updated at a time
`ignore_errors: yes` prevents the `docker stop` and `docker rm` from failing the playbook if the container didn't exist before
Also, don't forget the `-d` on `docker run` or else the playbook will never complete!

**Comment by bfleming-ciena** [comment] 2014-10-09 18:18
Thanks for following up.

**Comment by gmalouf** [comment] 2015-01-16 05:00
Are there actions to take for this issue or should it be closed?

**Comment by dsiegel** [comment] 2015-02-12 22:57
This problem makes the docker_module kind of useless. 

See the workaround by somethingnew2-0 above, which just uses the command module.

**Comment by MrMMorris** [comment] 2015-02-16 21:04
> This problem makes the docker_module kind of useless

+1

**Comment by abadger** [comment] 2015-03-13 18:21
I think that PR #502 and its followon tickets implemented this via the state=reloaded and pull=always flags parameters.  These have been merged into devel and stable-1.9.  Could someone take a look at one of those branches to see if this is resolved?

**Comment by dsiegel** [comment] 2015-03-14 03:05
That covers it nicely. Thanks.

**Comment by abadger** [comment] 2015-03-14 14:26
Thanks for testing!  Sorry it took so long to get something merged.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by abadger** 2015-03-14 14:26 UTC
Labels: bug_report, cloud, needs_info
