### ISSUE TITLE
Correct way to use debug?

### ISSUE THREAD

**Issue by pcj** [ansible/ansible-modules-core#1542] opened 2015-06-18 00:25 UTC
Trying to clarify if this is expected behavior:

```
  tasks:
  - debug: msg='Hello World'
```

succeeds with:

```
ok: [hostname] => {
    "msg": "Hello World"
}
```

Whereas debug message with a `prefix:` fails:

```
  tasks:
  - debug: msg='TODO: Hello World'
```

```
ERROR: Syntax Error while loading YAML script, playbook.yml
Note: The error may actually appear before this position: line 55, column 23

  - debug: msg='TODO: Hello World'
```

I was not able to discover the correct syntax to escape this, or come up with an answer why colons within a string literal (double or single delimiters) need be quoted in the first place.  Perhaps I should be using a different method to print messages to the user?

**Comment by bcoca** [comment] 2015-06-18 01:36
This is not a debug issue, its a yaml parsing issue, you have a : with a space w/o quoting the whole line (http://docs.ansible.com/YAMLSyntax.html#gotchas).

so you should write this:

`- debug: "msg='TODO: Hello world'"`

**Comment by bcoca** [comment] 2015-06-18 01:37
closing this as it is not a bug but the price of using YAML

**Closed as completed by bcoca** 2015-06-18 01:37 UTC

**Comment by pcj** [comment] 2015-06-18 03:14
@bcoca Thanks for clarification.
