### ISSUE TITLE
Service module fails when remote host is a docker container

### ISSUE THREAD

**Issue by rsyring** [ansible/ansible-modules-core#4024] opened 2016-06-23 17:27 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

service module
##### ANSIBLE VERSION

I've seen the problem with both:

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
ansible 1.9.6
  configured module search path = /usr/share/ansible
```
##### CONFIGURATION

Only using default values.
##### OS / ENVIRONMENT

Control host: Ubuntu 14.04
Connecting to: Ubuntu 14.04 on Docker version 1.9.1, build a34a1d5
##### SUMMARY

When using Ansible to connect to a docker container, restarting services using the service module does not work.  The task returns with a "changed" status but the process has not actually been restarted.

Verified with both the sshd service and the nginx service.
##### STEPS TO REPRODUCE

Build a docker image that can be used for this.  Example Dockerfile:

``` Dockerfile
# Use phusion/baseimage as base image. To make your builds reproducible, make
# sure you lock down to a specific version, not to `latest`!
# See https://github.com/phusion/baseimage-docker/blob/master/Changelog.md for
# a list of version numbers.
FROM phusion/baseimage:0.9.18

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

RUN rm -f /etc/service/sshd/down

# Regenerate SSH host keys. baseimage-docker does not contain any, so you
# have to do that yourself. You may also comment out this instruction; the
# init system will auto-generate one during boot.
RUN /etc/my_init.d/00_regen_ssh_host_keys.sh

# Keep this all by it's lonesome so we use the Docker cache and speed up development.
RUN apt-get update -q \
    && apt-get install -y python2.7 \
    && ln -s /usr/bin/python2.7 /usr/bin/python

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

Work with the docker image to get a container running:

``` shell
$ docker build -t ansible-service-bug .
$ docker run ansible-service-bug /sbin/my_init --enable-insecure-key

# open new terminal
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS             PORTS               NAMES
310b7a26d6ed        nsible-service-bug   "/sbin/my_init --enab"   5 seconds ago       Up 5 seconds                            sad_goodall
$ docker inspect -f "{{ .NetworkSettings.IPAddress }}" sad_goodall
172.17.0.2
```

Download the insecure key, test the ssh connection, verify the port sshd is running on:

``` shell
$ curl -o insecure_key -fSL https://github.com/phusion/baseimage-docker/raw/master/image/services/sshd/keys/insecure_key
$ ssh -i insecure_key root@172.17.0.2
root@310b7a26d6ed: cat /var/run/sshd.pid
22  # this number could be different, but note it
```

Run the following playbook:

``` yaml
- hosts: all
  vars:
    ansible_ssh_user: root
  gather_facts: false
  tasks:
    - service: name=ssh state=restarted
```

With the following command:

``` shell
$ ansible-playbook -i 172.17.0.2, playbook.yaml --private-key insecure_key 

PLAY [all] ******************************************************************** 

TASK: [service name=ssh state=restarted] ************************************** 
changed: [172.17.0.2]

PLAY RECAP ******************************************************************** 
172.17.0.2                 : ok=1    changed=1    unreachable=0    failed=0  
```

Now, in the ssh connection that should still be open to the docker container:

``` shell
root@310b7a26d6ed: cat /var/run/sshd.pid
22  # this number could be different, but note it
```
##### EXPECTED RESULTS

I expected the pid of the sshd server to change.
##### ACTUAL RESULTS

The restart task returns with a "changed" status but the service is not actually restarted.  The pid stays the same.
##### ADDITIONAL INFO
- I have verified the same behavior with nginx service.
- I have verified that the service module works correctly when connecting to a non-docker server running on Linode.
- I have verified that the service can be restarted using the init file directly and bypassing the service module.  See below for further details:

Change the playbook to:

``` yaml
- hosts: all
  vars:
    ansible_ssh_user: root
  gather_facts: false
  tasks:
    - command: /etc/init.d/ssh restart
```

Run it again:

``` shell
$ ansible-playbook -i 172.17.0.2, playbook.yaml --private-key insecure_key 

PLAY [all] ******************************************************************** 

TASK: [command /etc/init.d/ssh restart] *************************************** 
changed: [172.17.0.2]

PLAY RECAP ******************************************************************** 
172.17.0.2                 : ok=1    changed=1    unreachable=0    failed=0  
```

And in the ssh connection that should still be open to the docker container:

``` shell
root@310b7a26d6ed: cat /var/run/sshd.pid
132  # this number could be different, but it should be different from the commands ran earlier.
```

**Comment by bcoca** [comment] 2016-06-23 19:46
what is the value of the `ansible_service_mgr` fact for that container?

**Comment by rsyring** [comment] 2016-06-24 04:29
In the docker container built in the example I gave above, "my_init."  In a different docker container that simply runs ssh "sshd".  

I'm guessing the problem here is that my docker containers are not running a proper init system?  If this is a problem, then Ansible should at least bail on me.

**Comment by rsyring** [comment] 2016-06-24 04:42
Note that the container in the example above (phusion/baseimage) does contain a service management system, `runit`.  But, I see now that isn't supported: http://docs.ansible.com/ansible/service_module.html

So, my fault, sorry for the noise.  However, I **REALLY** think Ansible should fail if the service module is being used on a system that doesn't have a supported service manager.  It would have saved me hours of troubleshooting and have saved a bug report.  :)

**Comment by bcoca** [comment] 2016-07-23 22:03
Sadly service managers are not 100% possible to detect, nor is it possible to ensure all are absent. Ansible tries to find them and falls back to sysv init when in doubt. Docker makes this 'more fun' by sometimes lying to the system with a 'special' init or by just not having the init process that corresponds to the tools installed.

I'm going to close this as a duplicate of https://github.com/ansible/ansible-modules-core/issues/593, which has the same root problem, we cannot detect the proper/missing init system in some container systems.

**Closed as completed by bcoca** 2016-07-23 22:03 UTC
Labels: bug_report, cloud, docker
