### ISSUE TITLE
Changing default shell removes user from groups (OSX)

### ISSUE THREAD

**Issue by akhy** [ansible/ansible-modules-core#2616] opened 2015-12-03 10:41 UTC
```
- name: Change current user shell
  user: name={{ ansible_ssh_user }} shell={{ zsh_path }}
  become: yes
```

I'm playing this task to provision my OSX user to use ZSH from Homebrew. Strangely, this task also remove that user from several groups, most notably `admin` (thus removing its sudo privilege).

Before:

```
$ groups my_username
everyone localaccounts admin com.apple.sharepoint.group.1 _appstore _lpadmin _lpoperator _developer com.apple.access_screensharing com.apple.access_ssh com.apple.sharepoint.group.2
```

After:

```
$ groups my_username
everyone localaccounts com.apple.sharepoint.group.1 _lpoperator com.apple.sharepoint.group.2
```

Fortunately, I have another sudoer user to restore the groups. Otherwise, this would become nightmare for me. **Is it a bug, or did I do something wrong?**

---

EDIT: 
I'm executing the playbook like this (if it's really matter):

```
ansible-playbook osx.yml -i inventory --connection=local --ask-become-pass
```

**Comment by bcoca** [comment] 2015-12-03 15:28
duplicate of #2537

**Closed as completed by bcoca** 2015-12-03 15:28 UTC
