### ISSUE TITLE
apt module doesn't seem to support the long-form YAML syntax

### ISSUE THREAD

**Issue by firecat53** [ansible/ansible-modules-core#1900] opened 2015-08-11 00:14 UTC
Issue Type:

```
Bug Report
```

Ansible Version:  1.9.2

Ansible Configuration:

I have remote_user set to ansible and a python script set as the vault_password_file. Otherwise, no significant changes.

Environment:

Archlinux. Managing Ubuntu 14.04 system for this bug report

Summary:

When used in a playbook, the apt module works with the short-form YAML syntax but not the long form.

Steps To Reproduce:

roles/common/tasks/update.yml

```

---
- name: Ubuntu/Debian System upgrade
  apt:
    update_cache: yes
    upgrade: yes
  register: results_debian
  when: ansible_os_family == 'Debian'
```

Expected Results:

I'd expect this to run successfully, as I use the long form everywhere else in
my playbooks.

Actual Results:

```
ansible $ ansible-playbook -l vps update_all.yml 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [vps]

TASK: [Ubuntu/Debian System upgrade] ****************************************** 
failed: [vps] => {"failed": true}
msg: value of upgrade must be one of: yes,safe,full,dist, got: True

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/firecat53/update_all.retry

vps                        : ok=1    changed=0    unreachable=0    failed=1 
```

The following playbook runs normally:

```

---
- name: Ubuntu/Debian System upgrade
  apt:
    update_cache=yes upgrade=yes
  register: results_debian
  when: ansible_os_family == 'Debian'
```

Thanks!
Scott

**Comment by berislavlopac** [comment] 2015-09-02 20:21
Here's what I found on this issue and mistakenly submitted as a bug on the ansible repo:

In Ansible 1.9.2, for the following statement:

```
- name: apt upgrade
  apt: update_cache=no upgrade=no
```

I'm getting the following error:

```
TASK: [system | apt upgrade] ************************************************** 
failed: [default] => {"failed": true}
msg: value of upgrade must be one of: yes,safe,full,dist, got: no
```

That seems a bit in conflict with the documentation, which explicitly mentions `no` as a choice. In addition, the problem is even more pronounced if we use the extended yaml syntax:

```
- name: apt upgrade
  apt: 
    update_cache: yes
    upgrade: yes
```

In this form, even `yes` fails:

```
TASK: [system | apt upgrade] ************************************************** 
failed: [default] => {"failed": true}
msg: value of upgrade must be one of: yes,safe,full,dist, got: True
```

as the `yes` and `no` values are obviously first converted to boolean values (passing `"yes"` as a string works fine). While this is not explicitly stated in the docs, I think these values should be accepted here as well.

**Comment by t2d** [comment] 2015-11-16 08:54
In `ansible 1.9.4` the conversion is still happening:
Task:

```
  - name: Update packages
    apt:
      upgrade: yes
```

Result:

```
TASK: [Update packages] ******************************************************* 
failed: [localhost] => {"failed": true}
msg: value of upgrade must be one of: no,yes,safe,full,dist, got: True
```

**Comment by bcoca** [comment] 2015-11-16 15:59
This is not something Ansible can control as YAML itself will does the conversion, but YAML does give you a workaround, use quotes:

```
- apt:
      upgrade: "yes"
```

closing this ticket as there are really no actions to take on the development side.

**Closed as completed by bcoca** 2015-11-16 15:59 UTC
Labels: bug_report

**Comment by berislavlopac** [comment] 2015-11-16 17:20
Can this at least be stressed in the documentation?

**Comment by firecat53** [comment] 2015-11-16 19:34
That could be another note in the [Gotcha section](http://docs.ansible.com/ansible/YAMLSyntax.html#gotchas). Makes sense in hindsight...

**Comment by bcoca** [comment] 2015-11-16 20:06
added http://github.com/ansible/ansible/commit/1f34c6b214b1f9d792e99a619b04603b83743765
