### ISSUE TITLE
Apt Module with_items Broken

### ISSUE THREAD

**Issue by bbatsche** [ansible/ansible-modules-core#3145] opened 2016-02-29 18:49 UTC
##### Issue Type:
- Bug Report
##### Plugin Name:

apt
##### Ansible Version:

```
ansible 2.0.1.0
    config file = /Users/icemancast/vagrant-lamp/ansible.cfg
    configured module search path = Default w/o overrides
```
##### Environment:

Host: Mac OS X 10.10
Guest: Ubuntu 14.04
##### Summary:

Using `with_items` to specify packages to install with the `apt` module gives `TypeError: argument of type 'NoneType' is not iterable`
##### Steps To Reproduce:

``` yml
- name: Install System Utilties
  apt: package={{ item }} state=present
  become: yes
  with_items:
    - vim
    - git
    - curl
    - libcurl4-openssl-dev
    - build-essential
    - mailutils
    - apt-transport-https
    - ca-certificates
```
##### Expected Results:

Output from Ansible 2.0.0.2:

```
TASK [Common : Install System Utilties] ****************************************
ok: [vagrant] => (item=vim)
changed: [vagrant] => (item=git)
ok: [vagrant] => (item=curl)
changed: [vagrant] => (item=libcurl4-openssl-dev)
changed: [vagrant] => (item=build-essential)
changed: [vagrant] => (item=mailutils)
ok: [vagrant] => (item=apt-transport-https)
ok: [vagrant] => (item=ca-certificates)
```
##### Actual Results:

Output from Ansible 2.0.1.0

```
TASK [Common : Install System Utilties] ****************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: argument of type 'NoneType' is not iterable
fatal: [vagrant]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by Gaurav2Github** [comment] 2016-02-29 19:37
Error occurs when "package" alias is used in apt module
So, for now instead of "package" please use "name/pkg" alias. And you should be fine.

**Comment by bcoca** [comment] 2016-02-29 20:21
closing as dupe of #2300 2300

**Closed as completed by bcoca** 2016-02-29 20:21 UTC
Labels: bug_report
